ALTER TABLE `WA_Players`	CHANGE `name`		`name`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Players`	CHANGE `pass`		`pass`	VARCHAR(32)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Players`	CHANGE `money`		`money`	DOUBLE(11,2)	NOT NULL	DEFAULT '0.00';
ALTER TABLE `WA_Players`	CHANGE `itemsSold`	`itemsSold`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Players`	CHANGE `itemsBought`	`itemsBought` INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Players`	CHANGE `earnt`		`earnt`	DOUBLE(11,2)	NOT NULL	DEFAULT '0.00';
ALTER TABLE `WA_Players`	CHANGE `canBuy`		`canBuy`	TINYINT(1)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Players`	CHANGE `canSell`		`canSell`	TINYINT(1)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Players`	CHANGE `isAdmin`		`isAdmin`	TINYINT(1)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Items`		CHANGE `name`		`name`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Items`		CHANGE `damage`		`damage`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Items`		CHANGE `player`		`player`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Items`		CHANGE `quantity`		`quantity`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Enchantments`	CHANGE `enchName`		`enchName`	VARCHAR(32)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Enchantments`	CHANGE `enchId`		`enchId`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Enchantments`	CHANGE `level`		`level`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_EnchantLinks`	CHANGE `enchId`		`enchId`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_EnchantLinks`	CHANGE `itemTableId`	`itemTableId` INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_EnchantLinks`	CHANGE `itemId`		`itemId`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Auctions`	CHANGE `name`		`name`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Auctions`	CHANGE `damage`		`damage`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Auctions`	CHANGE `player`		`player`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Auctions`	CHANGE `quantity`		`quantity`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Auctions`	CHANGE `price`		`price`	DOUBLE(11,2)	NOT NULL	DEFAULT '0.00';
ALTER TABLE `WA_Auctions`	CHANGE `created`		`created`	DATETIME		NOT NULL	DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `WA_Auctions`	CHANGE `allowBids`	`allowBids`	TINYINT(1)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_Auctions`	CHANGE `currentBid`	`currentBid` DOUBLE(11,2)	NOT NULL	DEFAULT '0.00';
ALTER TABLE `WA_Auctions`	CHANGE `currentWinner`	`currentWinner` VARCHAR(16)	CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_SellPrice`	CHANGE `name`		`name`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_SellPrice`	CHANGE `damage`		`damage`	INT(11)		NOT NULL	DEFAULT '0';
ALTER TABLE `WA_SellPrice`	CHANGE `time`		`time`	DATETIME		NOT NULL	DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `WA_SellPrice`	CHANGE `quantity`		`quantity`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_SellPrice`	CHANGE `price`		`price`	DOUBLE(11,2)	NOT NULL DEFAULT '0.00';
ALTER TABLE `WA_SellPrice`	CHANGE `seller`		`seller`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_SellPrice`	CHANGE `buyer`		`buyer`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_MarketPrices`	CHANGE `name`		`name`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_MarketPrices`	CHANGE `damage`		`damage`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_MarketPrices`	CHANGE `time`		`time`	DATETIME		NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `WA_MarketPrices`	CHANGE `marketprice`	`marketprice` DOUBLE(11,2)	NOT NULL DEFAULT '0.00';
ALTER TABLE `WA_MarketPrices` CHANGE `ref`		`ref`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_Mail`		CHANGE `name`		`name`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_Mail`		CHANGE `damage`		`damage`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_Mail`		CHANGE `player`		`player`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_Mail`		CHANGE `quantity`		`quantity`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_RecentSigns`	CHANGE `world`		`world`	VARCHAR(32)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_RecentSigns`	CHANGE `offset`		`offset`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_RecentSigns`	CHANGE `x`			`x`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_RecentSigns`	CHANGE `y`			`y`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_RecentSigns`	CHANGE `z`			`z`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_ShoutSigns`	CHANGE `world`		`world`	VARCHAR(32)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_ShoutSigns`	CHANGE `radius`		`radius`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_ShoutSigns`	CHANGE `x`			`x`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_ShoutSigns`	CHANGE `y`			`y`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_ShoutSigns`	CHANGE `z`			`z`		INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_SaleAlerts`	CHANGE `seller`		`seller`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_SaleAlerts`	CHANGE `quantity`		`quantity`	INT(11)		NOT NULL DEFAULT '0';
ALTER TABLE `WA_SaleAlerts`	CHANGE `price`		`price`	DOUBLE(11,2)	NOT NULL DEFAULT '0.00';
ALTER TABLE `WA_SaleAlerts`	CHANGE `buyer`		`buyer`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_SaleAlerts`	CHANGE `item`		`item`	VARCHAR(16)		CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `WA_SaleAlerts`	CHANGE `alerted`		`alerted`	TINYINT(1)		NOT NULL DEFAULT '0';
DROP TABLE IF EXISTS `WA_StorageCheck`;
