<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Buildcraft - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'Buildcraft';

$Items[153]=array(
  'name'=>'Quarry',
  'icon'=>'Quarry.png',
  'pack'=>$pack);
$Items[154]=array(
  'name'=>'Landmark',
  'icon'=>'Landmark.png',
  'pack'=>$pack);
$Items[155]=array(
  'name'=>'Filler',
  'icon'=>'Filler.png',
  'pack'=>$pack);
$Items[157]=array(
  'name'=>'Builder',
  'icon'=>'Builder.png',
  'pack'=>$pack);
$Items[158]=array(
  'name'=>'Template Drawing Table',
  'icon'=>'Template_Drawing_Table.png',
  'pack'=>$pack);
$Items[160]=array(
  'name'=>'Frame',
  'icon'=>'Frame.png',
  'pack'=>$pack);
$Items[161]=array(
  0 =>array(
    'name'=>'Redstone Engine',
    'icon'=>'Engine_Redstone.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Steam Engine',
    'icon'=>'Engine_Steam.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Combustion Engine',
    'icon'=>'Engine_Combustion.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Engine',
    'icon'=>'Engine_Redstone.png',
    'pack'=>$pack),
);
$Items[162]=array(
  'name'=>'Oil',
  'icon'=>'Oil.png',
  'pack'=>$pack);
$Items[163]=array(
  'name'=>'Oil',
  'icon'=>'Oil.png',
  'pack'=>$pack);
$Items[164]=array(
  'name'=>'Pump',
  'icon'=>'Pump.png',
  'pack'=>$pack);
$Items[165]=array(
  'name'=>'Tank',
  'icon'=>'Tank.png',
  'pack'=>$pack);
$Items[167]=array(
  'name'=>'Refinery',
  'icon'=>'Refinery.png',
  'pack'=>$pack);
$Items[169]=array(
  'name'=>'Automatic Crafting Table',
  'icon'=>'Automatic_Crafting_Table.png',
  'pack'=>$pack);
$Items[171]=array(
  'name'=>'Mining Pipe',
  'icon'=>'Mining_Pipe.png',
  'pack'=>$pack);
$Items[174]=array(
  'name'=>'Mining Well',
  'icon'=>'Mining_Well.png',
  'pack'=>$pack);
$Items[4056]=array(
  'name'=>'Wooden Gear',
  'icon'=>'Gear_Wooden.png',
  'pack'=>$pack);
$Items[4057]=array(
  'name'=>'Stone Gear',
  'icon'=>'Gear_Stone.png',
  'pack'=>$pack);
$Items[4058]=array(
  'name'=>'Iron Gear',
  'icon'=>'Gear_Iron.png',
  'pack'=>$pack);
$Items[4059]=array(
  'name'=>'Gold Gear',
  'icon'=>'Gear_Gold.png',
  'pack'=>$pack);
$Items[4060]=array(
  'name'=>'Diamond Gear',
  'icon'=>'Gear_Diamond.png',
  'pack'=>$pack);
$Items[4061]=array(
  'type' =>'map',
  'title'=>'Template #map#',
  'name' =>'Template #map#',
  'icon' =>'Template.png',
  'stack'=>1,
  'pack' =>$pack);
$Items[4062]=array(
  'name'=>'Wrench',
  'icon'=>'Wrench.png',
  'pack'=>$pack);
$Items[4063]=array(
  'name'=>'Oil Bucket',
  'icon'=>'Bucket_Oil.png',
  'pack'=>$pack);
$Items[4065]=array(
  'name'=>'Pipe Waterproofing',
  'icon'=>'Waterproofing.png',
  'pack'=>$pack);
$Items[4066]=array(
  'name'=>'Fuel Bucket',
  'icon'=>'Bucket_Fuel.png',
  'pack'=>$pack);
$Items[4306]=array(
  'name'=>'Wooden Transport Pipe',
  'icon'=>'Pipe_Wooden.png',
  'pack'=>$pack);
$Items[4307]=array(
  'name'=>'Cobblestone Transport Pipe',
  'icon'=>'Pipe_Cobblestone.png',
  'pack'=>$pack);
$Items[4308]=array(
  'name'=>'Stone Transport Pipe',
  'icon'=>'Pipe_Stone.png',
  'pack'=>$pack);
$Items[4309]=array(
  'name'=>'Iron Transport Pipe',
  'icon'=>'Pipe_Iron.png',
  'pack'=>$pack);
$Items[4310]=array(
  'name'=>'Golden Transport Pipe',
  'icon'=>'Pipe_Golden.png',
  'pack'=>$pack);
$Items[4311]=array(
  'name'=>'Diamond Transport Pipe',
  'icon'=>'Pipe_Diamond.png',
  'pack'=>$pack);
$Items[4312]=array(
  'name'=>'Obsidian Transport Pipe',
  'icon'=>'Pipe_Obsidian.png',
  'pack'=>$pack);
$Items[4313]=array(
  'name'=>'Wooden Waterproof Pipe',
  'icon'=>'Pipe_Wooden_Waterproof.png',
  'pack'=>$pack);
$Items[4314]=array(
  'name'=>'Cobblestone Waterproof Pipe',
  'icon'=>'Pipe_Cobblestone_Waterproof.png',
  'pack'=>$pack);
$Items[4315]=array(
  'name'=>'Stone Waterproof Pipe',
  'icon'=>'Pipe_Stone_Waterproof.png',
  'pack'=>$pack);
$Items[4316]=array(
  'name'=>'Iron Waterproof Pipe',
  'icon'=>'Pipe_Iron_Waterproof.png',
  'pack'=>$pack);
$Items[4317]=array(
  'name'=>'Golden Waterproof Pipe',
  'icon'=>'Pipe_Golden_Waterproof.png',
  'pack'=>$pack);
$Items[4320]=array(
  'name'=>'Wooden Conductive Pipe',
  'icon'=>'Pipe_Wooden_Conductive.png',
  'pack'=>$pack);
$Items[4322]=array(
  'name'=>'Stone Conductive Pipe',
  'icon'=>'Pipe_Stone_Conductive.png',
  'pack'=>$pack);
$Items[4324]=array(
  'name'=>'Golden Conductive Pipe',
  'icon'=>'Pipe_Golden_Conductive.png',
  'pack'=>$pack);

unset($Items);
?>