<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Balkon Weapons Mod - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'Balkon';

$Items[26483]=array(
  'type' =>'tool',
  'name' =>'Wooden Spear',
  'title'=>'Wooden Spear %damaged%',
  'icon' =>'Wooden_Spear.png',
  'damage'=>60,
  'stack'=>1,
  'pack' =>$pack);
$Items[26484]=array(
  'type' =>'tool',
  'name' =>'Stone Spear',
  'title'=>'Stone Spear %damaged%',
  'icon' =>'Stone_Spear.png',
  'damage'=>132,
  'stack'=>1,
  'pack' =>$pack);
$Items[26485]=array(
  'type' =>'tool',
  'name' =>'Iron Spear',
  'title'=>'Iron Spear %damaged%',
  'icon' =>'Iron_Spear.png',
  'damage'=>251,
  'stack'=>1,
  'pack' =>$pack);
$Items[26486]=array(
  'type' =>'tool',
  'name' =>'Diamond Spear',
  'title'=>'Diamond Spear %damaged%',
  'icon' =>'Diamond_Spear.png',
  'damage'=>1562,
  'stack'=>1,
  'pack' =>$pack);
$Items[26487]=array(
  'type' =>'tool',
  'name' =>'Golden Spear',
  'title'=>'Golden Spear %damaged%',
  'icon' =>'Golden_Spear.png',
  'damage'=>33,
  'stack'=>1,
  'pack' =>$pack);
$Items[26488]=array(
  'type' =>'tool',
  'name' =>'Wooden Halberd',
  'title'=>'Wooden Halberd %damaged%',
  'icon' =>'Wooden_Halberd.png',
  'damage'=>60,
  'stack'=>1,
  'pack' =>$pack);
$Items[26489]=array(
  'type' =>'tool',
  'name' =>'Stone Halberd',
  'title'=>'Stone Halberd %damaged%',
  'icon' =>'Stone_Halberd.png',
  'damage'=>132,
  'stack'=>1,
  'pack' =>$pack);
$Items[26490]=array(
  'type' =>'tool',
  'name' =>'Iron Halberd',
  'title'=>'Iron Halberd %damaged%',
  'icon' =>'Iron_Halberd.png',
  'damage'=>251,
  'stack'=>1,
  'pack' =>$pack);
$Items[26491]=array(
  'type' =>'tool',
  'name' =>'Diamond Halberd',
  'title'=>'Diamond Halberd %damaged%',
  'icon' =>'Diamond_Halberd.png',
  'damage'=>1562,
  'stack'=>1,
  'pack' =>$pack);
$Items[26492]=array(
  'type' =>'tool',
  'name' =>'Golden Halberd',
  'title'=>'Golden Halberd %damaged%',
  'icon' =>'Golden_Halberd.png',
  'damage'=>33,
  'stack'=>1,
  'pack' =>$pack);
$Items[26493]=array(
  'type' =>'tool',
  'name' =>'Wooden Battleaxe',
  'title'=>'Wooden Battleaxe %damaged%',
  'icon' =>'Wooden_Battleaxe.png',
  'damage'=>60,
  'stack'=>1,
  'pack' =>$pack);
$Items[26494]=array(
  'type' =>'tool',
  'name' =>'Stone Battleaxe',
  'title'=>'Stone Battleaxe %damaged%',
  'icon' =>'Stone_Battleaxe.png',
  'damage'=>132,
  'stack'=>1,
  'pack' =>$pack);
$Items[26495]=array(
  'type' =>'tool',
  'name' =>'Iron Battleaxe',
  'title'=>'Iron Battleaxe %damaged%',
  'icon' =>'Iron_Battleaxe.png',
  'damage'=>251,
  'stack'=>1,
  'pack' =>$pack);
$Items[26496]=array(
  'type' =>'tool',
  'name' =>'Diamond Battleaxe',
  'title'=>'Diamond Battleaxe %damaged%',
  'icon' =>'Diamond_Battleaxe.png',
  'damage'=>1562,
  'stack'=>1,
  'pack' =>$pack);
$Items[26497]=array(
  'type' =>'tool',
  'name' =>'Golden Battleaxe',
  'title'=>'Golden Battleaxe %damaged%',
  'icon' =>'Golden_Battleaxe.png',
  'damage'=>33,
  'stack'=>1,
  'pack' =>$pack);
$Items[26498]=array(
  'type' =>'tool',
  'name' =>'Wooden Warhammer',
  'title'=>'Wooden Warhammer %damaged%',
  'icon' =>'Wooden_Warhammer.png',
  'damage'=>60,
  'stack'=>1,
  'pack' =>$pack);
$Items[26499]=array(
  'type' =>'tool',
  'name' =>'Stone Warhammer',
  'title'=>'Stone Warhammer %damaged%',
  'icon' =>'Stone_Warhammer.png',
  'damage'=>132,
  'stack'=>1,
  'pack' =>$pack);
$Items[26500]=array(
  'type' =>'tool',
  'name' =>'Iron Warhammer',
  'title'=>'Iron Warhammer %damaged%',
  'icon' =>'Iron_Warhammer.png',
  'damage'=>251,
  'stack'=>1,
  'pack' =>$pack);
$Items[26501]=array(
  'type' =>'tool',
  'name' =>'Diamond Warhammer',
  'title'=>'Diamond Warhammer %damaged%',
  'icon' =>'Diamond_Warhammer.png',
  'damage'=>1562,
  'stack'=>1,
  'pack' =>$pack);
$Items[26502]=array(
  'type' =>'tool',
  'name' =>'Golden Warhammer',
  'title'=>'Golden Warhammer %damaged%',
  'icon' =>'Golden_Warhammer.png',
  'damage'=>33,
  'stack'=>1,
  'pack' =>$pack);
$Items[26503]=array(
  'type' =>'tool',
  'name' =>'Wooden Knife',
  'title'=>'Wooden Knife %damaged%',
  'icon' =>'Wooden_Knife.png',
  'damage'=>30,
  'stack'=>1,
  'pack' =>$pack);
$Items[26504]=array(
  'type' =>'tool',
  'name' =>'Stone Knife',
  'title'=>'Stone Knife %damaged%',
  'icon' =>'Stone_Knife.png',
  'damage'=>66,
  'stack'=>1,
  'pack' =>$pack);
$Items[26505]=array(
  'type' =>'tool',
  'name' =>'Iron Knife',
  'title'=>'Iron Knife %damaged%',
  'icon' =>'Iron_Knife.png',
  'damage'=>126,
  'stack'=>1,
  'pack' =>$pack);
$Items[26506]=array(
  'type' =>'tool',
  'name' =>'Diamond Knife',
  'title'=>'Diamond Knife %damaged%',
  'icon' =>'Diamond_Knife.png',
  'damage'=>781,
  'stack'=>1,
  'pack' =>$pack);
$Items[26507]=array(
  'type' =>'tool',
  'name' =>'Golden Knife',
  'title'=>'Golden Knife %damaged%',
  'icon' =>'Golden_Knife.png',
  'damage'=>17,
  'stack'=>1,
  'pack' =>$pack);



// more items to add here!





unset($Items);
?>
