<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Balkon Weapons Mod - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'Balkon';

3323=>array(
  'type' =>'tool',
  'name' =>'Wooden Spear',
  'title'=>'Wooden Spear %damaged%',
  'icon' =>'Balkon_Wooden_Spear.png',
  'damage'=>60,
  'stack'=>1,
3324=>array(
  'type' =>'tool',
  'name' =>'Stone Spear',
  'title'=>'Stone Spear %damaged%',
  'icon' =>'Balkon_Stone_Spear.png',
  'damage'=>132,
  'stack'=>1,
3325=>array(
  'type' =>'tool',
  'name' =>'Iron Spear',
  'title'=>'Iron Spear %damaged%',
  'icon' =>'Balkon_Iron_Spear.png',
  'damage'=>251,
  'stack'=>1,
3326=>array(
  'type' =>'tool',
  'name' =>'Diamond Spear',
  'title'=>'Diamond Spear %damaged%',
  'icon' =>'Balkon_Diamond_Spear.png',
  'damage'=>1562,
  'stack'=>1,
3327=>array(
  'type' =>'tool',
  'name' =>'Golden Spear',
  'title'=>'Golden Spear %damaged%',
  'icon' =>'Balkon_Golden_Spear.png',
  'damage'=>33,
  'stack'=>1,
3328=>array(
  'type' =>'tool',
  'name' =>'Wooden Halberd',
  'title'=>'Wooden Halberd %damaged%',
  'icon' =>'Balkon_Wooden_Halberd.png',
  'damage'=>60,
  'stack'=>1,
3329=>array(
  'type' =>'tool',
  'name' =>'Stone Halberd',
  'title'=>'Stone Halberd %damaged%',
  'icon' =>'Balkon_Stone_Halberd.png',
  'damage'=>132,
  'stack'=>1,
3330=>array(
  'type' =>'tool',
  'name' =>'Iron Halberd',
  'title'=>'Iron Halberd %damaged%',
  'icon' =>'Balkon_Iron_Halberd.png',
  'damage'=>251,
  'stack'=>1,
3331=>array(
  'type' =>'tool',
  'name' =>'Diamond Halberd',
  'title'=>'Diamond Halberd %damaged%',
  'icon' =>'Balkon_Diamond_Halberd.png',
  'damage'=>1562,
  'stack'=>1,
3332=>array(
  'type' =>'tool',
  'name' =>'Golden Halberd',
  'title'=>'Golden Halberd %damaged%',
  'icon' =>'Balkon_Golden_Halberd.png',
  'damage'=>33,
  'stack'=>1,
3333=>array(
  'type' =>'tool',
  'name' =>'Wooden Battleaxe',
  'title'=>'Wooden Battleaxe %damaged%',
  'icon' =>'Balkon_Wooden_Battleaxe.png',
  'damage'=>60,
  'stack'=>1,
3334=>array(
  'type' =>'tool',
  'name' =>'Stone Battleaxe',
  'title'=>'Stone Battleaxe %damaged%',
  'icon' =>'Balkon_Stone_Battleaxe.png',
  'damage'=>132,
  'stack'=>1,
3335=>array(
  'type' =>'tool',
  'name' =>'Iron Battleaxe',
  'title'=>'Iron Battleaxe %damaged%',
  'icon' =>'Balkon_Iron_Battleaxe.png',
  'damage'=>251,
  'stack'=>1,
3336=>array(
  'type' =>'tool',
  'name' =>'Diamond Battleaxe',
  'title'=>'Diamond Battleaxe %damaged%',
  'icon' =>'Balkon_Diamond_Battleaxe.png',
  'damage'=>1562,
  'stack'=>1,
3337=>array(
  'type' =>'tool',
  'name' =>'Golden Battleaxe',
  'title'=>'Golden Battleaxe %damaged%',
  'icon' =>'Balkon_Golden_Battleaxe.png',
  'damage'=>33,
  'stack'=>1,
3338=>array(
  'type' =>'tool',
  'name' =>'Wooden Warhammer',
  'title'=>'Wooden Warhammer %damaged%',
  'icon' =>'Balkon_Wooden_Warhammer.png',
  'damage'=>60,
  'stack'=>1,
3339=>array(
  'type' =>'tool',
  'name' =>'Stone Warhammer',
  'title'=>'Stone Warhammer %damaged%',
  'icon' =>'Balkon_Stone_Warhammer.png',
  'damage'=>132,
  'stack'=>1,
3340=>array(
  'type' =>'tool',
  'name' =>'Iron Warhammer',
  'title'=>'Iron Warhammer %damaged%',
  'icon' =>'Balkon_Iron_Warhammer.png',
  'damage'=>251,
  'stack'=>1,
3341=>array(
  'type' =>'tool',
  'name' =>'Diamond Warhammer',
  'title'=>'Diamond Warhammer %damaged%',
  'icon' =>'Balkon_Diamond_Warhammer.png',
  'damage'=>1562,
  'stack'=>1,
3342=>array(
  'type' =>'tool',
  'name' =>'Golden Warhammer',
  'title'=>'Golden Warhammer %damaged%',
  'icon' =>'Balkon_Golden_Warhammer.png',
  'damage'=>33,
  'stack'=>1,
3343=>array(
  'type' =>'tool',
  'name' =>'Wooden Knife',
  'title'=>'Wooden Knife %damaged%',
  'icon' =>'Balkon_Wooden_Knife.png',
  'damage'=>30,
  'stack'=>1,
3344=>array(
  'type' =>'tool',
  'name' =>'Stone Knife',
  'title'=>'Stone Knife %damaged%',
  'icon' =>'Balkon_Stone_Knife.png',
  'damage'=>66,
  'stack'=>1,
3345=>array(
  'type' =>'tool',
  'name' =>'Iron Knife',
  'title'=>'Iron Knife %damaged%',
  'icon' =>'Balkon_Iron_Knife.png',
  'damage'=>126,
  'stack'=>1,
3346=>array(
  'type' =>'tool',
  'name' =>'Diamond Knife',
  'title'=>'Diamond Knife %damaged%',
  'icon' =>'Balkon_Diamond_Knife.png',
  'damage'=>781,
  'stack'=>1,
3347=>array(
  'type' =>'tool',
  'name' =>'Golden Knife',
  'title'=>'Golden Knife %damaged%',
  'icon' =>'Balkon_Golden_Knife.png',
  'damage'=>17,
  'stack'=>1,



// more items to add here!





unset($Items);
?>