<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// RailCraft - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'RailCraft';

$Items[206]=array(
  0 =>array(
    'name'=>'Boarding Track',
    'icon'=>'Track_Boarding.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Holding Track',
    'icon'=>'Track_Holding.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'One-Way Track',
    'icon'=>'Track_One-Way.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Control Track',
    'icon'=>'Track_Control.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Launcher Track',
    'icon'=>'Track_Launcher.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Priming Track',
    'icon'=>'Track_Priming.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Junction Track',
    'icon'=>'Track_Junction.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Track Switch',
    'icon'=>'Track_Switch.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Disembarking Track',
    'icon'=>'Track_Disembarking.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Suspended Track',
    'icon'=>'Track_Suspended.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Gated One-Way Track',
    'icon'=>'Track_Gated_One-Way.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Gated Track',
    'icon'=>'Track_Gated.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Wooden Track',
    'icon'=>'Track_Wooden.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Wooden Booster Track',
    'icon'=>'Track_Wooden_Booster.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Wooden Junction Track',
    'icon'=>'Track_Wooden_Junction.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Wooden Track Switch',
    'icon'=>'Track_Wooden_Switch.png',
    'pack'=>$pack),
  16=>array(
    'name'=>'HS Track',
    'icon'=>'Track_HS.png',
    'pack'=>$pack),
  17=>array(
    'name'=>'HS Booster Track',
    'icon'=>'Track_HS_Booster.png',
    'pack'=>$pack),
  18=>array(
    'name'=>'HS Transition Track',
    'icon'=>'Track_HS_Transition.png',
    'pack'=>$pack),
  19=>array(
    'name'=>'HS Switch Track',
    'icon'=>'Track_HS_Switch.png',
    'pack'=>$pack),
  20=>array(
    'name'=>'Train Boarding Track',
    'icon'=>'Track_Train_Boarding.png',
    'pack'=>$pack),
  21=>array(
    'name'=>'Train Holding Track',
    'icon'=>'Track_Train_Holding.png',
    'pack'=>$pack),
  22=>array(
    'name'=>'Coupler Track',
    'icon'=>'Track_Coupler.png',
    'pack'=>$pack),
  23=>array(
    'name'=>'Decoupler Track',
    'icon'=>'Track_Decoupler.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Track',
    'icon'=>'Track_Switch.png',
    'pack'=>$pack),
);
$Items[209]=array(
  1 =>array(
    'name'=>'Dual-Head Block Signal',
    'icon'=>'Signal_Block_Dual-Head.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Switch Motor',
    'icon'=>'Switch_Motor.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Block Signal',
    'icon'=>'Signal_Block.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Switch Lever',
    'icon'=>'Switch_Lever.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Wooden Post',
    'icon'=>'Post_Wooden.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Stone Post',
    'icon'=>'Post_Stone.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Signal Receiver Box',
    'icon'=>'Signal_Box_Receiver.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Signal Controller Box',
    'icon'=>'Signal_Box_Controller.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Distant Signal',
    'icon'=>'Signal_Distant.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Signal',
    'icon'=>'Signal_Block.png',
    'pack'=>$pack),
);
$Items[211]=array(
  0 =>array(
    'name'=>'Storage Detector',
    'icon'=>'Detector_Storage.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Any Detector',
    'icon'=>'Detector_Any.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Empty Detector',
    'icon'=>'Detector_Empty.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Mob Detector',
    'icon'=>'Detector_Mob.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Powered Detector',
    'icon'=>'Detector_Powered.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Player Detector',
    'icon'=>'Detector_Player.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Explosive Detector',
    'icon'=>'Detector_Explosive.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Animal Detector',
    'icon'=>'Detector_Animal.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Tank Detector',
    'icon'=>'Detector_Tank.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Advanced Detector',
    'icon'=>'Detector_Advanced.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Energy Detector',
    'icon'=>'Detector_Energy.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Growth Detector',
    'icon'=>'Detector_Growth.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Train Detector',
    'icon'=>'Detector_Train.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Detector',
    'icon'=>'Detector_Energy.png',
    'pack'=>$pack),
);
$Items[212]=array(
  'name'=>'Elevator Track',
  'icon'=>'Track_Elevator.png',
  'pack'=>$pack);
$Items[213]=array(
  0 =>array(
    'name'=>'Item Loader',
    'icon'=>'Loader_Item.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Item Unloader',
    'icon'=>'Unloader_Item.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Item Adv. Loader',
    'icon'=>'Loader_Item_Adv.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Liquid Loader',
    'icon'=>'Loader_Liquid.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Liquid Unloader',
    'icon'=>'Unloader_Liquid.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Adv. Item Unloader',
    'icon'=>'Unloader_Item_Adv.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Cart Dispenser',
    'icon'=>'Dispenser_Cart.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Coke Oven Brick',
    'icon'=>'Brick_Coke_Oven.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Rolling Machine',
    'icon'=>'Rolling_Machine.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Energy Loader',
    'icon'=>'Loader_Energy.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Energy Unloader',
    'icon'=>'Unloader_Energy.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Feed Station',
    'icon'=>'Feed_Station.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Blast Furnace Brick',
    'icon'=>'Brick_Blast_Furnace.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Train Dispenser',
    'icon'=>'Dispenser_Train.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Banded Planks',
    'icon'=>'Banded_Planks.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Loader',
    'icon'=>'Loader_Energy.png',
    'pack'=>$pack),
);
$Items[214]=array(
  0 =>array(
    'name'=>'World Anchor',
    'icon'=>'World_Anchor.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Concrete_Block.png',
    'icon'=>'Block of Concrete',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Block of Steel',
    'icon'=>'Steel_Block.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Infernal Brick',
    'icon'=>'Infernal_Brick.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'',
    'icon'=>'',
    'pack'=>$pack),
);
$Items[7256]=array(
  'name'=>'MFSU Cart',
  'icon'=>'Cart_MFSU.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7257]=array(
  'name'=>'Stone Railbed',
  'icon'=>'Railbed_Stone.png',
  'pack'=>$pack);
$Items[7260]=array(
  'name'=>'Signal Tuner',
  'icon'=>'Signal_Tuner.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7261]=array(
  'name'=>'Signal Block Surveyor',
  'icon'=>'Signal_Block_Surveyor.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7262]=array(
  'name'=>'Rebar',
  'icon'=>'Rebar.png',
  'pack'=>$pack);
$Items[7266]=array(
  0 =>array(
    'name'=>'Metal Post',
    'icon'=>'Post_Metal.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Metal Post (Black)',
    'icon'=>'Post_Metal_Black.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Metal Post (Red)',
    'icon'=>'Post_Metal_Red.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Metal Post (Green)',
    'icon'=>'Post_Metal_Green.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Metal Post (Brown)',
    'icon'=>'Post_Metal_Brown.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Metal Post (Blue)',
    'icon'=>'Post_Metal_Blue.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Metal Post (Purple)',
    'icon'=>'Post_Metal_Purple.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Metal Post (Cyan)',
    'icon'=>'Post_Metal_Cyan.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Metal Post (Light Grey)',
    'icon'=>'Post_Metal_Light_Grey.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Metal Post (Grey)',
    'icon'=>'Post_Metal_Grey.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Metal Post (Pink)',
    'icon'=>'Post_Metal_Pink.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Metal Post (Light Green)',
    'icon'=>'Post_Metal_Light_Green.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Metal Post (Yellow)',
    'icon'=>'Post_Metal_Yellow.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Metal Post (Light Blue)',
    'icon'=>'Post_Metal_Light_Blue.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Metal Post (Magenta)',
    'icon'=>'Post_Metal_Magenta.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Metal Post (Orange)',
    'icon'=>'Post_Metal_Orange.png',
    'pack'=>$pack),
  16=>array(
    'name'=>'Metal Post (White)',
    'icon'=>'Post_Metal_White.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Metal Post',
    'icon'=>'Post_Metal_White.png',
    'pack'=>$pack),
);
$Items[7267]=array(
  'name'=>'Stone Tie',
  'icon'=>'Tie_Stone.png',
  'pack'=>$pack);
$Items[7268]=array(
  'name'=>'Controller Circuit',
  'icon'=>'Circuit_Controller.png',
  'pack'=>$pack);
$Items[7269]=array(
  'name'=>'Creosote Oil',
  'icon'=>'Creosote_Oil.png',
  'pack'=>$pack);
$Items[7270]=array(
  'name'=>'TNT Cart',
  'icon'=>'Cart_TNT.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7272]=array(
  'name'=>'Steel Bore Head',
  'icon'=>'Bore_Head_Steel.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7276]=array(
  'name'=>'Batbox Cart',
  'icon'=>'Cart_Batbox.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7281]=array(
  'name'=>'Work Cart',
  'icon'=>'Cart_Work.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7291]=array(
  'name'=>'Coal Coke',
  'icon'=>'Coal_Coke.png',
  'pack'=>$pack);
$Items[7292]=array(
  'name'=>'Steel Ingot',
  'icon'=>'Steel_Ingot.png',
  'pack'=>$pack);
$Items[7293]=array(
  'name'=>'Standard Rail',
  'icon'=>'Rail_Standard.png',
  'pack'=>$pack);
$Items[7294]=array(
  'name'=>'HS Rail',
  'icon'=>'Rail_HS.png',
  'pack'=>$pack);
$Items[7300]=array(
  'name'=>'Advanced Rail',
  'icon'=>'Rail_Advanced.png',
  'pack'=>$pack);
$Items[7302]=array(
  'name'=>'Wooden Tie',
  'icon'=>'Tie_Wooden.png',
  'pack'=>$pack);
$Items[7303]=array(
  'name'=>'Anchor Cart',
  'icon'=>'Cart_Anchor.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7304]=array(
  'name'=>'Receiver Circuit',
  'icon'=>'Circuit_Receiver.png',
  'pack'=>$pack);
$Items[7305]=array(
  'name'=>'',
  'icon'=>'',
  'pack'=>$pack);
$Items[7306]=array(
  'name'=>'Wooden Railbed',
  'icon'=>'Railbed_Wooden.png',
  'pack'=>$pack);
$Items[7307]=array(
  'name'=>'MFE Cart',
  'icon'=>'Cart_MFE.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7308]=array(
  'name'=>'Iron Bore Head',
  'icon'=>'Bore_Head_Iron.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7310]=array(
  'name'=>'Tunnel Bore Machine',
  'icon'=>'Tunnel_Bore.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7312]=array(
  'name'=>'Tank Cart',
  'icon'=>'Cart_Tank.png',
  'stack'=>3,
  'pack'=>$pack);
$Items[7313]=array(
  'name'=>'Signal Lamp',
  'icon'=>'Signal_Lamp.png',
  'pack'=>$pack);
$Items[7314]=array(
  'name'=>'Diamond Bore Head',
  'icon'=>'Bore_Head_Diamond.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[7315]=array(
  'name'=>'Crowbar',
  'icon'=>'Crowbar.png',
  'pack'=>$pack);
$Items[7316]=array(
  'name'=>'Lapotron Loader Upgrade',
  'icon'=>'Lapotron_Loader_Upgrade.png',
  'stack'=>9,
  'pack'=>$pack);

unset($Items);
?>