<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Equivalent Exchange 2 - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'EquivalentExchange2';

// Rings
$Items[27584]=array(
  0 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_1.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_2.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_3.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_4.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_5.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_6.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Ring Of Arcana',
    'icon'=>'Ring_Of_Arcana_7.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Arcana Ring',
    'icon'=>'Ring_Of_Arcana_0.png',
    'pack'=>$pack),
);

$Items[27528]=array(
  'name'=>'Iron Band',
  'icon'=>'Iron_Band.png',
  'pack'=>$pack);
$Items[27534]=array(
  'name'=>'Archangels Smite',
  'icon'=>'Archangels_Smite.png',
  'pack'=>$pack);
$Items[27532]=array(
  0 =>array(
    'name'=>'Black Hole Band',
    'icon'=>'Black_Hole_Band_1.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Black Hole Band',
    'icon'=>'Black_Hole_Band_2.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Black Hole Band',
    'icon'=>'Black_Hole_Band_1.png',
    'pack'=>$pack),
);
$Items[27537]=array(
  0 =>array(
    'name'=>'Harvest Goddess Band',
    'icon'=>'Harvest_Goddess_Band_1.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Harvest Goddess Band',
    'icon'=>'Harvest_Goddess_Band_2.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Band',
    'icon'=>'Harvest_Goddess_Band_1.png',
    'pack'=>$pack),
);
$Items[27533]=array(
  0 =>array(
    'name'=>'Ring Of Ignition',
    'icon'=>'Ring_Of_Ignition_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Ring Of Ignition',
    'icon'=>'Ring_Of_Ignition_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Ring Of Ignition',
    'icon'=>'Ring_Of_Ignition_0.png',
    'pack'=>$pack),
);
$Items[27536]=array(
  0 =>array(
    'name'=>'Swiftwolfs_Rending_Gale',
    'icon'=>'Swiftwolfs_Rending_Gale_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Swiftwolfs_Rending_Gale',
    'icon'=>'Swiftwolfs_Rending_Gale_1.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Swiftwolfs_Rending_Gale',
    'icon'=>'Swiftwolfs_Rending_Gale_2.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Swiftwolfs_Rending_Gale',
    'icon'=>'Swiftwolfs_Rending_Gale_3.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Gale',
    'icon'=>'Swiftwolfs_Rending_Gale_0.png',
    'pack'=>$pack),
);
$Items[27593]=array(
  0 =>array(
    'name'=>'Void Ring',
    'icon'=>'Void_Ring_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Void Ring',
    'icon'=>'Void_Ring_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Void Ring',
    'icon'=>'Void_Ring_0.png',
    'pack'=>$pack),
);
$Items[27574]=array(
  0 =>array(
    'name'=>'Zero Ring',
    'icon'=>'Zero_Ring_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Zero Ring',
    'icon'=>'Zero_Ring_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Zero Ring',
    'icon'=>'Zero_Ring_0.png',
    'pack'=>$pack),
);

// Power Stones
$Items[27588]=array(
  0 =>array(
    'name'=>'Body Stone',
    'icon'=>'Body_Stone_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Body Stone',
    'icon'=>'Body_Stone_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Body Stone',
    'icon'=>'Body_Stone_0.png',
    'pack'=>$pack),
);
$Items[27529]=array(
  0 =>array(
    'name'=>'Soul Stone',
    'icon'=>'Soul_Stone_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Soul Stone',
    'icon'=>'Soul_Stone_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Soul Stone',
    'icon'=>'Soul_Stone_0.png',
    'pack'=>$pack),
);
$Items[27589]=array(
  0 =>array(
    'name'=>'Life Stone',
    'icon'=>'Life_Stone_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Life Stone',
    'icon'=>'Life_Stone_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Life Stone',
    'icon'=>'Life_Stone_0.png',
    'pack'=>$pack),
);
$Items[27590]=array(
  0 =>array(
    'name'=>'Mind Stone',
    'icon'=>'Mind_Stone_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Mind Stone',
    'icon'=>'Mind_Stone_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Mind Stone',
    'icon'=>'Mind_Stone_0.png',
    'pack'=>$pack),
);
$Items[27526]=array(
  'name'=>'Philosophers Stone',
  'icon'=>'Philosophers_Stone.png',
  'pack'=>$pack);
$Items[27527]=array(
  'name'=>'Destruction Catalyst',
  'icon'=>'Destruction_Catalyst.png',
  'pack'=>$pack);
$Items[27535]=array(
  'name'=>'Hyperkinetic Lens',
  'icon'=>'Hyperkinetic_Lens.png',
  'pack'=>$pack);
$Items[27528]=array(
  'name'=>'Catalytic Lens',
  'icon'=>'Catalytic_Lens.png',
  'pack'=>$pack);

// Materials
$Items[27539]=array(
  'name'=>'Alchemical Coal',
  'icon'=>'Alchemical_Coal.png',
  'pack'=>$pack);
$Items[27540]=array(
  'name'=>'Mobius Fuel',
  'icon'=>'Mobius_Fuel.png',
  'pack'=>$pack);
$Items[27571]=array(
  'name'=>'Aeternalis Fuel',
  'icon'=>'Aeternalis_Fuel.png',
  'pack'=>$pack);
$Items[27541]=array(
  'name'=>'Dark Matter',
  'icon'=>'Dark_Matter.png',
  'pack'=>$pack);
$Items[27563]=array(
  'name'=>'Red Matter',
  'icon'=>'Red_Matter.png',
  'pack'=>$pack);

// Dark Matter Tools
$Items[27543]=array(
  'name'=>'Dark Matter Pickaxe',
  'icon'=>'Dark_Matter_Pickaxe.png',
  'pack'=>$pack);
$Items[27544]=array(
  'name'=>'Dark Matter Shovel',
  'icon'=>'Dark_Matter_Shovel.png',
  'pack'=>$pack);
$Items[27545]=array(
  'name'=>'Dark Matter Hoe',
  'icon'=>'Dark_Matter_Hoe.png',
  'pack'=>$pack);
$Items[27546]=array(
  'name'=>'Dark Matter Sword',
  'icon'=>'Dark_Matter_Sword.png',
  'pack'=>$pack);
$Items[27547]=array(
  'name'=>'Dark Matter Axe',
  'icon'=>'Dark_Matter_Axe.png',
  'pack'=>$pack);
$Items[27548]=array(
  'name'=>'Dark Matter Shears',
  'icon'=>'Dark_Matter_Shears.png',
  'pack'=>$pack);
$Items[27555]=array(
  'name'=>'Dark Matter Hammer',
  'icon'=>'Dark_Matter_Hammer.png',
  'pack'=>$pack);

// Red Matter Tools
$Items[27564]=array(
  'name'=>'Red Matter Pickaxe',
  'icon'=>'Red_Matter_Pickaxe.png',
  'pack'=>$pack);
$Items[27565]=array(
  'name'=>'Red Matter Shovel',
  'icon'=>'Red_Matter_Shovel.png',
  'pack'=>$pack);
$Items[27566]=array(
  'name'=>'Red Matter Hoe',
  'icon'=>'Red_Matter_Hoe.png',
  'pack'=>$pack);
$Items[27567]=array(
  'name'=>'Red Matter Sword',
  'icon'=>'Red_Matter_Sword.png',
  'pack'=>$pack);
$Items[27568]=array(
  'name'=>'Red Matter Axe',
  'icon'=>'Red_Matter_Axe.png',
  'pack'=>$pack);
$Items[27569]=array(
  'name'=>'Red Matter Shears',
  'icon'=>'Red_Matter_Shears.png',
  'pack'=>$pack);
$Items[27570]=array(
  'name'=>'Red Matter Hammer',
  'icon'=>'Red_Matter_Hammer.png',
  'pack'=>$pack);
$Items[27572]=array(
  'name'=>'Red Katar',
  'icon'=>'Red_Katar.png',
  'pack'=>$pack);
$Items[27573]=array(
  'name'=>'Red Morningstar',
  'icon'=>'Red_Morningstar.png',
  'pack'=>$pack);

// Dark Matter Armor
$Items[27550]=array(
  'name'=>'Dark Matter Helmet',
  'icon'=>'Dark_Matter_Helmet.png',
  'pack'=>$pack);
$Items[27549]=array(
  'name'=>'Dark Matter Armor',
  'icon'=>'Dark_Matter_Armor.png',
  'pack'=>$pack);
$Items[27551]=array(
  'name'=>'Dark Matter Greaves',
  'icon'=>'Dark_Matter_Greaves.png',
  'pack'=>$pack);
$Items[27552]=array(
  'name'=>'Dark Matter Boots',
  'icon'=>'Dark_Matter_Boots.png',
  'pack'=>$pack);

// Red Matter Armor
$Items[27573]=array(
  'name'=>'Red Matter Helmet',
  'icon'=>'Red_Matter_Helmet.png',
  'pack'=>$pack);
$Items[27573]=array(
  'name'=>'Red Matter Helmet',
  'icon'=>'Red_Matter_Helmet.png',
  'pack'=>$pack);
$Items[27573]=array(
  'name'=>'Red Matter Helmet',
  'icon'=>'Red_Matter_Helmet.png',
  'pack'=>$pack);
$Items[27573]=array(
  'name'=>'Red Matter Helmet',
  'icon'=>'Red_Matter_Helmet.png',
  'pack'=>$pack);

// Gem Armor
$Items[27580]=array(
  'name'=>'Abyss Helmet',
  'icon'=>'Abyss_Helmet.png',
  'pack'=>$pack);
$Items[27579]=array(
  'name'=>'Infernal Armor',
  'icon'=>'Infernal_Armor.png',
  'pack'=>$pack);
$Items[27581]=array(
  'name'=>'Gravity Greaves',
  'icon'=>'Gravity_Greaves.png',
  'pack'=>$pack);
$Items[27582]=array(
  'name'=>'Hurricane Boots',
  'icon'=>'Hurricane_Boots.png',
  'pack'=>$pack);

// Transmutation Tablet Progression
$Items[130]=array(
  'name'=>'Transmutation Tablet',
  'icon'=>'Transmutation_Tablet_0.png',
  'pack'=>$pack);
$Items[27592]=array(
  'name'=>'Transmutation Tablet',
  'icon'=>'Transmutation_Tablet_1.png',
  'pack'=>$pack);
$Items[27594]=array(
  'name'=>'Alchemical Tome',
  'icon'=>'Alchemical_Tome.png',
  'pack'=>$pack);

// Other Items
$Items[27530]=array(
  'name'=>'Evertide Amulet',
  'icon'=>'Evertide_Amulet.png',
  'pack'=>$pack);
$Items[27531]=array(
  'name'=>'Volcanite Amulet',
  'icon'=>'Volcanite_Amulet.png',
  'pack'=>$pack);
$Items[27553]=array(
  0 =>array(
    'name'=>'Gem Of Eternal Density',
    'icon'=>'Gem_Of_Eternal_Density_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Gem Of Eternal Density',
    'icon'=>'Gem_Of_Eternal_Density_1.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Gem',
    'icon'=>'Gem_Of_Eternal_Density_0.png',
    'pack'=>$pack),
);
$Items[27554]=array(
  'name'=>'Talisman Of Repair',
  'icon'=>'Talisman_Of_Repair.png',
  'pack'=>$pack);
$Items[27538]=array(
  0 =>array(
    'name'=>'Watch Of Flowing Time Off',
    'icon'=>'Watch_Of_Flowing_Time_Off.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Watch Of Flowing Time On',
    'icon'=>'Watch_Of_Flowing_Time_On.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
);
$Items[27583]=array(
  'name'=>'Mercurial Eye',
  'icon'=>'Mercurial_Eye.png',
  'pack'=>$pack);
$Items[27585]=array(
  0 =>array(
    'name'=>'Low Divining Rod',
    'icon'=>'Divining_Rod_Low.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Mid Divining Rod',
    'icon'=>'Divining_Rod_Mid.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'High Divining Rod',
    'icon'=>'Divining_Rod_High.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
);
$Items[27562]=array(
  0 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_0.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_1.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_2.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_3.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_4.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_5.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_6.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_7.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_8.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_9.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_10.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_11.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_12.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_13.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Alchemy Bag',
    'icon'=>'Alchemy_Bag_14.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Alchemy Bag',
    'icon'=>'Alchemy_Bag_0.png',
    'pack'=>$pack),
);
$Items[27594]=array(
  'name'=>'Dark Matter Pedestal',
  'icon'=>'Dark_Matter_Pedestal.png',
  'pack'=>$pack);

$Items[129]=array(
  'name'=>'Interdiction Torch',
  'icon'=>'Interdiction_Torch.png',
  'pack'=>$pack);
$Items[27542]=array(
  0 =>array(
    'name'=>'Low Covalence Dust',
    'icon'=>'Covalence_Dust_Low.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Medium Covalence Dust',
    'icon'=>'Covalence_Dust_Mid.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'High Covalence Dust',
    'icon'=>'Covalence_Dust_High.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Covalence Dust',
    'icon'=>'Covalence_Dust_High.png',
    'pack'=>$pack),
);
  
// Klein Star Progression
$Items[27557]=array(
  'name'=>'Klein Star',
  'icon'=>'Klein_Star_1.png',
  'pack'=>$pack);
$Items[27558]=array(
  'name'=>'Klein Star 2',
  'icon'=>'Klein_Star_2.png',
  'pack'=>$pack);
$Items[27559]=array(
  'name'=>'Klein Star 3',
  'icon'=>'Klein_Star_3.png',
  'pack'=>$pack);
$Items[27560]=array(
  'name'=>'Klein Star 4',
  'icon'=>'Klein_Star_4.png',
  'pack'=>$pack);
$Items[27561]=array(
  'name'=>'Klein Star Sphere',
  'icon'=>'Klein_Star_Sphere.png',
  'pack'=>$pack);
$Items[27591]=array(
  'name'=>'Klein Star Omega',
  'icon'=>'Klein_Star_Omega.png',
  'pack'=>$pack);

//Debug Item
$Items[30104]=array(
  'name'=>'Debug Item',
  'icon'=>'Debug_Item.png',
  'pack'=>$pack);

// Alchemical Blocks
$Items[128]=array(
  0 =>array(
    'name'=>'Alchemical Chest',
    'icon'=>'Alchemical_Chest.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Energy Condenser',
    'icon'=>'Energy_Condenser.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Alchemical Item',
    'icon'=>'Alchemical_Chest.png',
    'pack'=>$pack),
);
$Items[126]=array(
  0 =>array(
    'name'=>'Energy Collector MK1',
    'icon'=>'Energy_Collector_MK1.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Energy Collector MK2',
    'icon'=>'Energy_Collector_MK2.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Energy Collector MK3',
    'icon'=>'Energy_Collector_MK3.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Dark Matter Furnace',
    'icon'=>'Dark_Matter_Furnace.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Red Matter Furnace',
    'icon'=>'Red_Matter_Furnace.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Antimatter Relay MK1',
    'icon'=>'Antimatter_Relay_MK1.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Antimatter Relay MK2',
    'icon'=>'Antimatter_Relay_MK2.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Antimatter Relay MK3',
    'icon'=>'Antimatter_Relay_MK3.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Dark Matter Block',
    'icon'=>'Dark_Matter_Block.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Red Matter Block',
    'icon'=>'Red_Matter_Block.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Nova Catalyst',
    'icon'=>'Nova_Catalyst.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Nova Cataclysm',
    'icon'=>'Nova_Cataclysm.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Energy_Collector_MK1.png',
    'pack'=>$pack),
);

unset($Items);
?>