<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Immibis's Modular Forcefields - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'MFFS';

$Items[253]=array(
  0 =>array(
    'name'=>'Forcefield core',
    'icon'=>'Forcefield_core.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'MFFS Area Projector',
    'icon'=>'MFFS_area_projector.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Directional Forcefield Projector',
    'icon'=>'Directional_forcefield_projector.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'MFFS Deflector',
    'icon'=>'MFFS_deflector.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Tube Forcefield Projector',
    'icon'=>'Tube_forcefield_projector.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'MFFS Directional Extender',
    'icon'=>'MFFS_directional_extender.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Forcefield EU Injector',
    'icon'=>'Forcefield_EU_injector.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Reactor Containment Field Projector',
    'icon'=>'Reactor_containment_field_projector.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'MFFS Reactor Heat Control',
    'icon'=>'MFFS_reactor_heat_control.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'MFFS Reactor Heat Monitor Server',
    'icon'=>'MFFS_reactor_heat_monitor_server.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Forcefield Item',
    'icon'=>'MFFS_reactor_heat_monitor_server.png',
    'pack'=>$pack),
);
$Items[254]=array(
  0 =>array(
    'name'=>'MFFS Reactor Heat Monitor Client',
    'icon'=>'MFFS_reactor_heat_monitor_client.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Forcefield Underwater Upgrade',
    'icon'=>'Forcefield_underwater_upgrade.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Forcefield Dome Upgrade',
    'icon'=>'Forcefield_dome_upgrade.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Forcefield Block Cutter Upgrade',
    'icon'=>'Forcefield_block_cutter_upgrade.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Forcefield Core Storage Upgrade',
    'icon'=>'Forcefield_core_storage_upgrade.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Forcefield Core Range Upgrade',
    'icon'=>'Forcefield_core_range_upgrade.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Forcefield Zapper Upgrade',
    'icon'=>'Forcefield_zapper_upgrade.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Forcefield Camouflage Upgrade',
    'icon'=>'Forcefield_camouflage_upgrade.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'MFFS Reactor Connector',
    'icon'=>'MFFS_reactor_connector.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Forcefield Item',
    'icon'=>'MFFS_reactor_heat_monitor_client.png',
    'pack'=>$pack),
);
$Items[11366]=array(
  'name'=>'MFFS Remote Reactor Link',
  'icon'=>'MFFS_remote_reactor_link.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11367]=array(
  'name'=>'MFDevice <Debugger>',
  'icon'=>'MFDevice_Debugger.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11368]=array(
  'name'=>'MFDevice <ID-Tool>',
  'icon'=>'MFDevice_ID-Tool.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11370]=array(
  'name'=>'MFDevice <Wrench>',
  'icon'=>'MFDevice_Wrench.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11371]=array(
  'name'=>'Blank MFFS card',
  'icon'=>'Blank_MFFS_card.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11372]=array(
  'name'=>'MFFS Frequency Card',
  'icon'=>'MFFS_frequency_card.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11373]=array(
  'name'=>'MFFS ID Card',
  'icon'=>'MFFS_ID_card.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[11374]=array(
  'name'=>'MFFS Link Card',
  'icon'=>'MFFS_link_card.png',
  'stack'=>1,
  'pack'=>$pack);

unset($Items);
?>