<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Red Power - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'RedPower';

// wire
$Items[136]=array(
  256=>array(
    'name'=>'Red Alloy Wire',
    'icon'=>'Wire.png',
    'pack'=>$pack),
  512 =>array(
    'name'=>'White Insulated Wire',
    'icon'=>'Insulated_Wire_White.png',
    'pack'=>$pack),
  513 =>array(
    'name'=>'Orange Insulated Wire',
    'icon'=>'Insulated_Wire_Orange.png',
    'pack'=>$pack),
  514 =>array(
    'name'=>'Magenta Insulated Wire',
    'icon'=>'Insulated_Wire_Magenta.png',
    'pack'=>$pack),
  515 =>array(
    'name'=>'Light Blue Insulated Wire',
    'icon'=>'Insulated_Wire_Light_Blue.png',
    'pack'=>$pack),
  516 =>array(
    'name'=>'Yellow Insulated Wire',
    'icon'=>'Insulated_Wire_Yellow.png',
    'pack'=>$pack),
  517 =>array(
    'name'=>'Lime Insulated Wire',
    'icon'=>'Insulated_Wire_Lime.png',
    'pack'=>$pack),
  518 =>array(
    'name'=>'Pink Insulated Wire',
    'icon'=>'Insulated_Wire_Pink.png',
    'pack'=>$pack),
  519 =>array(
    'name'=>'Gray Insulated Wire',
    'icon'=>'Insulated_Wire_Gray.png',
    'pack'=>$pack),
  520 =>array(
    'name'=>'Light Gray Insulated Wire',
    'icon'=>'Insulated_Wire_Light_Gray.png',
    'pack'=>$pack),
  521 =>array(
    'name'=>'Cyan Insulated Wire',
    'icon'=>'Insulated_Wire_Cyan.png',
    'pack'=>$pack),
  522 =>array(
    'name'=>'Purple Insulated Wire',
    'icon'=>'Insulated_Wire_Purple.png',
    'pack'=>$pack),
  523 =>array(
    'name'=>'Blue Insulated Wire',
    'icon'=>'Insulated_Wire_Blue.png',
    'pack'=>$pack),
  524 =>array(
    'name'=>'Brown Insulated Wire',
    'icon'=>'Insulated_Wire_Brown.png',
    'pack'=>$pack),
  525 =>array(
    'name'=>'Green Insulated Wire',
    'icon'=>'Insulated_Wire_Green.png',
    'pack'=>$pack),
  526 =>array(
    'name'=>'Red Insulated Wire',
    'icon'=>'Insulated_Wire_Red.png',
    'pack'=>$pack),
  527 =>array(
    'name'=>'Black Insulated Wire',
    'icon'=>'Insulated_Wire_Black.png',
    'pack'=>$pack),
  768 =>array(
    'name'=>'Bundled Cable',
    'icon'=>'Bundled_Cable.png',
    'pack'=>$pack),
  769 =>array(
    'name'=>'White Bundled Cable',
    'icon'=>'Bundled_Cable_White.png',
    'pack'=>$pack),
  770 =>array(
    'name'=>'Orange Bundled Cable',
    'icon'=>'Bundled_Cable_Orange.png',
    'pack'=>$pack),
  771 =>array(
    'name'=>'Magenta Bundled Cable',
    'icon'=>'Bundled_Cable_Magenta.png',
    'pack'=>$pack),
  772 =>array(
    'name'=>'Light Blue Bundled Cable',
    'icon'=>'Bundled_Cable_Light_Blue.png',
    'pack'=>$pack),
  773 =>array(
    'name'=>'Yellow Bundled Cable',
    'icon'=>'Bundled_Cable_Yellow.png',
    'pack'=>$pack),
  774 =>array(
    'name'=>'Lime Bundled Cable',
    'icon'=>'Bundled_Cable_Lime.png',
    'pack'=>$pack),
  775 =>array(
    'name'=>'Pink Bundled Cable',
    'icon'=>'Bundled_Cable_Pink.png',
    'pack'=>$pack),
  776 =>array(
    'name'=>'Gray Bundled Cable',
    'icon'=>'Bundled_Cable_Gray.png',
    'pack'=>$pack),
  777 =>array(
    'name'=>'Light Gray Bundled Cable',
    'icon'=>'Bundled_Cable_Light_Gray.png',
    'pack'=>$pack),
  778 =>array(
    'name'=>'Cyan Bundled Cable',
    'icon'=>'Bundled_Cable_Cyan.png',
    'pack'=>$pack),
  779 =>array(
    'name'=>'Purple Bundled Cable',
    'icon'=>'Bundled_Cable_Purple.png',
    'pack'=>$pack),
  780 =>array(
    'name'=>'Blue Bundled Cable',
    'icon'=>'Bundled_Cable_Blue.png',
    'pack'=>$pack),
  781 =>array(
    'name'=>'Brown Bundled Cable',
    'icon'=>'Bundled_Cable_Brown.png',
    'pack'=>$pack),
  782 =>array(
    'name'=>'Green Bundled Cable',
    'icon'=>'Bundled_Cable_Green.png',
    'pack'=>$pack),
  783 =>array(
    'name'=>'Red Bundled Cable',
    'icon'=>'Bundled_Cable_Red.png',
    'pack'=>$pack),
  784 =>array(
    'name'=>'Black Bundled Cable',
    'icon'=>'Bundled_Cable_Black.png',
    'pack'=>$pack),
  1280=>array(
    'name'=>'Blue Alloy Wire',
    'icon'=>'Wire_Blue_Alloy.png',
    'pack'=>$pack),
  1792=>array(
    'name'=>'Fluid Pipe',
    'icon'=>'Tube_Fluid.png',
    'pack'=>$pack),
  2048=>array(
    'name'=>'Pneumatic Tube',
    'icon'=>'Tube_Pneumatic.png',
    'pack'=>$pack),
  2304=>array(
    'name'=>'Redstone Tube',
    'icon'=>'Tube_Redstone.png',
    'pack'=>$pack),
  2560=>array(
    'name'=>'Restriction Tube',
    'icon'=>'Tube_Restriction.png',
    'pack'=>$pack),
  2816=>array(
    'name'=>'Magtube',
    'icon'=>'Magtube.png',
    'pack'=>$pack),
  3072=>array(
    'name'=>'Ribbon Cable',
    'icon'=>'Ribbon_Cable.png',
    'pack'=>$pack),
  -1  =>array(
    'name'=>'Unknown Item',
    'icon'=>'Wire.png',
    'pack'=>$pack),
);
$Items[137]=array(
  0 =>array(
    'name'=>'Alloy Furnace',
    'icon'=>'Alloy_Furnace.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Blulectric Furnace',
    'icon'=>'Blulectric_Furnace.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Buffer',
    'icon'=>'Buffer.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Project Table',
    'icon'=>'Project_Table.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Blulectric Alloy Furnace',
    'icon'=>'Blulectric_Alloy_Furnace.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Alloy_Furnace.png',
    'pack'=>$pack),
);
// gates
$Items[138]=array(
  0 =>array(
    'name'=>'Timer',
    'icon'=>'Timer.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Sequencer',
    'icon'=>'Sequencer.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'State Cell',
    'icon'=>'State_Cell.png',
    'pack'=>$pack),
  256=>array(
    'name'=>'RS Latch',
    'icon'=>'RS_Latch.png',
    'pack'=>$pack),
  257=>array(
    'name'=>'NOR Gate',
    'icon'=>'NOR_Gate.png',
    'pack'=>$pack),
  258=>array(
    'name'=>'OR Gate',
    'icon'=>'OR_Gate.png',
    'pack'=>$pack),
  259=>array(
    'name'=>'NAND Gate',
    'icon'=>'NAND_Gate.png',
    'pack'=>$pack),
  260=>array(
    'name'=>'AND Gate',
    'icon'=>'AND_Gate.png',
    'pack'=>$pack),
  261=>array(
    'name'=>'XNOR Gate',
    'icon'=>'XNOR_Gate.png',
    'pack'=>$pack),
  262=>array(
    'name'=>'XOR Gate',
    'icon'=>'XOR_Gate.png',
    'pack'=>$pack),
  263=>array(
    'name'=>'Pulse Former',
    'icon'=>'Pulse_Former.png',
    'pack'=>$pack),
  264=>array(
    'name'=>'Toggle Latch',
    'icon'=>'Toggle_Latch.png',
    'pack'=>$pack),
  265=>array(
    'name'=>'NOT Gate',
    'icon'=>'NOT_Gate.png',
    'pack'=>$pack),
  266=>array(
    'name'=>'Buffer Gate',
    'icon'=>'Buffer_Gate.png',
    'pack'=>$pack),
  267=>array(
    'name'=>'Multiplexer',
    'icon'=>'Multiplexer.png',
    'pack'=>$pack),
  268=>array(
    'name'=>'Repeater',
    'icon'=>'Repeater.png',
    'pack'=>$pack),
  269=>array(
    'name'=>'Synchronizer',
    'icon'=>'Synchronizer.png',
    'pack'=>$pack),
  270=>array(
    'name'=>'Randomizer',
    'icon'=>'Randomizer.png',
    'pack'=>$pack),
  271=>array(
    'name'=>'Transparent Latch',
    'icon'=>'Transparent_Latch.png',
    'pack'=>$pack),
  272=>array(
    'name'=>'Light Sensor',
    'icon'=>'Light_Sensor.png',
    'pack'=>$pack),
  512=>array(
    'name'=>'Null Cell',
    'icon'=>'Null_Cell.png',
    'pack'=>$pack),
  513=>array(
    'name'=>'Invert Chell',
    'icon'=>'Invert_Cell.png',
    'pack'=>$pack),
  514=>array(
    'name'=>'Non-Invert Cell',
    'icon'=>'Non-Invert_Cell.png',
    'pack'=>$pack),
  768=>array(
    'name'=>'Counter',
    'icon'=>'Counter.png',
    'pack'=>$pack),
  1024=>array(
    'name'=>'Bus Transceiver',
    'icon'=>'Bus_Transceiver.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Gate',
    'icon'=>'Timer.png',
    'pack'=>$pack),
);
$Items[139]=array(
  0 =>array(
    'name'=>'Indigo Flower',
    'icon'=>'Indigo_Flower.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Rubber Sapling',
    'icon'=>'Rubber_Sapling.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Rubber_Sapling.png',
    'pack'=>$pack),
);
$Items[140]=array(
  0 =>array(
    'name'=>'Ruby Ore',
    'icon'=>'Ore_Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald Ore',
    'icon'=>'Ore_Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire Ore',
    'icon'=>'Ore_Sapphire.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Silver Ore',
    'icon'=>'Ore_Silver.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Tin Ore',
    'icon'=>'Ore_Tin.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Copper Ore',
    'icon'=>'Ore_Copper.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Tungsten Ore',
    'icon'=>'Ore_Tungsten.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Nikolite Ore',
    'icon'=>'Ore_Nikolite.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Ore_Ruby.png',
    'pack'=>$pack),
);
$Items[141]=array(
  'name'=>'Rubberwood Leaves',
  'icon'=>'Leaves_Rubberwood.png',
  'pack'=>$pack);
$Items[142]=array(
  0 =>array(
    'name'=>'Marble',
    'icon'=>'Marble.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Basalt',
    'icon'=>'Basalt.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Marble Brick',
    'icon'=>'Marble_Brick.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Basalt Cobblestone',
    'icon'=>'Basalt_Cobblestone.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Basalt Brick',
    'icon'=>'Basalt_Brick.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Marble.png',
    'pack'=>$pack),
);
$Items[143]=array(
  'name'=>'Rubberwood',
  'icon'=>'Rubberwood.png',
  'pack'=>$pack);
$Items[145]=array(
  0 =>array(
    'name'=>'Ruby Block',
    'icon'=>'Block_Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald Block',
    'icon'=>'Block_Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire Block',
    'icon'=>'Block_Sapphire.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Block_Ruby.png',
    'pack'=>$pack),
);
// lamps
$Items[147]=array(
  0 =>array(
    'name'=>'White Lamp',
    'icon'=>'Lamp_White.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Orange Lamp',
    'icon'=>'Lamp_Orange.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Magenta Lamp',
    'icon'=>'Lamp_Magenta.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Light Blue Lamp',
    'icon'=>'Lamp_Light_Blue.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Yellow Lamp',
    'icon'=>'Lamp_Yellow.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Lime Lamp',
    'icon'=>'Lamp_Lime.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Pink Lamp',
    'icon'=>'Lamp_Pink.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Gray Lamp',
    'icon'=>'Lamp_Gray.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Light Gray Lamp',
    'icon'=>'Lamp_Light_Gray.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Cyan Lamp',
    'icon'=>'Lamp_Cyan.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Purple Lamp',
    'icon'=>'Lamp_Purple.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Blue Lamp',
    'icon'=>'Lamp_Blue.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Brown Lamp',
    'icon'=>'Lamp_Brown.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Green Lamp',
    'icon'=>'Lamp_Green.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Red Lamp',
    'icon'=>'Lamp_Red.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Black Lamp',
    'icon'=>'Lamp_Black.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Lamp',
    'icon'=>'Lamp_White.png',
    'pack'=>$pack),
);
$Items[148]=array(
  'name'=>'IO Expander',
  'icon'=>'IO_Expander.png',
  'pack'=>$pack);
$Items[150]=array(
  0 =>array(
    'name'=>'Deployer',
    'icon'=>'Deployer.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Block Breaker',
    'icon'=>'Block_Breaker.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Transposer',
    'icon'=>'Transposer.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Filter',
    'icon'=>'Filter.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Item Detector',
    'icon'=>'Item_Detector.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Sorting Machine',
    'icon'=>'Sorting_Machine.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Battery Box',
    'icon'=>'Battery_Box.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Frame Motor',
    'icon'=>'Frame_Motor.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Retriever',
    'icon'=>'Retriever.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Regulator',
    'icon'=>'Regulator.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Thermopile',
    'icon'=>'Thermopile.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Igniter',
    'icon'=>'Igniter.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Assembler',
    'icon'=>'Assembler.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Ejector',
    'icon'=>'Ejector.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Relay',
    'icon'=>'Relay.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Deployer.png',
    'pack'=>$pack),
);
$Items[151]=array(
  0 =>array(
    'name'=>'Solar Panel',
    'icon'=>'Solar_Panel.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Pump',
    'icon'=>'Pump.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Accelerator',
    'icon'=>'Accelerator.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Grate',
    'icon'=>'Grate.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Solar_Panel.png',
    'pack'=>$pack),
);
$Items[152]=array(
  'name'=>'Support Frame',
  'icon'=>'Support_Frame.png',
  'pack'=>$pack);
// lumar
$Items[1256]=array(
  0 =>array(
    'name'=>'White Lumar',
    'icon'=>'Lumar_White.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Orange Lumar',
    'icon'=>'Lumar_Orange.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Magenta Lumar',
    'icon'=>'Lumar_Magenta.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Light Blue Lumar',
    'icon'=>'Lumar_Light_Blue.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Yellow Lumar',
    'icon'=>'Lumar_Yellow.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Lime Lumar',
    'icon'=>'Lumar_Lime.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Pink Lumar',
    'icon'=>'Lumar_Pink.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Gray Lumar',
    'icon'=>'Lumar_Gray.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Light Gray Lumar',
    'icon'=>'Lumar_Light_Gray.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Cyan Lumar',
    'icon'=>'Lumar_Cyan.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Purple Lumar',
    'icon'=>'Lumar_Purple.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Blue Lumar',
    'icon'=>'Lumar_Blue.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Brown Lumar',
    'icon'=>'Lumar_Brown.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Green Lumar',
    'icon'=>'Lumar_Green.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Red Lumar',
    'icon'=>'Lumar_Red.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Black Lumar',
    'icon'=>'Lumar_Black.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Lumar',
    'icon'=>'Lumar_White.png',
    'pack'=>$pack),
);
  -1=>array(
    'name'=>'Unknown Lumar',
    'icon'=>'WhiteGlow.png',
    'pack'=>$pack),
);
$Items[1257]=array(
  0 =>array(
    'name'=>'Ruby',
    'icon'=>'Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald',
    'icon'=>'Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire',
    'icon'=>'Sapphire.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Silver Ingot',
    'icon'=>'Ingot_Silver.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Tin Ingot',
    'icon'=>'Ingot_Tin.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Copper Ingot',
    'icon'=>'Ingot_Copper.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Nikolite',
    'icon'=>'Nikolite.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Ruby.png',
    'pack'=>$pack),
);
$Items[1258]=array(
  0 =>array(
    'name'=>'Red Alloy Ingot',
    'icon'=>'Ingot_Red_Alloy.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Blue Alloy Ingot',
    'icon'=>'Ingot_Blue_Alloy.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Brass Ingot',
    'icon'=>'Ingot_Brass.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Silicon Boule',
    'icon'=>'Silicon_Boule.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Silicon Wafer',
    'icon'=>'Wafer_Silicon.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Blue Doped Wafer',
    'icon'=>'Wafer_Blue-Doped.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Red Doped Wafer',
    'icon'=>'Wafer_Red-Doped.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Tinplate',
    'icon'=>'Tinplate.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Fine Copper Wire',
    'icon'=>'Fine_Copper_Wire.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Fine Iron Wire',
    'icon'=>'Fine_Iron_Wire.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Copper Coil',
    'icon'=>'Copper_Coil.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Blulectric Motor',
    'icon'=>'Blulectric_Motor.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Ingot_Red_Alloy.png',
    'pack'=>$pack),
);


unset($Items);
?>