<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Red Power - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'RedPower';

$Items[133]=array(
  0 =>array(
    'name'=>'Backplane',
    'icon'=>'Backplane.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'8K RAM Module',
    'icon'=>'8K_RAM_Module.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Backplane.png',
    'pack'=>$pack),
);
$Items[134]=array(
  0 =>array(
    'name'=>'Monitor',
    'icon'=>'Monitor.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Central Processing Unit',
    'icon'=>'Central_Processing_Unit.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Disk Drive',
    'icon'=>'Disk_Drive.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Monitor.png',
    'pack'=>$pack),
);
// wire
$Items[136]=array(
  256 =>array(
    'name'=>'Red Alloy Wire',
    'icon'=>'Wire_Red_Alloy.png',
    'pack'=>$pack),
  512 =>array(
    'name'=>'White Insulated Wire',
    'icon'=>'Insulated_Wire_White.png',
    'pack'=>$pack),
  513 =>array(
    'name'=>'Orange Insulated Wire',
    'icon'=>'Insulated_Wire_Orange.png',
    'pack'=>$pack),
  514 =>array(
    'name'=>'Magenta Insulated Wire',
    'icon'=>'Insulated_Wire_Magenta.png',
    'pack'=>$pack),
  515 =>array(
    'name'=>'Light Blue Insulated Wire',
    'icon'=>'Insulated_Wire_Light_Blue.png',
    'pack'=>$pack),
  516 =>array(
    'name'=>'Yellow Insulated Wire',
    'icon'=>'Insulated_Wire_Yellow.png',
    'pack'=>$pack),
  517 =>array(
    'name'=>'Lime Insulated Wire',
    'icon'=>'Insulated_Wire_Lime.png',
    'pack'=>$pack),
  518 =>array(
    'name'=>'Pink Insulated Wire',
    'icon'=>'Insulated_Wire_Pink.png',
    'pack'=>$pack),
  519 =>array(
    'name'=>'Gray Insulated Wire',
    'icon'=>'Insulated_Wire_Gray.png',
    'pack'=>$pack),
  520 =>array(
    'name'=>'Light Gray Insulated Wire',
    'icon'=>'Insulated_Wire_Light_Gray.png',
    'pack'=>$pack),
  521 =>array(
    'name'=>'Cyan Insulated Wire',
    'icon'=>'Insulated_Wire_Cyan.png',
    'pack'=>$pack),
  522 =>array(
    'name'=>'Purple Insulated Wire',
    'icon'=>'Insulated_Wire_Purple.png',
    'pack'=>$pack),
  523 =>array(
    'name'=>'Blue Insulated Wire',
    'icon'=>'Insulated_Wire_Blue.png',
    'pack'=>$pack),
  524 =>array(
    'name'=>'Brown Insulated Wire',
    'icon'=>'Insulated_Wire_Brown.png',
    'pack'=>$pack),
  525 =>array(
    'name'=>'Green Insulated Wire',
    'icon'=>'Insulated_Wire_Green.png',
    'pack'=>$pack),
  526 =>array(
    'name'=>'Red Insulated Wire',
    'icon'=>'Insulated_Wire_Red.png',
    'pack'=>$pack),
  527 =>array(
    'name'=>'Black Insulated Wire',
    'icon'=>'Insulated_Wire_Black.png',
    'pack'=>$pack),
  768 =>array(
    'name'=>'Bundled Cable',
    'icon'=>'Bundled_Cable.png',
    'pack'=>$pack),
  769 =>array(
    'name'=>'White Bundled Cable',
    'icon'=>'Bundled_Cable_White.png',
    'pack'=>$pack),
  770 =>array(
    'name'=>'Orange Bundled Cable',
    'icon'=>'Bundled_Cable_Orange.png',
    'pack'=>$pack),
  771 =>array(
    'name'=>'Magenta Bundled Cable',
    'icon'=>'Bundled_Cable_Magenta.png',
    'pack'=>$pack),
  772 =>array(
    'name'=>'Light Blue Bundled Cable',
    'icon'=>'Bundled_Cable_Light_Blue.png',
    'pack'=>$pack),
  773 =>array(
    'name'=>'Yellow Bundled Cable',
    'icon'=>'Bundled_Cable_Yellow.png',
    'pack'=>$pack),
  774 =>array(
    'name'=>'Lime Bundled Cable',
    'icon'=>'Bundled_Cable_Lime.png',
    'pack'=>$pack),
  775 =>array(
    'name'=>'Pink Bundled Cable',
    'icon'=>'Bundled_Cable_Pink.png',
    'pack'=>$pack),
  776 =>array(
    'name'=>'Gray Bundled Cable',
    'icon'=>'Bundled_Cable_Gray.png',
    'pack'=>$pack),
  777 =>array(
    'name'=>'Light Gray Bundled Cable',
    'icon'=>'Bundled_Cable_Light_Gray.png',
    'pack'=>$pack),
  778 =>array(
    'name'=>'Cyan Bundled Cable',
    'icon'=>'Bundled_Cable_Cyan.png',
    'pack'=>$pack),
  779 =>array(
    'name'=>'Purple Bundled Cable',
    'icon'=>'Bundled_Cable_Purple.png',
    'pack'=>$pack),
  780 =>array(
    'name'=>'Blue Bundled Cable',
    'icon'=>'Bundled_Cable_Blue.png',
    'pack'=>$pack),
  781 =>array(
    'name'=>'Brown Bundled Cable',
    'icon'=>'Bundled_Cable_Brown.png',
    'pack'=>$pack),
  782 =>array(
    'name'=>'Green Bundled Cable',
    'icon'=>'Bundled_Cable_Green.png',
    'pack'=>$pack),
  783 =>array(
    'name'=>'Red Bundled Cable',
    'icon'=>'Bundled_Cable_Red.png',
    'pack'=>$pack),
  784 =>array(
    'name'=>'Black Bundled Cable',
    'icon'=>'Bundled_Cable_Black.png',
    'pack'=>$pack),
  1280=>array(
    'name'=>'Blue Alloy Wire',
    'icon'=>'Wire_Blue_Alloy.png',
    'pack'=>$pack),
  1792=>array(
    'name'=>'Fluid Pipe',
    'icon'=>'Tube_Fluid.png',
    'pack'=>$pack),
  2048=>array(
    'name'=>'Pneumatic Tube',
    'icon'=>'Tube_Pneumatic.png',
    'pack'=>$pack),
  2304=>array(
    'name'=>'Redstone Tube',
    'icon'=>'Tube_Redstone.png',
    'pack'=>$pack),
  2560=>array(
    'name'=>'Restriction Tube',
    'icon'=>'Tube_Restriction.png',
    'pack'=>$pack),
  2816=>array(
    'name'=>'Magtube',
    'icon'=>'Magtube.png',
    'pack'=>$pack),
  3072=>array(
    'name'=>'Ribbon Cable',
    'icon'=>'Ribbon_Cable.png',
    'pack'=>$pack),
  -1  =>array(
    'name'=>'Unknown Item',
    'icon'=>'Wire_Red_Alloy.png',
    'pack'=>$pack),
);
$Items[137]=array(
  0 =>array(
    'name'=>'Alloy Furnace',
    'icon'=>'Alloy_Furnace.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Blulectric Furnace',
    'icon'=>'Blulectric_Furnace.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Buffer',
    'icon'=>'Buffer.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Project Table',
    'icon'=>'Project_Table.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Blulectric Alloy Furnace',
    'icon'=>'Blulectric_Alloy_Furnace.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Alloy_Furnace.png',
    'pack'=>$pack),
);
// gates
$Items[138]=array(
  0 =>array(
    'name'=>'Timer',
    'icon'=>'Timer.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Sequencer',
    'icon'=>'Sequencer.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'State Cell',
    'icon'=>'Cell_State.png',
    'pack'=>$pack),
  256=>array(
    'name'=>'RS Latch',
    'icon'=>'Latch_RS.png',
    'pack'=>$pack),
  257=>array(
    'name'=>'NOR Gate',
    'icon'=>'Gate_NOR.png',
    'pack'=>$pack),
  258=>array(
    'name'=>'OR Gate',
    'icon'=>'Gate_OR.png',
    'pack'=>$pack),
  259=>array(
    'name'=>'NAND Gate',
    'icon'=>'Gate_NAND.png',
    'pack'=>$pack),
  260=>array(
    'name'=>'AND Gate',
    'icon'=>'Gate_AND.png',
    'pack'=>$pack),
  261=>array(
    'name'=>'XNOR Gate',
    'icon'=>'Gate_XNOR.png',
    'pack'=>$pack),
  262=>array(
    'name'=>'XOR Gate',
    'icon'=>'Gate_XOR.png',
    'pack'=>$pack),
  263=>array(
    'name'=>'Pulse Former',
    'icon'=>'Pulse_Former.png',
    'pack'=>$pack),
  264=>array(
    'name'=>'Toggle Latch',
    'icon'=>'Latch_Toggle.png',
    'pack'=>$pack),
  265=>array(
    'name'=>'NOT Gate',
    'icon'=>'Gate_NOT.png',
    'pack'=>$pack),
  266=>array(
    'name'=>'Buffer Gate',
    'icon'=>'Gate_Buffer.png',
    'pack'=>$pack),
  267=>array(
    'name'=>'Multiplexer',
    'icon'=>'Multiplexer.png',
    'pack'=>$pack),
  268=>array(
    'name'=>'Repeater',
    'icon'=>'Repeater.png',
    'pack'=>$pack),
  269=>array(
    'name'=>'Synchronizer',
    'icon'=>'Synchronizer.png',
    'pack'=>$pack),
  270=>array(
    'name'=>'Randomizer',
    'icon'=>'Randomizer.png',
    'pack'=>$pack),
  271=>array(
    'name'=>'Transparent Latch',
    'icon'=>'Latch_Transparent.png',
    'pack'=>$pack),
  272=>array(
    'name'=>'Light Sensor',
    'icon'=>'Light_Sensor.png',
    'pack'=>$pack),
  512=>array(
    'name'=>'Null Cell',
    'icon'=>'Cell_Null.png',
    'pack'=>$pack),
  513=>array(
    'name'=>'Invert Cell',
    'icon'=>'Cell_Invert.png',
    'pack'=>$pack),
  514=>array(
    'name'=>'Non-Invert Cell',
    'icon'=>'Cell_Non-Invert.png',
    'pack'=>$pack),
  768=>array(
    'name'=>'Counter',
    'icon'=>'Counter.png',
    'pack'=>$pack),
  1024=>array(
    'name'=>'Bus Transceiver',
    'icon'=>'Bus_Transceiver.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Gate',
    'icon'=>'Timer.png',
    'pack'=>$pack),
);
$Items[139]=array(
  0 =>array(
    'name'=>'Indigo Flower',
    'icon'=>'Indigo_Flower.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Rubber Sapling',
    'icon'=>'Rubber_Sapling.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Rubber_Sapling.png',
    'pack'=>$pack),
);
$Items[140]=array(
  0 =>array(
    'name'=>'Ruby Ore',
    'icon'=>'Ore_Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald Ore',
    'icon'=>'Ore_Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire Ore',
    'icon'=>'Ore_Sapphire.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Silver Ore',
    'icon'=>'Ore_Silver.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Tin Ore',
    'icon'=>'Ore_Tin.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Copper Ore',
    'icon'=>'Ore_Copper.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Tungsten Ore',
    'icon'=>'Ore_Tungsten.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Nikolite Ore',
    'icon'=>'Ore_Nikolite.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Ore_Ruby.png',
    'pack'=>$pack),
);
$Items[141]=array(
  'name'=>'Rubberwood Leaves',
  'icon'=>'Leaves_Rubberwood.png',
  'pack'=>$pack);
$Items[142]=array(
  0 =>array(
    'name'=>'Marble',
    'icon'=>'Marble.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Basalt',
    'icon'=>'Basalt.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Marble Brick',
    'icon'=>'Marble_Brick.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Basalt Cobblestone',
    'icon'=>'Basalt_Cobblestone.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Basalt Brick',
    'icon'=>'Basalt_Brick.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Marble.png',
    'pack'=>$pack),
);
$Items[143]=array(
  'name'=>'Rubberwood',
  'icon'=>'Rubberwood.png',
  'pack'=>$pack);
$Items[145]=array(
  0 =>array(
    'name'=>'Ruby Block',
    'icon'=>'Block_Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald Block',
    'icon'=>'Block_Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire Block',
    'icon'=>'Block_Sapphire.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Block_Ruby.png',
    'pack'=>$pack),
);
// lamps
$Items[147]=array(
  0 =>array(
    'name'=>'White Lamp',
    'icon'=>'Lamp_White.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Orange Lamp',
    'icon'=>'Lamp_Orange.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Magenta Lamp',
    'icon'=>'Lamp_Magenta.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Light Blue Lamp',
    'icon'=>'Lamp_Light_Blue.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Yellow Lamp',
    'icon'=>'Lamp_Yellow.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Lime Lamp',
    'icon'=>'Lamp_Lime.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Pink Lamp',
    'icon'=>'Lamp_Pink.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Gray Lamp',
    'icon'=>'Lamp_Gray.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Light Gray Lamp',
    'icon'=>'Lamp_Light_Gray.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Cyan Lamp',
    'icon'=>'Lamp_Cyan.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Purple Lamp',
    'icon'=>'Lamp_Purple.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Blue Lamp',
    'icon'=>'Lamp_Blue.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Brown Lamp',
    'icon'=>'Lamp_Brown.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Green Lamp',
    'icon'=>'Lamp_Green.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Red Lamp',
    'icon'=>'Lamp_Red.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Black Lamp',
    'icon'=>'Lamp_Black.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Lamp',
    'icon'=>'Lamp_White.png',
    'pack'=>$pack),
);
$Items[148]=array(
  'name'=>'IO Expander',
  'icon'=>'IO_Expander.png',
  'pack'=>$pack);
$Items[150]=array(
  0 =>array(
    'name'=>'Deployer',
    'icon'=>'Deployer.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Block Breaker',
    'icon'=>'Block_Breaker.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Transposer',
    'icon'=>'Transposer.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Filter',
    'icon'=>'Filter.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Item Detector',
    'icon'=>'Item_Detector.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Sorting Machine',
    'icon'=>'Sorting_Machine.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Battery Box',
    'icon'=>'Battery_Box.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Frame Motor',
    'icon'=>'Frame_Motor.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Retriever',
    'icon'=>'Retriever.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Regulator',
    'icon'=>'Regulator.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Thermopile',
    'icon'=>'Thermopile.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Igniter',
    'icon'=>'Igniter.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Assembler',
    'icon'=>'Assembler.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Ejector',
    'icon'=>'Ejector.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Relay',
    'icon'=>'Relay.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Deployer.png',
    'pack'=>$pack),
);
$Items[151]=array(
  0 =>array(
    'name'=>'Solar Panel',
    'icon'=>'Solar_Panel.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Pump',
    'icon'=>'Pump.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Accelerator',
    'icon'=>'Accelerator.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Grate',
    'icon'=>'Grate.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Solar_Panel.png',
    'pack'=>$pack),
);
$Items[152]=array(
  'name'=>'Support Frame',
  'icon'=>'Support_Frame.png',
  'pack'=>$pack);
// lumar
$Items[1256]=array(
  0 =>array(
    'name'=>'White Lumar',
    'icon'=>'Lumar_White.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Orange Lumar',
    'icon'=>'Lumar_Orange.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Magenta Lumar',
    'icon'=>'Lumar_Magenta.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Light Blue Lumar',
    'icon'=>'Lumar_Light_Blue.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Yellow Lumar',
    'icon'=>'Lumar_Yellow.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Lime Lumar',
    'icon'=>'Lumar_Lime.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Pink Lumar',
    'icon'=>'Lumar_Pink.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Gray Lumar',
    'icon'=>'Lumar_Gray.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Light Gray Lumar',
    'icon'=>'Lumar_Light_Gray.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Cyan Lumar',
    'icon'=>'Lumar_Cyan.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Purple Lumar',
    'icon'=>'Lumar_Purple.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Blue Lumar',
    'icon'=>'Lumar_Blue.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Brown Lumar',
    'icon'=>'Lumar_Brown.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Green Lumar',
    'icon'=>'Lumar_Green.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Red Lumar',
    'icon'=>'Lumar_Red.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Black Lumar',
    'icon'=>'Lumar_Black.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Lumar',
    'icon'=>'Lumar_White.png',
    'pack'=>$pack),
);
$Items[1257]=array(
  0 =>array(
    'name'=>'Ruby',
    'icon'=>'Ruby.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Emerald',
    'icon'=>'Emerald.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Sapphire',
    'icon'=>'Sapphire.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Silver Ingot',
    'icon'=>'Ingot_Silver.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Tin Ingot',
    'icon'=>'Ingot_Tin.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Copper Ingot',
    'icon'=>'Ingot_Copper.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Nikolite',
    'icon'=>'Nikolite.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Ruby.png',
    'pack'=>$pack),
);
$Items[1259]=array(
  'name' =>'Indigo Dye',
  'icon' =>'Indigo_Dye.png',
  'pack'=>$pack);
$Items[1260]=array(
  'type' =>'tool',
  'name' =>'Iron Handsaw',
  'title'=>'Iron Handsaw %damaged%',
  'icon' =>'Handsaw_Iron.png',
  'damage'=>321,
  'stack'=>1,
  'pack'=>$pack);
$Items[1261]=array(
  'type' =>'tool',
  'name' =>'Diamond Handsaw',
  'title'=>'Diamond Handsaw %damaged%',
  'icon' =>'Handsaw_Diamond.png',
  'damage'=>1281,
  'stack'=>1,
  'pack'=>$pack);
$Items[1262]=array(
  'type' =>'tool',
  'name' =>'Screwdriver',
  'title'=>'Screwdriver %damaged%',
  'icon' =>'Screwdriver.png',
  'damage'=>201,
  'stack'=>1,
  'pack'=>$pack);
$Items[1263]=array(
  0 =>array(
    'name'=>'Stone Wafer',
    'icon'=>'Stone_Wafer.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Stone Wire',
    'icon'=>'Stone_Wire.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Stone Anode',
    'icon'=>'Stone_Anode.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Stone Cathode',
    'icon'=>'Stone_Cathode.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Stone Pointer',
    'icon'=>'Stone_Pointer.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Stone Redwire',
    'icon'=>'Stone_Redwire.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Plate Assembly',
    'icon'=>'Plate_Assembly.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Silicon Chip',
    'icon'=>'Silicon_Chip.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Tainted Silicon Chip',
    'icon'=>'Silicon_Chip_Tainted.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Stone Bundle',
    'icon'=>'Stone_Bundle.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Stone_Wafer.png',
    'pack'=>$pack),
);
$Items[1264]=array(
  'type' =>'tool',
  'name' =>'Ruby Handsaw',
  'title'=>'Ruby Handsaw %damaged%',
  'icon' =>'Handsaw_Ruby.png',
  'damage'=>641,
  'stack'=>1,
  'pack'=>$pack);
$Items[1265]=array(
  'type' =>'tool',
  'name' =>'Emerald Handsaw',
  'title'=>'Emerald Handsaw %damaged%',
  'icon' =>'Handsaw_Emerald.png',
  'damage'=>641,
  'stack'=>1,
  'pack'=>$pack);
$Items[1266]=array(
  'type' =>'tool',
  'name' =>'Sapphire Handsaw',
  'title'=>'Sapphire Handsaw %damaged%',
  'icon' =>'Handsaw_Sapphire.png',
  'damage'=>641,
  'stack'=>1,
  'pack'=>$pack);
$Items[1267]=array(
  'type' =>'tool',
  'name' =>'Wood Sickle',
  'title'=>'Wood Sickle %damaged%',
  'icon' =>'Sickle_Wood.png',
  'damage'=>60,
  'stack'=>1,
  'pack'=>$pack);
$Items[1268]=array(
  'type' =>'tool',
  'name' =>'Stone Sickle',
  'title'=>'Stone Sickle %damaged%',
  'icon' =>'Sickle_Stone.png',
  'damage'=>132,
  'stack'=>1,
  'pack'=>$pack);
$Items[1269]=array(
  'type' =>'tool',
  'name' =>'Iron Sickle',
  'title'=>'Iron Sickle %damaged%',
  'icon' =>'Sickle_Iron.png',
  'damage'=>251,
  'stack'=>1,
  'pack'=>$pack);
$Items[1270]=array(
  'type' =>'tool',
  'name' =>'Diamond Sickle',
  'title'=>'Diamond Sickle %damaged%',
  'icon' =>'Sickle_Diamond.png',
  'damage'=>1562,
  'stack'=>1,
  'pack'=>$pack);
$Items[1271]=array(
  'type' =>'tool',
  'name' =>'Gold Sickle',
  'title'=>'Gold Sickle %damaged%',
  'icon' =>'Sickle_Gold.png',
  'damage'=>33,
  'stack'=>1,
  'pack'=>$pack);
$Items[1272]=array(
  'type' =>'tool',
  'name' =>'Ruby Sickle',
  'title'=>'Ruby Sickle %damaged%',
  'icon' =>'Sickle_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1273]=array(
  'type' =>'tool',
  'name' =>'Emerald Sickle',
  'title'=>'Emerald Sickle %damaged%',
  'icon' =>'Sickle_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1274]=array(
  'type' =>'tool',
  'name' =>'Sapphire Sickle',
  'title'=>'Sapphire Sickle %damaged%',
  'icon' =>'Sickle_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1275]=array(
  'type' =>'tool',
  'name' =>'Ruby Sword',
  'title'=>'Ruby Sword %damaged%',
  'icon' =>'Sword_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1276]=array(
  'type' =>'tool',
  'name' =>'Emerald Sword',
  'title'=>'Emerald Sword %damaged%',
  'icon' =>'Sword_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1277]=array(
  'type' =>'tool',
  'name' =>'Sapphire Sword',
  'title'=>'Sapphire Sword %damaged%',
  'icon' =>'Sword_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1278]=array(
  'type' =>'tool',
  'name' =>'Ruby Shovel',
  'title'=>'Ruby Shovel %damaged%',
  'icon' =>'Shovel_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1279]=array(
  'type' =>'tool',
  'name' =>'Emerald Shovel',
  'title'=>'Emerald Shovel %damaged%',
  'icon' =>'Shovel_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1280]=array(
  'type' =>'tool',
  'name' =>'Sapphire Shovel',
  'title'=>'Sapphire Shovel %damaged%',
  'icon' =>'Shovel_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1281]=array(
  'type' =>'tool',
  'name' =>'Ruby Pickaxe',
  'title'=>'Ruby Pickaxe %damaged%',
  'icon' =>'Pickaxe_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1282]=array(
  'type' =>'tool',
  'name' =>'Emerald Pickaxe',
  'title'=>'Emerald Pickaxe %damaged%',
  'icon' =>'Pickaxe_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1283]=array(
  'type' =>'tool',
  'name' =>'Sapphire Pickaxe',
  'title'=>'Sapphire Pickaxe %damaged%',
  'icon' =>'Pickaxe_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1284]=array(
  'type' =>'tool',
  'name' =>'Ruby Axe',
  'title'=>'Ruby Axe %damaged%',
  'icon' =>'Axe_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1285]=array(
  'type' =>'tool',
  'name' =>'Emerald Axe',
  'title'=>'Emerald Axe %damaged%',
  'icon' =>'Axe_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1286]=array(
  'type' =>'tool',
  'name' =>'Sapphire Axe',
  'title'=>'Sapphire Axe %damaged%',
  'icon' =>'Axe_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1287]=array(
  'type' =>'tool',
  'name' =>'Ruby Hoe',
  'title'=>'Ruby Hoe %damaged%',
  'icon' =>'Hoe_Ruby.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1288]=array(
  'type' =>'tool',
  'name' =>'Emerald Hoe',
  'title'=>'Emerald Hoe %damaged%',
  'icon' =>'Hoe_Emerald.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1289]=array(
  'type' =>'tool',
  'name' =>'Sapphire Hoe',
  'title'=>'Sapphire Hoe %damaged%',
  'icon' =>'Hoe_Sapphire.png',
  'damage'=>501,
  'stack'=>1,
  'pack'=>$pack);
$Items[1290]=array(
  'name'=>'Flax Seeds',
  'icon'=>'Flax_Seeds.png',
  'pack'=>$pack);
// paint cans
$Items[1291]=array(
  'name'=>'Paint Can',
  'icon'=>'Paint_Can.png',
  'pack'=>$pack);
$Items[1292]=array(
  'type' =>'tool',
  'name' =>'White Paint',
  'title'=>'White Paint %painted%',
  'icon' =>'Paint_Can_White.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1293]=array(
  'type' =>'tool',
  'name' =>'Orange Paint',
  'title'=>'Orange Paint %painted%',
  'icon' =>'Paint_Can_Orange.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1294]=array(
  'type' =>'tool',
  'name' =>'Magenta Paint',
  'title'=>'Magenta Paint %painted%',
  'icon' =>'Paint_Can_Magenta.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1295]=array(
  'type' =>'tool',
  'name' =>'Light Blue Paint',
  'title'=>'Light Blue Paint %painted%',
  'icon' =>'Paint_Can_Light_Blue.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1296]=array(
  'type' =>'tool',
  'name' =>'Yellow Paint',
  'title'=>'Yellow Paint %painted%',
  'icon' =>'Paint_Can_Yellow.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1297]=array(
  'type' =>'tool',
  'name' =>'Lime Paint',
  'title'=>'Lime Paint %painted%',
  'icon' =>'Paint_Can_Lime.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1298]=array(
  'type' =>'tool',
  'name' =>'Pink Paint',
  'title'=>'Pink Paint %painted%',
  'icon' =>'Paint_Can_Pink.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1299]=array(
  'type' =>'tool',
  'name' =>'Gray Paint',
  'title'=>'Gray Paint %painted%',
  'icon' =>'Paint_Can_Gray.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1300]=array(
  'type' =>'tool',
  'name' =>'Light Gray Paint',
  'title'=>'Light Gray Paint %painted%',
  'icon' =>'Paint_Can_Light_Gray.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1301]=array(
  'type' =>'tool',
  'name' =>'Cyan Paint',
  'title'=>'Cyan Paint %painted%',
  'icon' =>'Paint_Can_Cyan.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1302]=array(
  'type' =>'tool',
  'name' =>'Purple Paint',
  'title'=>'Purple Paint %painted%',
  'icon' =>'Paint_Can_Purple.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1303]=array(
  'type' =>'tool',
  'name' =>'Blue Paint',
  'title'=>'Blue Paint %painted%',
  'icon' =>'Paint_Can_Blue.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1304]=array(
  'type' =>'tool',
  'name' =>'Brown Paint',
  'title'=>'Brown Paint %painted%',
  'icon' =>'Paint_Can_Brown.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1305]=array(
  'type' =>'tool',
  'name' =>'Green Paint',
  'title'=>'Green Paint %painted%',
  'icon' =>'Paint_Can_Green.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1306]=array(
  'type' =>'tool',
  'name' =>'Red Paint',
  'title'=>'Red Paint %painted%',
  'icon' =>'Paint_Can_Red.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1307]=array(
  'type' =>'tool',
  'name' =>'Black Paint',
  'title'=>'Black Paint %painted%',
  'icon' =>'Paint_Can_Black.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
// paint brushes
$Items[1308]=array(
  'name'=>'Paint Brush',
  'icon'=>'Paint_Brush.png',
  'pack'=>$pack);
$Items[1309]=array(
  'type' =>'tool',
  'name' =>'White Paint Brush',
  'title'=>'White Paint Brush %painted%',
  'icon' =>'Paint_Brush_White.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1310]=array(
  'type' =>'tool',
  'name' =>'Orange Paint Brush',
  'title'=>'Orange Paint Brush %painted%',
  'icon' =>'Paint_Brush_Orange.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1311]=array(
  'type' =>'tool',
  'name' =>'Magenta Paint Brush',
  'title'=>'Magenta Paint Brush %painted%',
  'icon' =>'Paint_Brush_Magenta.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1312]=array(
  'type' =>'tool',
  'name' =>'Light Blue Paint Brush',
  'title'=>'Light Blue Paint Brush %painted%',
  'icon' =>'Paint_Brush_Light_Blue.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1313]=array(
  'type' =>'tool',
  'name' =>'Yellow Paint Brush',
  'title'=>'Yellow Paint Brush %painted%',
  'icon' =>'Paint_Brush_Yellow.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1314]=array(
  'type' =>'tool',
  'name' =>'Lime Paint Brush',
  'title'=>'Lime Paint Brush %painted%',
  'icon' =>'Paint_Brush_Lime.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1315]=array(
  'type' =>'tool',
  'name' =>'Pink Paint Brush',
  'title'=>'Pink Paint Brush %painted%',
  'icon' =>'Paint_Brush_Pink.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1316]=array(
  'type' =>'tool',
  'name' =>'Gray Paint Brush',
  'title'=>'Gray Paint Brush %painted%',
  'icon' =>'Paint_Brush_Gray.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1317]=array(
  'type' =>'tool',
  'name' =>'Light Gray Paint Brush',
  'title'=>'Light Gray Paint Brush %painted%',
  'icon' =>'Paint_Brush_Light_Gray.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1318]=array(
  'type' =>'tool',
  'name' =>'Cyan Paint Brush',
  'title'=>'Cyan Paint Brush %painted%',
  'icon' =>'Paint_Brush_Cyan.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1319]=array(
  'type' =>'tool',
  'name' =>'Purple Paint Brush',
  'title'=>'Purple Paint Brush %painted%',
  'icon' =>'Paint_Brush_Purple.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1320]=array(
  'type' =>'tool',
  'name' =>'Blue Paint Brush',
  'title'=>'Blue Paint Brush %painted%',
  'icon' =>'Paint_Brush_Blue.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1321]=array(
  'type' =>'tool',
  'name' =>'Brown Paint Brush',
  'title'=>'Brown Paint Brush %painted%',
  'icon' =>'Paint_Brush_Brown.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1322]=array(
  'type' =>'tool',
  'name' =>'Green Paint Brush',
  'title'=>'Green Paint Brush %painted%',
  'icon' =>'Paint_Brush_Green.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1323]=array(
  'type' =>'tool',
  'name' =>'Red Paint Brush',
  'title'=>'Red Paint Brush %painted%',
  'icon' =>'Paint_Brush_Red.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1324]=array(
  'type' =>'tool',
  'name' =>'Black Paint Brush',
  'title'=>'Black Paint Brush %painted%',
  'icon' =>'Paint_Brush_Black.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[1325]=array(
  'name' =>'Voltmeter',
  'icon' =>'Voltmeter.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[1326]=array(
  'name' =>'BT Battery',
  'icon' =>'BT_Battery.png',
  'pack'=>$pack);
$Items[1327]=array(
  'type' =>'tool',
  'name' =>'Sonic Screwdriver',
  'title'=>'Sonic Screwdriver %charged%',
  'icon' =>'Screwdriver_Sonic.png',
  'damage'=>400,
  'stack'=>1,
  'pack'=>$pack);
$Items[1328]=array(
  'type' =>'tool',
  'name' =>'BT Battery',
  'title'=>'BT Battery %charged%',
  'icon' =>'BT_Battery.png',
  'damage'=>1475,
  'stack'=>1,
  'pack'=>$pack);
$Items[1329]=array(
  'type' =>'tool',
  'name' =>'Athame',
  'title'=>'Athame %damaged%',
  'icon' =>'Athame.png',
  'damage'=>101,
  'stack'=>1,
  'pack'=>$pack);
$Items[1331]=array(
  'type' =>'tool',
  'name' =>'Diamond Drawplate',
  'title'=>'Diamond Drawplate %damaged%',
  'icon' =>'Diamond_Drawplate.png',
  'damage'=>256,
  'stack'=>1,
  'pack'=>$pack);
$Items[1332]=array(
  'type' =>'tool',
  'name' =>'Wool Card',
  'title'=>'Wool Card %damaged%',
  'icon' =>'Wool_Card.png',
  'damage'=>64,
  'stack'=>1,
  'pack'=>$pack);
$Items[1333]=array(
  0 =>array(
    'name' =>'Blank Floppy Disk',
    'icon' =>'Floppy_Disk.png',
    'stack'=>1,
    'pack' =>$pack),
  1 =>array(
    'name' =>'FORTH Boot Disk',
    'icon' =>'FORTH_Boot_Disk.png',
    'stack'=>1,
    'pack' =>$pack),
  -1=>array(
    'type' =>'map',
    'name' =>'Floppy Disk #map#',
    'title'=>'Floppy Disk #map#',
    'icon' =>'Floppy_Disk.png',
    'stack'=>1,
    'pack' =>$pack),
);
$Items[1334]=array(
  0 =>array(
    'name'=>'Iron Nugget',
    'icon'=>'Nugget_Iron.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Silver Nugget',
    'icon'=>'Nugget_Silver.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Tin Nugget',
    'icon'=>'Nugget_Tin.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Copper Nugget',
    'icon'=>'Nugget_Copper.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Nugget',
    'icon'=>'Nugget_Iron.png',
    'pack'=>$pack),
);


unset($Items);
?>