<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// default - item definitions


// enchantments
ItemFuncs::$Enchantments=array(
  0 =>array(
    'en'=>'Protection',
    ''=>'',
    ''=>''),
  1 =>array(
    'en'=>'Fire Protecion',
    ''=>'',
    ''=>''),
  2 =>array(
    'en'=>'Feather Falling',
    ''=>'',
    ''=>''),
  3 =>array(
    'en'=>'Blast Protection',
    ''=>'',
    ''=>''),
  4 =>array(
    'en'=>'Projectile Protection',
    ''=>'',
    ''=>''),
  5 =>array(
    'en'=>'Respiration',
    ''=>'',
    ''=>''),
  6 =>array(
    'en'=>'Aqua Affinity',
    ''=>'',
    ''=>''),
  16=>array(
    'en'=>'Sharpness',
    ''=>'',
    ''=>''),
  17=>array(
    'en'=>'Smite',
    ''=>'',
    ''=>''),
  18=>array(
    'en'=>'Bane of Arthropods',
    ''=>'',
    ''=>''),
  19=>array(
    'en'=>'Knockback',
    ''=>'',
    ''=>''),
  20=>array(
    'en'=>'Fire Aspect',
    ''=>'',
    ''=>''),
  21=>array(
    'en'=>'Looting',
    ''=>'',
    ''=>''),
  32=>array(
    'en'=>'Efficiency',
    ''=>'',
    ''=>''),
  33=>array(
    'en'=>'Silk Touch',
    ''=>'',
    ''=>''),
  34=>array(
    'en'=>'Unbreaking',
    ''=>'',
    ''=>''),
  35=>array(
    'en'=>'Fortune',
    ''=>'',
    ''=>''),
  48=>array(
    'en'=>'Power',
    ''=>'',
    ''=>''),
  49=>array(
    'en'=>'Punch',
    ''=>'',
    ''=>''),
  50=>array(
    'en'=>'Flame',
    ''=>'',
    ''=>''),
  51=>array(
    'en'=>'Infinity',
    ''=>'',
    ''=>''),
  -1=>array(
    'en'=>'Unknown',
    ''=>'',
    ''=>''),
);


// default items
ItemFuncs::$Items=array(
  1=>array(
    'name'=>array(
      'en'=>'Stone',
      'de'=>'Stein',
      ''=>'',
      ''=>''),
    'icon'=>'Stone.png'),
  2=>array(
    'name'=>array(
      'en'=>'Grass',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Grass.png'),
  3=>array(
    'name'=>array(
      'en'=>'Dirt',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Dirt.png'),
  4=>array(
    'name'=>array(
      'en'=>'Cobblestone',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Cobblestone.png'),
  5=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Wooden Plank (Oak)',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Wooden Plank (Pine)',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Wooden Plank (Birch)',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Wooden Plank (Jungle)',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Wooden Plank',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Oak.png'),
  ),
  6=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Oak Sapling',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Sapling_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Pine Sapling',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Sapling_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Birch Sapling',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Sapling_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Jungle Sapling',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Sapling_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Sapling',
        ''=>'',
        ''=>'',
        ''=>''),
      'icon'=>'Sapling.png'),
  ),
  7=>array(
    'name'=>array(
      'en'=>'Bedrock',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Bedrock.png'),
  8=>array(
    'name'=>array(
      'en'=>'Water',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Water.png'),
  9=>array(
    'name'=>array(
      'en'=>'Stationary Water',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Water.png'),
  10=>array(
    'name'=>array(
      'en'=>'Lava',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Lava.png'),
  11=>array(
    'name'=>array(
      'en'=>'Stationary Lava',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Lava.png'),
  12=>array(
    'name'=>array(
      'en'=>'Sand',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Sand.png'),
  13=>array(
    'name'=>array(
      'en'=>'Gravel',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Gravel.png'),
  14=>array(
    'name'=>array(
      'en'=>'Gold Ore',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Gold_Ore.png'),
  15=>array(
    'name'=>array(
      'en'=>'Iron Ore',
      ''=>'',
      ''=>'',
      ''=>''),
    'icon'=>'Iron_Ore.png'),
  16=>array(
    'name'=>array(
      'en'=>'Coal Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Coal_Ore.png'),
  17=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Oak Log',
        ''=>'',
        ''=>''),
      'icon'=>'Log_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Pine Log',
        ''=>'',
        ''=>''),
      'icon'=>'Log_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Birch Log',
        ''=>'',
        ''=>''),
      'icon'=>'Log_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Jungle Log',
        ''=>'',
        ''=>''),
      'icon'=>'Log_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Log',
        ''=>'',
        ''=>''),
      'icon'=>'Log_Oak.png'),
  ),
  18=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Oak Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Oak.png'),
    4 =>array(
      'name'=>array(
        'en'=>'Oak Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Pine Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Pine.png'),
    5 =>array(
      'name'=>array(
        'en'=>'Pine Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Birch Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Birch.png'),
    6 =>array(
      'name'=>array(
        'en'=>'Birch Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Jungle Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Jungle.png'),
    7 =>array(
      'name'=>array(
        'en'=>'Jungle Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Leaves',
        ''=>'',
        ''=>''),
      'icon'=>'Leaves_Oak.png'),
  ),
  19=>array(
    'name'=>array(
      'en'=>'Sponge',
      ''=>'',
      ''=>''),
    'icon'=>'Sponge.png'),
  20=>array(
    'name'=>array(
      'en'=>'Glass',
      ''=>'',
      ''=>''),
    'icon'=>'Glass.png'),
  21=>array(
    'name'=>array(
      'en'=>'Lapis Lazuli Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Lapis_Lazuli_Ore.png'),
  22=>array(
    'name'=>array(
      'en'=>'Lapis Lazuli Block',
      ''=>'',
      ''=>''),
    'icon'=>'Lapis_Lazuli_Block.png'),
  23=>array(
    'name'=>array(
      'en'=>'Dispenser',
      ''=>'',
      ''=>''),
    'icon'=>'Dispenser.png'),
  24=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Sandstone',
        ''=>'',
        ''=>''),
      'icon'=>'Sandstone.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Decorative Sandstone',
        ''=>'',
        ''=>''),
      'icon'=>'Sandstone_Decorative.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Smooth Sandstone',
        ''=>'',
        ''=>''),
      'icon'=>'Sandstone_Smooth.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Sandstone',
        ''=>'',
        ''=>''),
      'icon'=>'Sandstone.png'),
  ),
  25=>array(
    'name'=>array(
      'en'=>'Note Block',
      ''=>'',
      ''=>''),
    'icon'=>'Note_Block.png'),
  26=>array(
    'name'=>array(
      'en'=>'Bed Block',
      ''=>'',
      ''=>''),
    'icon'=>'Bed.png'),
  27=>array(
    'name'=>array(
      'en'=>'Powered Rail',
      ''=>'',
      ''=>''),
    'icon'=>'Rail_Powered.png'),
  28=>array(
    'name'=>array(
      'en'=>'Detector Rail',
      ''=>'',
      ''=>''),
    'icon'=>'Rail_Detector.png'),
  29=>array(
    'name'=>array(
      'en'=>'Sticky Piston',
      ''=>'',
      ''=>''),
    'icon'=>'Sticky_Piston.png'),
  30=>array(
    'name'=>array(
      'en'=>'Web',
      ''=>'',
      ''=>''),
    'icon'=>'Cobweb.png'),
  31=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Dead Shrub',
        ''=>'',
        ''=>''),
      'icon'=>'Tall_Grass1.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Tall Grass',
        ''=>'',
        ''=>''),
      'icon'=>'Tall_Grass2.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Live Shrub',
        ''=>'',
        ''=>''),
      'icon'=>'Tall_Grass3.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Shrub',
        ''=>'',
        ''=>''),
      'icon'=>'Tall_Grass1.png'),
  ),
  32=>array(
    'name'=>array(
      'en'=>'Dead Shrub',
      ''=>'',
      ''=>''),
    'icon'=>'Dead_Bush.png'),
  33=>array(
    'name'=>array(
      'en'=>'Piston',
      ''=>'',
      ''=>''),
    'icon'=>'Piston.png'),
  34=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Piston',
        ''=>'',
        ''=>''),
      'icon'=>'Piston.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Sticky_Piston',
        ''=>'',
        ''=>''),
      'icon'=>'Sticky_Piston.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Piston',
        ''=>'',
        ''=>''),
      'icon'=>'Piston.png'),
  ),
  35=>array(
    0 =>array(
      'name'=>array(
        'en'=>'White Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_White.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Orange Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Orange.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Magenta Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Magenta.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Light Blue Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Light_Blue.png'),
    4 =>array(
      'name'=>array(
        'en'=>'Yellow Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Yellow.png'),
    5 =>array(
      'name'=>array(
        'en'=>'Light Green Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Lime.png'),
    6 =>array(
      'name'=>array(
        'en'=>'Pink Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Pink.png'),
    7 =>array(
      'name'=>array(
        'en'=>'Grey Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Gray.png'),
    8 =>array(
      'name'=>array(
        'en'=>'Light Grey Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Light_Gray.png'),
    9 =>array(
      'name'=>array(
        'en'=>'Cyan Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Cyan.png'),
    10=>array(
      'name'=>array(
        'en'=>'Purple Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Purple.png'),
    11=>array(
      'name'=>array(
        'en'=>'Blue Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Blue.png'),
    12=>array(
      'name'=>array(
        'en'=>'Brown Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Brown.png'),
    13=>array(
      'name'=>array(
        'en'=>'Dark Green Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Green.png'),
    14=>array(
      'name'=>array(
        'en'=>'Red Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Red.png'),
    15=>array(
      'name'=>array(
        'en'=>'Black Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_Black.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Wool',
        ''=>'',
        ''=>''),
      'icon'=>'Wool_White.png'),
  ),
  37=>array(
    'name'=>array(
      'en'=>'Dandelion',
      ''=>'',
      ''=>''),
    'icon'=>'Dandelion.png'),
  38=>array(
    'name'=>array(
      'en'=>'Rose',
      ''=>'',
      ''=>''),
    'icon'=>'Rose.png'),
  39=>array(
    'name'=>array(
      'en'=>'Brown Mushroom',
      ''=>'',
      ''=>''),
    'icon'=>'Mushroom_Brown.png'),
  40=>array(
    'name'=>array(
      'en'=>'Red Mushroom',
      ''=>'',
      ''=>''),
    'icon'=>'Mushroom_Red.png'),
  41=>array(
    'name'=>array(
      'en'=>'Gold Block',
      ''=>'',
      ''=>''),
    'icon'=>'Gold_Block.png'),
  42=>array(
    'name'=>array(
      'en'=>'Iron Block',
      ''=>'',
      ''=>''),
    'icon'=>'Iron_Block.png'),
  // subitems 1, 2, and 3 not supported by minecraft
  //TODO: need images for these
  43=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Double Stone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Stone_Double.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Double Sandstone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Sandstone.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Double Wooden Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Wood.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Double Cobblestone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Cobblestone.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Double Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Stone_Double.png'),
  ),
  44=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Stone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Stone.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Sandstone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Sandstone.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Wooden Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Oak.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Cobblestone Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Cobblestone.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Stone.png'),
  ),
  45=>array(
    'name'=>array(
      'en'=>'Brick Block',
      ''=>'',
      ''=>''),
    'icon'=>'Brick_Block.png'),
  46=>array(
    'name'=>array(
      'en'=>'TNT',
      ''=>'',
      ''=>''),
    'icon'=>'TNT.png'),
  47=>array(
    'name'=>array(
      'en'=>'Bookshelf',
      ''=>'',
      ''=>''),
    'icon'=>'Bookshelf.png'),
  48=>array(
    'name'=>array(
      'en'=>'Mossy Cobblestone',
      ''=>'',
      ''=>''),
    'icon'=>'Cobblestone_Moss.png'),
  49=>array(
    'name'=>array(
      'en'=>'Obsidian',
      ''=>'',
      ''=>''),
    'icon'=>'Obsidian.png'),
  50=>array(
    'name'=>array(
      'en'=>'Torch',
      ''=>'',
      ''=>''),
    'icon'=>'Torch.png'),
  51=>array(
    'name'=>array(
      'en'=>'Fire',
      ''=>'',
      ''=>''),
    'icon'=>'Fire.png'),
  52=>array(
    50=>array(
      'name'=>array(
        'en'=>'Creeper Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Creeper.png'),
    51=>array(
      'name'=>array(
        'en'=>'Skeleton Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Skeleton.png'),
    52=>array(
      'name'=>array(
        'en'=>'Spider Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Spider.png'),
    53=>array(
      'name'=>array(
        'en'=>'Giant Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Giant.png'),
    54=>array(
      'name'=>array(
        'en'=>'Zombie Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Zombie.png'),
    55=>array(
      'name'=>array(
        'en'=>'Slime Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Slime.png'),
    56=>array(
      'name'=>array(
        'en'=>'Ghast Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Ghast.png'),
    57=>array(
      'name'=>array(
        'en'=>'Zombie Pigman Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Zombie_Pigman.png'),
    58=>array(
      'name'=>array(
        'en'=>'Enderman Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Enderman.png'),
    59=>array(
      'name'=>array(
        'en'=>'Cave Spider Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Cave_Spider.png'),
    60=>array(
      'name'=>array(
        'en'=>'Silverfish Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Silverfish.png'),
    61=>array(
      'name'=>array(
        'en'=>'Blaze Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Blaze.png'),
    62=>array(
      'name'=>array(
        'en'=>'Magma Cube Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Magma_Cube.png'),
    90=>array(
      'name'=>array(
        'en'=>'Pig Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Pig.png'),
    91=>array(
      'name'=>array(
        'en'=>'Sheep Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Sheep.png'),
    92=>array(
      'name'=>array(
        'en'=>'Cow Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Cow.png'),
    93=>array(
      'name'=>array(
        'en'=>'Chicken Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Chicken.png'),
    94=>array(
      'name'=>array(
        'en'=>'Squid Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Squid.png'),
    95=>array(
      'name'=>array(
        'en'=>'Wolf Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Wolf.png'),
    96=>array(
      'name'=>array(
        'en'=>'Mooshroom Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Mooshroom.png'),
    97=>array(
      'name'=>array(
        'en'=>'Snowman Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Snowman.png'),
   120=>array(
      'name'=>array(
        'en'=>'Villager Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Villager.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Spawner',
        ''=>'',
        ''=>''),
      'icon'=>'Spawner_Pig.png'),
  ),
  53=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Wooden Stairs (Oak)',
        ''=>'',
        ''=>''),
      'icon'=>'Stairs_Wooden_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Wooden Stairs (Pine)',
        ''=>'',
        ''=>''),
      'icon'=>'Stairs_Wooden_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Wooden Stairs (Birch)',
        ''=>'',
        ''=>''),
      'icon'=>'Stairs_Wooden_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Wooden Stairs (Jungle)',
        ''=>'',
        ''=>''),
      'icon'=>'Stairs_Wooden_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Wooden Stairs',
        ''=>'',
        ''=>''),
      'icon'=>'Stairs_Wooden_Oak.png'),
  ),
  54=>array(
    'name'=>array(
      'en'=>'Chest',
      ''=>'',
      ''=>''),
    'icon'=>'Chest.png'),
  55=>array(
    'name'=>array(
      'en'=>'Redstone Wire',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Dust.png'),
  56=>array(
    'name'=>array(
      'en'=>'Diamond Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Diamond_Ore.png'),
  57=>array(
    'name'=>array(
      'en'=>'Diamond Block',
      ''=>'',
      ''=>''),
    'icon'=>'Diamond_Block.png'),
  58=>array(
    'name'=>array(
      'en'=>'Workbench',
      ''=>'',
      ''=>''),
    'icon'=>'Crafting_Table.png'),
//  // TODO=> add crop picture(s)
//  59=>array(
//    'name'=>array(
//      'en'=>'Crops',
//      ''=>'',
//      ''=>''),
//    'icon'=>'Crops'),
  60=>array(
    'name'=>array(
      'en'=>'Soil',
      ''=>'',
      ''=>''),
    'icon'=>'Farmland.png'),
  61=>array(
    'name'=>array(
      'en'=>'Furnace',
      ''=>'',
      ''=>''),
    'icon'=>'Furnace.png'),
  62=>array(
    'name'=>array(
      'en'=>'Burning Furnace',
      ''=>'',
      ''=>''),
    'icon'=>'Furnace.png'),
  63=>array(
    'name'=>array(
      'en'=>'Sign Post',
      ''=>'',
      ''=>''),
    'icon'=>'Sign.png',
    'stack'=>16),
  64=>array(
    'name'=>array(
      'en'=>'Wooden Door Block',
      ''=>'',
      ''=>''),
    'icon'=>'Door_Wood.png',
    'stack'=>1),
  65=>array(
    'name'=>array(
      'en'=>'Ladder',
      ''=>'',
      ''=>''),
    'icon'=>'Ladder.png'),
  66=>array(
    'name'=>array(
      'en'=>'Rail',
      ''=>'',
      ''=>''),
    'icon'=>'Rails.png'),
  67=>array(
    'name'=>array(
      'en'=>'Cobblestone Stairs',
      ''=>'',
      ''=>''),
    'icon'=>'Stairs_Cobblestone.png'),
  68=>array(
    'name'=>array(
      'en'=>'Wall Sign',
      ''=>'',
      ''=>''),
    'icon'=>'Sign.png',
    'stack'=>16),
  69=>array(
    'name'=>array(
      'en'=>'Lever',
      ''=>'',
      ''=>''),
    'icon'=>'Lever.png'),
  70=>array(
    'name'=>array(
      'en'=>'Stone Pressure Plate',
      ''=>'',
      ''=>''),
    'icon'=>'Pressure_Plate_Stone.png'),
  71=>array(
    'name'=>array(
      'en'=>'Iron Door Block',
      ''=>'',
      ''=>''),
    'icon'=>'Door_Iron.png',
    'stack'=>1),
  72=>array(
    'name'=>array(
      'en'=>'Wooden Pressure Plate',
      ''=>'',
      ''=>''),
    'icon'=>'Pressure_Plate_Wood.png'),
  73=>array(
    'name'=>array(
      'en'=>'Redstone Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Ore.png'),
  74=>array(
    'name'=>array(
      'en'=>'Glowing Redstone Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Ore.png'),
  75=>array(
    'name'=>array(
      'en'=>'Redstone Torch',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Torch.png'),
  76=>array(
    'name'=>array(
      'en'=>'Redstone Torch',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Torch.png'),
  77=>array(
    'name'=>array(
      'en'=>'Stone Button',
      ''=>'',
      ''=>''),
    'icon'=>'Stone_Button.png'),
  78=>array(
    'name'=>array(
      'en'=>'Snow',
      ''=>'',
      ''=>''),
    'icon'=>'Snow_Block.png'),
  79=>array(
    'name'=>array(
      'en'=>'Ice',
      ''=>'',
      ''=>''),
    'icon'=>'Ice.png'),
  80=>array(
    'name'=>array(
      'en'=>'Snow Block',
      ''=>'',
      ''=>''),
    'icon'=>'Snow_Block.png'),
  81=>array(
    'name'=>array(
      'en'=>'Cactus',
      ''=>'',
      ''=>''),
    'icon'=>'Cactus.png'),
  82=>array(
    'name'=>array(
      'en'=>'Clay',
      ''=>'',
      ''=>''),
    'icon'=>'Clay_Block.png'),
  83=>array(
    'name'=>array(
      'en'=>'Sugar Cane',
      ''=>'',
      ''=>''),
    'icon'=>'Sugar_Cane.png'),
  84=>array(
    'name'=>array(
      'en'=>'Jukebox',
      ''=>'',
      ''=>''),
    'icon'=>'Jukebox.png'),
  85=>array(
    'name'=>array(
      'en'=>'Fence',
      ''=>'',
      ''=>''),
    'icon'=>'Fence.png'),
  86=>array(
    'name'=>array(
      'en'=>'Pumpkin',
      ''=>'',
      ''=>''),
    'icon'=>'Pumpkin.png'),
  87=>array(
    'name'=>array(
      'en'=>'Netherrack',
      ''=>'',
      ''=>''),
    'icon'=>'Netherrack.png'),
  88=>array(
    'name'=>array(
      'en'=>'Soul Sand',
      ''=>'',
      ''=>''),
    'icon'=>'Soul_Sand.png'),
  89=>array(
    'name'=>array(
      'en'=>'Glowstone',
      ''=>'',
      ''=>''),
    'icon'=>'Glowstone_Block.png'),
  90=>array(
    'name'=>array(
      'en'=>'Portal',
      ''=>'',
      ''=>''),
    'icon'=>'Portal.png'),
  91=>array(
    'name'=>array(
      'en'=>'Jack-O-Lantern',
      ''=>'',
      ''=>''),
    'icon'=>'Jack-O-Lantern.png'),
  92=>array(
    'name'=>array(
      'en'=>'Cake',
      ''=>'',
      ''=>''),
    'icon'=>'Cake.png',
    'stack'=>1),
  93=>array(
    'name'=>array(
      'en'=>'Redstone Repeater',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Repeater.png'),
  94=>array(
    'name'=>array(
      'en'=>'Redstone Repeater',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Repeater.png'),
  95=>array(
    'name'=>array(
      'en'=>'Locked Chest',
      ''=>'',
      ''=>''),
    'icon'=>'Chest.png'),
  96=>array(
    'name'=>array(
      'en'=>'Trapdoor',
      ''=>'',
      ''=>''),
    'icon'=>'Trapdoor.png'),
//  97=>array(
//    'name'=>array(
//      'en'=>'Silverfish Stone',
//      ''=>'',
//      ''=>''),
//    'icon'=>''),
  98=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Stone Brick',
        ''=>'',
        ''=>''),
      'icon'=>'Stone_Brick.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Mossy Stone Brick',
        ''=>'',
        ''=>''),
      'icon'=>'Stone_Brick_Mossy.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Cracked Stone Brick',
        ''=>'',
        ''=>''),
      'icon'=>'Stone_Brick_Cracked.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Circle Stone Brick',
        ''=>'',
        ''=>''),
      'icon'=>'Stone_Brick_Circle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Brick',
        ''=>'',
        ''=>''),
      'icon'=>'Stone_Brick.png'),
  ),
  99=>array(
    'name'=>array(
      'en'=>'Brown Mushroom Cap',
      ''=>'',
      ''=>''),
    'icon'=>'Mushroom_Brown.png'),
  100=>array(
    'name'=>array(
      'en'=>'Red Mushroom Cap',
      ''=>'',
      ''=>''),
    'icon'=>'Mushroom_Red.png'),
  101=>array(
    'name'=>array(
      'en'=>'Iron Bars',
      ''=>'',
      ''=>''),
    'icon'=>'Iron_Bars.png'),
  102=>array(
    'name'=>array(
      'en'=>'Glass Pane',
      ''=>'',
      ''=>''),
    'icon'=>'Glass_Pane.png'),
  103=>array(
    'name'=>array(
      'en'=>'Melon',
      ''=>'',
      ''=>''),
    'icon'=>'Melon_Block.png'),
//  // TODO=> add pumpkin and melon steam pictures
//  104=>array(
//    'name'=>array(
//      'en'=>'Pumpkin Stem',
//        ''=>'',
//        ''=>''),
//    'icon'=>''),
//  105=>array(
//    'name'=>array(
//      'en'=>'Melon Stem',
//        ''=>'',
//        ''=>''),
//    'icon'=>''),
  106=>array(
    'name'=>array(
      'en'=>'Vines',
      ''=>'',
      ''=>''),
    'icon'=>'Vines.png'),
  107=>array(
    'name'=>array(
      'en'=>'Fence Gate',
      ''=>'',
      ''=>''),
    'icon'=>'Fence_Gate.png'),
  108=>array(
    'name'=>array(
      'en'=>'Brick Stairs',
      ''=>'',
      ''=>''),
    'icon'=>'Stairs_Brick.png'),
  109=>array(
    'name'=>array(
      'en'=>'Stone Brick Stairs',
      ''=>'',
      ''=>''),
    'icon'=>'Stairs_Stone_Brick.png'),
  110=>array(
    'name'=>array(
      'en'=>'Mycelium',
      ''=>'',
      ''=>''),
    'icon'=>'Mycelium.png'),
  111=>array(
    'name'=>array(
      'en'=>'Lily Pad',
      ''=>'',
      ''=>''),
    'icon'=>'Lily_Pad.png'),
  112=>array(
    'name'=>array(
      'en'=>'Nether Brick',
      ''=>'',
      ''=>''),
    'icon'=>'Nether_Brick.png'),
  113=>array(
    'name'=>array(
      'en'=>'Nether Brick Fence',
      ''=>'',
      ''=>''),
    'icon'=>'Nether_Brick_Fence.png'),
  114=>array(
    'name'=>array(
      'en'=>'Nether Brick Stairs',
      ''=>'',
      ''=>''),
    'icon'=>'Stairs_Nether_Brick.png'),
  115=>array(
    'name'=>array(
      'en'=>'Nether Wart',
      ''=>'',
      ''=>''),
    'icon'=>'Nether_Wart.png'),
  116=>array(
    'name'=>array(
      'en'=>'Enchantment Table',
      ''=>'',
      ''=>''),
    'icon'=>'Enchantment_Table.png'),
  117=>array(
    'name'=>array(
      'en'=>'Brewing Stand',
      ''=>'',
      ''=>''),
    'icon'=>'Brewing_Stand.png'),
  118=>array(
    'name'=>array(
      'en'=>'Cauldron',
      ''=>'',
      ''=>''),
    'icon'=>'Cauldron.png'),
  119=>array(
    'name'=>array(
      'en'=>'End Portal',
      ''=>'',
      ''=>''),
    'icon'=>'End_Portal.png'),
  120=>array(
    'name'=>array(
      'en'=>'End Portal Frame',
      ''=>'',
      ''=>''),
    'icon'=>'End_Portal_Frame.png'),
  121=>array(
    'name'=>array(
      'en'=>'End Stone',
      ''=>'',
      ''=>''),
    'icon'=>'End_Stone.png'),
  122=>array(
    'name'=>array(
      'en'=>'Dragon Egg',
      ''=>'',
      ''=>''),
    'icon'=>'Dragon_Egg.png'),
  123=>array(
    'name'=>array(
      'en'=>'Redstone Lamp',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Lamp.png'),
  //TODO: need images for these
  125=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Double Wooden Slab (Oak)',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Double Wooden Slab (Pine)',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Double Wooden Slab (Birch)',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Double Wooden Slab (Jungle)',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Double Wooden Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Wooden_Plank_Oak.png'),
  ),
  126=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Wooden Slab (Oak)',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Oak.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Wooden Slab (Pine)',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Pine.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Wooden Slab (Birch)',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Birch.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Wooden Slab (Jungle)',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Jungle.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Wooden Slab',
        ''=>'',
        ''=>''),
      'icon'=>'Slab_Wood_Oak.png'),
  ),
  128=>array(
    'name'=>array(
      'en'=>'Sandstone Stairs',
      ''=>'',
      ''=>''),
    'icon'=>'Stairs_Sandstone.png'),
  129=>array(
    'name'=>array(
      'en'=>'Emerald Ore',
      ''=>'',
      ''=>''),
    'icon'=>'Emerald_Ore.png'),
  130=>array(
    'name'=>array(
      'en'=>'Ender Chest',
      ''=>'',
      ''=>''),
    'icon'=>'Ender_Chest.png'),
  131=>array(
    'name'=>array(
      'en'=>'Tripwire Hook',
      ''=>'',
      ''=>''),
    'icon'=>'Tripwire_Hook.png'),
  133=>array(
    'name'=>array(
      'en'=>'Emerald Block',
      ''=>'',
      ''=>''),
    'icon'=>'Emerald_Block.png'),
  256=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Shovel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Shovel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Shovel.png',
    'damage'=>251,
    'stack'=>1),
  257=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Pickaxe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Pickaxe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Pickaxe.png',
    'damage'=>251,
    'stack'=>1),
  258=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Axe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Axe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Axe.png',
    'damage'=>251,
    'stack'=>1),
  259=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Flint and Steel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Flint and Steel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Flint_and_Steel.png',
    'damage'=>65,
    'stack'=>1),
  260=>array(
    'name'=>array(
      'en'=>'Apple',
      ''=>'',
      ''=>''),
    'icon'=>'Apple_Red.png'),
  261=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Bow',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Bow %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Bow.png',
    'damage'=>385,
    'stack'=>1),
  262=>array(
    'name'=>array(
      'en'=>'Arrow',
      ''=>'',
      ''=>''),
    'icon'=>'Arrow.png'),
  263=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Coal',
        ''=>'',
        ''=>''),
      'icon'=>'Coal_Item.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Charcoal',
        ''=>'',
        ''=>''),
      'icon'=>'Charcoal_Item.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Coal',
        ''=>'',
        ''=>''),
      'icon'=>'Coal_Item.png'),
  ),
  264=>array(
    'name'=>array(
      'en'=>'Diamond',
      ''=>'',
      ''=>''),
    'icon'=>'Diamond_Gem.png'),
  265=>array(
    'name'=>array(
      'en'=>'Iron Ingot',
      ''=>'',
      ''=>''),
    'icon'=>'Iron_Ingot.png'),
  266=>array(
    'name'=>array(
      'en'=>'Gold Ingot',
      ''=>'',
      ''=>''),
    'icon'=>'Gold_Ingot.png'),
  267=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Sword',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Sword %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Sword.png',
    'damage'=>251,
    'stack'=>1),
  268=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Wooden Sword',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Wooden Sword %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Wooden_Sword.png',
    'damage'=>60,
    'stack'=>1),
  269=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Wooden Shovel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Wooden Shovel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Wooden_Shovel.png',
    'damage'=>60,
    'stack'=>1),
  270=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Wooden Pickaxe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Wooden Pickaxe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Wooden_Pickaxe.png',
    'damage'=>60,
    'stack'=>1),
  271=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Wooden Axe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Wooden Axe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Wooden_Axe.png',
    'damage'=>60,
    'stack'=>1),
  272=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Stone Sword',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Stone Sword %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Stone_Sword.png',
    'damage'=>132,
    'stack'=>1),
  273=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Stone Shovel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Stone Shovel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Stone_Shovel.png',
    'damage'=>132,
    'stack'=>1),
  274=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Stone Pickaxe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Stone Pickaxe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Stone_Pickaxe.png',
    'damage'=>132,
    'stack'=>1),
  275=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Stone Axe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Stone Axe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Stone_Axe.png',
    'damage'=>132,
    'stack'=>1),
  276=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Sword',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Sword %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Sword.png',
    'damage'=>1562,
    'stack'=>1),
  277=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Shovel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Shovel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Shovel.png',
    'damage'=>1562,
    'stack'=>1),
  278=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Pickaxe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Pickaxe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Pickaxe.png',
    'damage'=>1562,
    'stack'=>1),
  279=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Axe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Axe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Axe.png',
    'damage'=>1562,
    'stack'=>1),
  280=>array(
    'name'=>array(
      'en'=>'Stick',
      ''=>'',
      ''=>''),
    'icon'=>'Stick.png'),
  281=>array(
    'name'=>array(
      'en'=>'Bowl',
      ''=>'',
      ''=>''),
    'icon'=>'Bowl.png'),
  282=>array(
    'name'=>array(
      'en'=>'Mushroom Soup',
      ''=>'',
      ''=>''),
    'icon'=>'Mushroom_Stew.png',
    'stack'=>1),
  283=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Sword',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Sword %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Sword.png',
    'damage'=>33,
    'stack'=>1),
  284=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Shovel',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Shovel %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Shovel.png',
    'damage'=>33,
    'stack'=>1),
  285=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Pickaxe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Pickaxe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Pickaxe.png',
    'damage'=>33,
    'stack'=>1),
  286=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Axe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Axe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Axe.png',
    'damage'=>33,
    'stack'=>1),
  287=>array(
    'name'=>array(
      'en'=>'String',
      ''=>'',
      ''=>''),
    'icon'=>'String.png'),
  288=>array(
    'name'=>array(
      'en'=>'Feather',
      ''=>'',
      ''=>''),
    'icon'=>'Feather.png'),
  289=>array(
    'name'=>array(
      'en'=>'Gunpowder',
      ''=>'',
      ''=>''),
    'icon'=>'Gunpowder.png'),
  290=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Wooden Hoe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Wooden Hoe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Wooden_Hoe.png',
    'damage'=>60,
    'stack'=>1),
  291=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Stone Hoe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Stone Hoe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Stone_Hoe.png',
    'damage'=>132,
    'stack'=>1),
  292=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Hoe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Hoe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Hoe.png',
    'damage'=>251,
    'stack'=>1),
  293=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Hoe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Hoe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Hoe.png',
    'damage'=>1562,
    'stack'=>1),
  294=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Hoe',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Hoe %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Hoe.png',
    'damage'=>33,
    'stack'=>1),
  295=>array(
    'name'=>array(
      'en'=>'Wheat Seeds',
      ''=>'',
      ''=>''),
    'icon'=>'Seeds_Wheat.png'),
  296=>array(
    'name'=>array(
      'en'=>'Wheat',
      ''=>'',
      ''=>''),
    'icon'=>'Wheat.png'),
  297=>array(
    'name'=>array(
      'en'=>'Bread',
      ''=>'',
      ''=>''),
    'icon'=>'Bread.png'),
  298=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Leather Helmet',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Leather Helmet %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Leather_Helmet.png',
    'damage'=>56,
    'stack'=>1),
  299=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Leather Chestplate',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Leather Chestplate %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Leather_Chestplate.png',
    'damage'=>81,
    'stack'=>1),
  300=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Leather Leggings',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Leather Leggings %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Leather_Pants.png',
    'damage'=>76,
    'stack'=>1),
  301=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Leather Boots',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Leather Boots %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Leather_Boots.png',
    'damage'=>66,
    'stack'=>1),
  302=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Chain Mail Helmet',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Chain Mail Helmet %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Chain_Armor_Helmet.png',
    'damage'=>166,
    'stack'=>1),
  303=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Chain Mail Chestplate',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Chain Mail Chestplate %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Chain_Armor_Chestplate.png',
    'damage'=>241,
    'stack'=>1),
  304=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Chain Mail Leggings',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Chain Mail Leggings %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Chain_Armor_Leggings.png',
    'damage'=>226,
    'stack'=>1),
  305=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Chain Mail Boots',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Chain Mail Boots %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Chain_Armor_Boots.png',
    'damage'=>196,
    'stack'=>1),
  306=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Helmet',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Helmet %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Helmet.png',
    'damage'=>166,
    'stack'=>1),
  307=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Chestplate',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Chestplate %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Chestplate.png',
    'damage'=>241,
    'stack'=>1),
  308=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Leggings',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Leggings %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Leggings.png',
    'damage'=>226,
    'stack'=>1),
  309=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Iron Boots',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Iron Boots %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Iron_Boots.png',
    'damage'=>196,
    'stack'=>1),
  310=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Helmet',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Helmet %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Helmet.png',
    'damage'=>364,
    'stack'=>1),
  311=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Chestplate',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Chestplate %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Chestplate.png',
    'damage'=>529,
    'stack'=>1),
  312=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Leggings',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Leggings %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Leggings.png',
    'damage'=>496,
    'stack'=>1),
  313=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Diamond Boots',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Diamond Boots %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Diamond_Boots.png',
    'damage'=>430,
    'stack'=>1),
  314=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Helmet',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Helmet %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Helmet.png',
    'damage'=>78,
    'stack'=>1),
  315=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Chestplate',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Chestplate %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Chestplate.png',
    'damage'=>113,
    'stack'=>1),
  316=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Leggings',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Leggings %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Leggings.png',
    'damage'=>106,
    'stack'=>1),
  317=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Gold Boots',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Gold Boots %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Gold_Boots.png',
    'damage'=>92,
    'stack'=>1),
  318=>array(
    'name'=>array(
      'en'=>'Flint',
      ''=>'',
      ''=>''),
    'icon'=>'Flint.png'),
  319=>array(
    'name'=>array(
      'en'=>'Raw Porkchop',
      ''=>'',
      ''=>''),
    'icon'=>'Porkchop_Raw.png'),
  320=>array(
    'name'=>array(
      'en'=>'Cooked Porkchop',
      ''=>'',
      ''=>''),
    'icon'=>'Porkchop_Cooked.png'),
  321=>array(
    'name'=>array(
      'en'=>'Painting',
      ''=>'',
      ''=>''),
    'icon'=>'Painting.png'),
  322=>array(
    'name'=>array(
      'en'=>'Golden Apple',
      ''=>'',
      ''=>''),
    'icon'=>'Apple_Golden.png'),
  323=>array(
    'name'=>array(
      'en'=>'Sign',
      ''=>'',
      ''=>''),
    'icon'=>'Sign.png',
    'stack'=>16),
  324=>array(
    'name'=>array(
      'en'=>'Wooden Door',
      ''=>'',
      ''=>''),
    'icon'=>'Door_Wood.png',
    'stack'=>1),
  325=>array(
    'name'=>array(
      'en'=>'Bucket',
      ''=>'',
      ''=>''),
    'icon'=>'Bucket.png',
    'stack'=>16),
  326=>array(
    'name'=>array(
      'en'=>'Bucket of Water',
      ''=>'',
      ''=>''),
    'icon'=>'Bucket_Water.png',
    'stack'=>1),
  327=>array(
    'name'=>array(
      'en'=>'Bucket of Lava',
      ''=>'',
      ''=>''),
    'icon'=>'Bucket_Lava.png',
    'stack'=>1),
  328=>array(
    'name'=>array(
      'en'=>'Minecart',
      ''=>'',
      ''=>''),
    'icon'=>'Minecart.png',
    'stack'=>1),
  329=>array(
    'name'=>array(
      'en'=>'Saddle',
      ''=>'',
      ''=>''),
    'icon'=>'Saddle.png',
    'stack'=>1),
  330=>array(
    'name'=>array(
      'en'=>'Iron Door',
      ''=>'',
      ''=>''),
    'icon'=>'Door_Iron.png',
    'stack'=>1),
  331=>array(
    'name'=>array(
      'en'=>'Redstone',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Dust.png'),
  332=>array(
    'name'=>array(
      'en'=>'Snowball',
      ''=>'',
      ''=>''),
    'icon'=>'Snowball.png',
    'stack'=>16),
  333=>array(
    'name'=>array(
      'en'=>'Boat',
      ''=>'',
      ''=>''),
    'icon'=>'Boat.png',
    'stack'=>1),
  334=>array(
    'name'=>array(
      'en'=>'Leather',
      ''=>'',
      ''=>''),
    'icon'=>'Leather.png'),
  335=>array(
    'name'=>array(
      'en'=>'Bucket of Milk',
      ''=>'',
      ''=>''),
    'icon'=>'Bucket_Milk.png',
    'stack'=>1),
  336=>array(
    'name'=>array(
      'en'=>'Clay Brick',
      ''=>'',
      ''=>''),
    'icon'=>'Clay_Brick.png'),
  337=>array(
    'name'=>array(
      'en'=>'Clay Balls',
      ''=>'',
      ''=>''),
    'icon'=>'Clay_Item.png'),
  338=>array(
    'name'=>array(
      'en'=>'Sugar Cane',
      ''=>'',
      ''=>''),
    'icon'=>'Sugar_Cane.png'),
  339=>array(
    'name'=>array(
      'en'=>'Paper',
      ''=>'',
      ''=>''),
    'icon'=>'Paper.png'),
  340=>array(
    'name'=>array(
      'en'=>'Book',
      ''=>'',
      ''=>''),
    'icon'=>'Book.png'),
  341=>array(
    'name'=>array(
      'en'=>'Slimeball',
      ''=>'',
      ''=>''),
    'icon'=>'Slimeball.png'),
  342=>array(
    'name'=>array(
      'en'=>'Storage Minecart',
      ''=>'',
      ''=>''),
    'icon'=>'Minecart_Storage.png',
    'stack'=>1),
  343=>array(
    'name'=>array(
      'en'=>'Powered Minecart',
      ''=>'',
      ''=>''),
    'icon'=>'Minecart_Powered.png',
    'stack'=>1),
  344=>array(
    'name'=>array(
      'en'=>'Egg',
      ''=>'',
      ''=>''),
    'icon'=>'Egg.png',
    'stack'=>16),
  345=>array(
    'name'=>array(
      'en'=>'Compass',
      ''=>'',
      ''=>''),
    'icon'=>'Compass.png'),
  346=>array(
    'type' =>'tool',
    'name'=>array(
      'en'=>'Fishing Rod',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Fishing Rod %damaged%',
      ''=>'',
      ''=>''),
    'icon'=>'Fishing_Rod.png',
    'damage'=>65,
    'stack'=>1),
  347=>array(
    'name'=>array(
      'en'=>'Clock',
      ''=>'',
      ''=>''),
    'icon'=>'Clock.png'),
  348=>array(
    'name'=>array(
      'en'=>'Glowstone Dust',
      ''=>'',
      ''=>''),
    'icon'=>'Glowstone_Dust.png'),
  349=>array(
    'name'=>array(
      'en'=>'Raw Fish',
      ''=>'',
      ''=>''),
    'icon'=>'Fish_Raw.png'),
  350=>array(
    'name'=>array(
      'en'=>'Cooked Fish',
      ''=>'',
      ''=>''),
    'icon'=>'Fish_Cooked.png'),
  351=>array(
    0 =>array(
      'name'=>array(
        'en'=>'Ink Sack',
        ''=>'',
        ''=>''),
      'icon'=>'Ink_Sac.png'),
    1 =>array(
      'name'=>array(
        'en'=>'Rose Red',
        ''=>'',
        ''=>''),
      'icon'=>'Rose_Red.png'),
    2 =>array(
      'name'=>array(
        'en'=>'Cactus Green',
        ''=>'',
        ''=>''),
      'icon'=>'Cactus_Green.png'),
    3 =>array(
      'name'=>array(
        'en'=>'Cocoa Beans',
        ''=>'',
        ''=>''),
      'icon'=>'Cocoa_Beans.png'),
    4 =>array(
      'name'=>array(
        'en'=>'Lapis Lazuli',
        ''=>'',
        ''=>''),
      'icon'=>'Lapis_Lazuli_Dye.png'),
    5 =>array(
      'name'=>array(
        'en'=>'Purple Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Purple.png'),
    6 =>array(
      'name'=>array(
        'en'=>'Cyan Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Cyan.png'),
    7 =>array(
      'name'=>array(
        'en'=>'Light Grey Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Light_Gray.png'),
    8 =>array(
      'name'=>array(
        'en'=>'Grey Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Gray.png'),
    9 =>array(
      'name'=>array(
        'en'=>'Pink Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Pink.png'),
    10=>array(
      'name'=>array(
        'en'=>'Lime Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Lime.png'),
    11=>array(
      'name'=>array(
        'en'=>'Dandelion Yellow',
        ''=>'',
        ''=>''),
      'icon'=>'Dandelion_Yellow.png'),
    12=>array(
      'name'=>array(
        'en'=>'Light Blue Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Light_Blue.png'),
    13=>array(
      'name'=>array(
        'en'=>'Magenta Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Magenta.png'),
    14=>array(
      'name'=>array(
        'en'=>'Orange Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Dye_Orange.png'),
    15=>array(
      'name'=>array(
        'en'=>'Bone Meal',
        ''=>'',
        ''=>''),
      'icon'=>'Bone_Meal.png'),
    -1=>array(
      'name'=>array(
        'en'=>'Unknown Dye',
        ''=>'',
        ''=>''),
      'icon'=>'Bone_Meal.png'),
  ),
  352=>array(
    'name'=>array(
      'en'=>'Bone',
      ''=>'',
      ''=>''),
    'icon'=>'Bone.png'),
  353=>array(
    'name'=>array(
      'en'=>'Sugar',
      ''=>'',
      ''=>''),
    'icon'=>'Sugar.png'),
  354=>array(
    'name'=>array(
      'en'=>'Cake',
      ''=>'',
      ''=>''),
    'icon'=>'Cake.png',
    'stack'=>1),
  355=>array(
    'name'=>array(
      'en'=>'Bed',
      ''=>'',
      ''=>''),
    'icon'=>'Bed.png',
    'stack'=>1),
  356=>array(
    'name'=>array(
      'en'=>'Redstone Repeater',
      ''=>'',
      ''=>''),
    'icon'=>'Redstone_Repeater.png'),
  357=>array(
    'name'=>array(
      'en'=>'Cookie',
      ''=>'',
      ''=>''),
    'icon'=>'Cookie.png'),
  358=>array(
    'type' =>'map',
    'name' =>array(
      'en'=>'Map #map#',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Map #map#',
      ''=>'',
      ''=>''),
    'icon' =>'Map_Item.png',
    'stack'=>1),
  359=>array(
    'type' =>'tool',
    'name' =>array(
      'en'=>'Shears',
      ''=>'',
      ''=>''),
    'title'=>array(
      'en'=>'Shears %damaged%',
      ''=>'',
      ''=>''),
    'icon' =>'Shears.png',
    'damage'=>238,
    'stack'=>1),
  360=>array(
    'name'=>array(
      'en'=>'Melon Slice',
      ''=>'',
      ''=>''),
    'icon'=>'Melon_Slice.png'),
  361=>array(
    'name'=>array(
      'en'=>'Pumpkin Seeds',
      ''=>'',
      ''=>''),
    'icon'=>'Seeds_Pumpkin.png'),
  362=>array(
    'name'=>array(
      'en'=>'Melon Seeds',
      ''=>'',
      ''=>''),
    'icon'=>'Seeds_Melon.png'),
  363=>array(
    'name'=>array(
      'en'=>'Raw Beef',
      ''=>'',
      ''=>''),
    'icon'=>'Beef_Raw.png'),
  364=>array(
    'name'=>array(
      'en'=>'Steak',
      ''=>'',
      ''=>''),
    'icon'=>'Beef_Cooked.png'),
  365=>array(
    'name'=>array(
      'en'=>'Raw Chicken',
      ''=>'',
      ''=>''),
    'icon'=>'Chicken_Raw.png'),
  366=>array(
    'name'=>array(
      'en'=>'Cooked Chicken',
      ''=>'',
      ''=>''),
    'icon'=>'Chicken_Cooked.png'),
  367=>array(
    'name'=>array(
      'en'=>'Rotten Flesh',
      ''=>'',
      ''=>''),
    'icon'=>'Rotten_Flesh.png'),
  368=>array(
    'name'=>array(
      'en'=>'Ender Pearl',
      ''=>'',
      ''=>''),
    'icon'=>'Ender_Pearl.png',
    'stack'=>16),
  369=>array(
    'name'=>array(
      'en'=>'Blaze Rod',
      ''=>'',
      ''=>''),
    'icon'=>'Blaze_Rod.png'),
  370=>array(
    'name'=>array(
      'en'=>'Ghast Tear',
      ''=>'',
      ''=>''),
    'icon'=>'Ghast_Tear.png'),
  371=>array(
    'name'=>array(
      'en'=>'Gold Nugget',
      ''=>'',
      ''=>''),
    'icon'=>'Gold_Nugget.png'),
  372=>array(
    'name'=>array(
      'en'=>'Nether Wart',
      ''=>'',
      ''=>''),
    'icon'=>'Seeds_Nether_Wart.png'),
  373=>array(
    0    =>array(
      'name'=>array(
        'en'=>'Bottle of Water',
        ''=>'',
        ''=>''),
      'icon'=>'Bottle_Water.png',
      'stack'=>1),
    16   =>array(
      'name'=>array(
        'en'=>'Awkward Potion',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Awkward.png',
      'stack'=>1),
    32   =>array(
      'name'=>array(
        'en'=>'Thick Potion',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Thick.png',
      'stack'=>1),
    64   =>array(
      'name'=>array(
        'en'=>'Mundane Potion',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Mundane.png',
      'stack'=>1),
    16273=>array(
      'name'=>array(
        'en'=>'Regeneration Potion (0:45)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration.png',
      'stack'=>1),
    16274=>array(
      'name'=>array(
        'en'=>'Speed Potion (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed.png',
      'stack'=>1),
    16276=>array(
      'name'=>array(
        'en'=>'Poison Potion (0:45)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison.png',
      'stack'=>1),
    16281=>array(
      'name'=>array(
        'en'=>'Strength Potion (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength.png',
      'stack'=>1),
    16305=>array(
      'name'=>array(
        'en'=>'Regeneration Potion II (0:22)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration.png',
      'stack'=>1),
    16306=>array(
      'name'=>array(
        'en'=>'Speed Potion II (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed.png',
      'stack'=>1),
    16307=>array(
      'name'=>array(
        'en'=>'Fire Resistance Potion (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Fire_Resistance.png',
      'stack'=>1),
    16308=>array(
      'name'=>array(
        'en'=>'Poison Potion II (0:22)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison.png',
      'stack'=>1),
    16312=>array(
      'name'=>array(
        'en'=>'Weakness Potion (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Weakness.png',
      'stack'=>1),
    16313=>array(
      'name'=>array(
        'en'=>'Strength Potion II (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength.png',
      'stack'=>1),
    16314=>array(
      'name'=>array(
        'en'=>'Slowness Potion (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Slowness.png',
      'stack'=>1),
    16337=>array(
      'name'=>array(
        'en'=>'Regeneration Potion (2:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration.png',
      'stack'=>1),
    16338=>array(
      'name'=>array(
        'en'=>'Speed Potion (8:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed.png',
      'stack'=>1),
    16340=>array(
      'name'=>array(
        'en'=>'Poison Potion (2:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison.png',
      'stack'=>1),
    16345=>array(
      'name'=>array(
        'en'=>'Strength Potion (8:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength.png',
      'stack'=>1),
    16369=>array(
      'name'=>array(
        'en'=>'Regeneration Splash II (1:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration_Splash.png',
      'stack'=>1),
    16370=>array(
      'name'=>array(
        'en'=>'Speed Potion II (4:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed.png',
      'stack'=>1),
    16371=>array(
      'name'=>array(
        'en'=>'Fire Resistance Potion (8:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Fire_Resistance.png',
      'stack'=>1),
    16372=>array(
      'name'=>array(
        'en'=>'Poison Potion II (1:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison.png',
      'stack'=>1),
    16376=>array(
      'name'=>array(
        'en'=>'Weakness Potion (4:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Weakness.png',
      'stack'=>1),
    16377=>array(
      'name'=>array(
        'en'=>'Strength Potion II (4:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength.png',
      'stack'=>1),
    16378=>array(
      'name'=>array(
        'en'=>'Slowness Potion (4:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Slowness.png',
      'stack'=>1),
    32657=>array(
      'name'=>array(
        'en'=>'Splash of Regeneration (0:33)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration_Splash.png',
      'stack'=>1),
    32658=>array(
      'name'=>array(
        'en'=>'Splash of Speed (2:15)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed_Splash.png',
      'stack'=>1),
    32660=>array(
      'name'=>array(
        'en'=>'Splash of Poison (0:33)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison_Splash.png',
      'stack'=>1),
    32665=>array(
      'name'=>array(
        'en'=>'Splash of Strength (2:15)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength_Splash.png',
      'stack'=>1),
    32689=>array(
      'name'=>array(
        'en'=>'Splash of Regeneration II (0:16)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration_Splash.png',
      'stack'=>1),
    32690=>array(
      'name'=>array(
        'en'=>'Splash of Speed II (1:07)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed_Splash.png',
      'stack'=>1),
    32691=>array(
      'name'=>array(
        'en'=>'Splash of Fire Resistance (2:15)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Fire_Resistance_Splash.png',
      'stack'=>1),
    32692=>array(
      'name'=>array(
        'en'=>'Splash of Poison II (0:16)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison_Splash.png',
      'stack'=>1),
    32696=>array(
      'name'=>array(
        'en'=>'Splash of Weakness (1:07)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Weakness_Splash.png',
      'stack'=>1),
    32697=>array(
      'name'=>array(
        'en'=>'Splash of Strength II (1:07)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength_Splash.png',
      'stack'=>1),
    32698=>array(
      'name'=>array(
        'en'=>'Splash of Slowness (1:07)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Slowness_Splash.png',
      'stack'=>1),
    32721=>array(
      'name'=>array(
        'en'=>'Splash of Regeneration (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration_Splash.png',
      'stack'=>1),
    32722=>array(
      'name'=>array(
        'en'=>'Splash of Speed (6:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed_Splash.png',
      'stack'=>1),
    32724=>array(
      'name'=>array(
        'en'=>'Splash of Poison (1:30)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison_Splash.png',
      'stack'=>1),
    32725=>array(
      'name'=>array(
        'en'=>'Instant Health',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Healing_Splash.png',
      'stack'=>1),
    32729=>array(
      'name'=>array(
        'en'=>'Splash of Strength (6:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength_Splash.png',
      'stack'=>1),
    32732=>array(
      'name'=>array(
        'en'=>'Instant Damage',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Harming.png',
      'stack'=>1),
    32753=>array(
      'name'=>array(
        'en'=>'Splash of Regeneration II (0:45)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Regeneration_Splash.png',
      'stack'=>1),
    32754=>array(
      'name'=>array(
        'en'=>'Splash of Speed II (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Speed_Splash.png',
      'stack'=>1),
    32755=>array(
      'name'=>array(
        'en'=>'Splash of Fire Resistance (6:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Fire_Resistance_Splash.png',
      'stack'=>1),
    32756=>array(
      'name'=>array(
        'en'=>'Splash of Poison II (0:45)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Poison_Splash.png',
      'stack'=>1),
    32757=>array(
      'name'=>array(
        'en'=>'Instant Health II',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Instant_Health.png',
      'stack'=>1),
    32760=>array(
      'name'=>array(
        'en'=>'Splash of Weakness (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Weakness_Splash.png',
      'stack'=>1),
    32761=>array(
      'name'=>array(
        'en'=>'Splash of Strength II (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Strength_Splash.png',
      'stack'=>1),
    32762=>array(
      'name'=>array(
        'en'=>'Splash of Slowness (3:00)',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Slowness_Splash.png',
      'stack'=>1),
    32764=>array(
      'name'=>array(
        'en'=>'Instant Damage II',
        ''=>'',
        ''=>''),
      'icon'=>'Potion_Harming_Splash.png',
      'stack'=>1),
    -1   =>array(
      'name'=>array(
        'en'=>'Unknown Potion',
        ''=>'',
        ''=>''),
      'icon'=>'Bottle_Water.png',
      'stack'=>1),
  ),
  374=>array(
    'name'=>array(
      'en'=>'Glass Bottle',
      ''=>'',
      ''=>''),
    'icon'=>'Bottle_Glass.png'),
  375=>array(
    'name'=>array(
      'en'=>'Spider Eye',
      ''=>'',
      ''=>''),
    'icon'=>'Spider_Eye.png'),
  376=>array(
    'name'=>array(
      'en'=>'Fermented Spider Eye',
      ''=>'',
      ''=>''),
    'icon'=>'Fermented_Spider_Eye.png'),
  377=>array(
    'name'=>array(
      'en'=>'Blaze Powder',
      ''=>'',
      ''=>''),
    'icon'=>'Blaze_Powder.png'),
  378=>array(
    'name'=>array(
      'en'=>'Magma Cream',
      ''=>'',
      ''=>''),
    'icon'=>'Magma_Cream.png'),
  379=>array(
    'name'=>array(
      'en'=>'Brewing Stand',
      ''=>'',
      ''=>''),
    'icon'=>'Brewing_Stand.png'),
  380=>array(
    'name'=>array(
      'en'=>'Cauldron',
      ''=>'',
      ''=>''),
    'icon'=>'Cauldron.png'),
  381=>array(
    'name'=>array(
      'en'=>'Eye of Ender',
      ''=>'',
      ''=>''),
    'icon'=>'Eye_of_Ender.png'),
  382=>array(
    'name'=>array(
      'en'=>'Glistering Melon (Slice)',
      ''=>'',
      ''=>''),
    'icon'=>'Melon_Glistering.png'),
  383=>array(
    50 =>array(
      'name'=>array(
        'en'=>'Spawn Creeper',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Creeper.png'),
    51 =>array(
      'name'=>array(
        'en'=>'Spawn Skeleton',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Skeleton.png'),
    52 =>array(
      'name'=>array(
        'en'=>'Spawn Spider',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Spider.png'),
    54 =>array(
      'name'=>array(
        'en'=>'Spawn Zombie',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Zombie.png'),
    55 =>array(
      'name'=>array(
        'en'=>'Spawn Slime',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Slime.png'),
    56 =>array(
      'name'=>array(
        'en'=>'Spawn Ghast',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Ghast.png'),
    57 =>array(
      'name'=>array(
        'en'=>'Spawn Pig Zombie',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Pig_Zombie.png'),
    58 =>array(
      'name'=>array(
        'en'=>'Spawn Enderman',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Enderman.png'),
    59 =>array(
      'name'=>array(
        'en'=>'Spawn Cave_Spider',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Cave_Spider.png'),
    60 =>array(
      'name'=>array(
        'en'=>'Spawn Silverfish',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Silverfish.png'),
    61 =>array(
      'name'=>array(
        'en'=>'Spawn Blaze',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Blaze.png'),
    62 =>array(
      'name'=>array(
        'en'=>'Spawn Magma Cube',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Magma_Cube.png'),
    90 =>array(
      'name'=>array(
        'en'=>'Spawn Pig',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Pig.png'),
    91 =>array(
      'name'=>array(
        'en'=>'Spawn Sheep',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Sheep.png'),
    92 =>array(
      'name'=>array(
        'en'=>'Spawn Cow',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Cow.png'),
    93 =>array(
      'name'=>array(
        'en'=>'Spawn Chicken',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Chicken.png'),
    94 =>array(
      'name'=>array(
        'en'=>'Spawn Squid',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Squid.png'),
    95 =>array(
      'name'=>array(
        'en'=>'Spawn Wolf',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Wolf.png'),
    96 =>array(
      'name'=>array(
        'en'=>'Spawn Mooshroom',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Mooshroom.png'),
    98 =>array(
      'name'=>array(
        'en'=>'Spawn Ocelot',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Ocelot.png'),
    120=>array(
      'name'=>array(
        'en'=>'Spawn Villager',
        ''=>'',
        ''=>''),
      'icon'=>'Spawn_Villager.png'),
    -1 =>array(
      'name'=>array(
        'en'=>'Unknown Spawn Egg',
        ''=>'',
        ''=>''),
      'icon'=>'Egg.png'),
  ),
  384=>array(
    'name'=>array(
      'en'=>'Bottle o\' Enchanting',
      ''=>'',
      ''=>''),
    'icon'=>'Bottle_o_Enchanting.png'),
  385=>array(
    'name'=>array(
      'en'=>'Fire Charge',
      ''=>'',
      ''=>''),
    'icon'=>'Fire_Charge.png'),
  386=>array(
    'name'=>array(
      'en'=>'Book and Quill',
      ''=>'',
      ''=>''),
    'icon'=>'Book_and_Quill.png',
    'stack'=>1),
  387=>array(
    'name'=>array(
      'en'=>'Written Book',
      ''=>'',
      ''=>''),
    'icon'=>'Book_Written.png',
    'stack'=>1),
  388=>array(
    'name'=>array(
      'en'=>'Emerald',
      ''=>'',
      ''=>''),
    'icon'=>'Emerald.png'),
  2256=>array(
    'name'=>array(
      'en'=>'Music Disc (13)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Gold.png',
    'stack'=>1),
  2257=>array(
    'name'=>array(
      'en'=>'Music Disc (Cat)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Green.png',
    'stack'=>1),
  2258=>array(
    'name'=>array(
      'en'=>'Music Disc (Blocks)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Blocks.png',
    'stack'=>1),
  2259=>array(
    'name'=>array(
      'en'=>'Music Disc (Chirp)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Chirp.png',
    'stack'=>1),
  2260=>array(
    'name'=>array(
      'en'=>'Music Disc (Far)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Far.png',
    'stack'=>1),
  2261=>array(
    'name'=>array(
      'en'=>'Music Disc (Mall)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Mall.png',
    'stack'=>1),
  2262=>array(
    'name'=>array(
      'en'=>'Music Disc (Mellohi)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Mellohi.png',
    'stack'=>1),
  2263=>array(
    'name'=>array(
      'en'=>'Music Disc (Stal)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Stal.png',
    'stack'=>1),
  2264=>array(
    'name'=>array(
      'en'=>'Music Disc (Strad)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Strad.png',
    'stack'=>1),
  2265=>array(
    'name'=>array(
      'en'=>'Music Disc (Ward)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_Ward.png',
    'stack'=>1),
  2266=>array(
    'name'=>array(
      'en'=>'Music Disc (11)',
      ''=>'',
      ''=>''),
    'icon'=>'Disc_11.png',
    'stack'=>1),
  -1  =>array(
    'name'=>array(
      'en'=>'Unknown %itemid%',
      ''=>'',
      ''=>''),
    'icon'=>'Unknown.png'),
);


?>