<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// buildcraft item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'ic2';

$Items[218]=array(
  'name'=>'Crops',
  'icon'=>'Crops.png',
  'pack'=>$pack);
$Items[219]=array(
  'name'=>'Luminator',
  'icon'=>'Luminator.png',
  'pack'=>$pack);
$Items[220]=array(
  'name'=>'Scaffold',
  'icon'=>'Scaffold.png',
  'pack'=>$pack);
$Items[221]=array(
  'name'=>'Construction Foam Wall',
  'icon'=>'Construction_Foam_Wall.png',
  'pack'=>$pack);
$Items[222]=array(
  'name'=>'Construction Foam',
  'icon'=>'Construction_Foam.png',
  'pack'=>$pack);
$Items[223]=array(
  0 =>array(
    'name'=>'Teleporter',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Tesla Coil',
    'icon'=>'Tesla_Coil.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
);
$Items[224]=array(
  0 =>array(
    'name'=>'Copper Block',
    'icon'=>'Copper_Block.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Tin Block',
    'icon'=>'Tin_Block.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Bronze Block',
    'icon'=>'Bronze_Block.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Uranium Block',
    'icon'=>'Uranium_Block.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Copper_Block.png',
    'pack'=>$pack),
);
$Items[225]=array(
  0 =>array(
    'name'=>'Personal Safe',
    'icon'=>'Personal_Safe.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Trade-O-Mat',
    'icon'=>'Trade-O-Mat.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Personal_Safe.png',
    'pack'=>$pack),
);
$Items[226]=array(
  'name'=>'Luminator',
  'icon'=>'Luminator.png',
  'pack'=>$pack);
$Items[227]=array(
  0 =>array(
    'name'=>'BatBox',
    'icon'=>'BatBox.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'MFE',
    'icon'=>'MFE_Unit.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'MFSU',
    'icon'=>'MFS_Unit.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'LV-Transformer',
    'icon'=>'LV_Transformer.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'MV-Transformer',
    'icon'=>'MV_Transformer.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'HV-Transformer',
    'icon'=>'HV_Transformer.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'BatBox.png',
    'pack'=>$pack),
);
$Items[230]=array(
  'name'=>'Reinforced Glass',
  'icon'=>'Reinforced_Glass.png',
  'pack'=>$pack);
$Items[231]=array(
  'name'=>'Reinforced Stone',
  'icon'=>'Reinforced_Stone.png',
  'pack'=>$pack);
$Items[232]=array(
  'name'=>'Iron Fence',
  'icon'=>'Iron_Fence.png',
  'pack'=>$pack);
$Items[233]=array(
  'name'=>'Reactor Chamber',
  'icon'=>'Reactor_Chamber.png',
  'pack'=>$pack);
$Items[234]=array(
  'name'=>'Rubber Sheet',
  'icon'=>'Rubber_Sheet.png',
  'pack'=>$pack);
$Items[237]=array(
  'name'=>'Nuke',
  'icon'=>'Nuke.png',
  'pack'=>$pack);
$Items[239]=array(
  'name'=>'Industrial TNT',
  'icon'=>'Industrial_TNT.png',
  'pack'=>$pack);
$Items[241]=array(
  'name'=>'Rubber Tree Sapling',
  'icon'=>'Rubber_Sapling.png',
  'pack'=>$pack);
$Items[242]=array(
  'name'=>'Rubber Tree Leaves',
  'icon'=>'Rubber_Leaves.png',
  'pack'=>$pack);
$Items[243]=array(
  'name'=>'Rubber Wood',
  'icon'=>'Rubber_Wood.png',
  'pack'=>$pack);
$Items[244]=array(
  'name'=>'Mining Pipe',
  'icon'=>'Mining_Pipe_2.png',
  'pack'=>$pack);
$Items[245]=array(
  'name'=>'Mining Pipe',
  'icon'=>'Mining_Pipe.png',
  'pack'=>$pack);
$Items[250]=array(
  0 =>array(
    'name'=>'Machine Block',
    'icon'=>'Machine_Block.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Iron Furnace',
    'icon'=>'Iron_Furnace.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Electric Furnace',
    'icon'=>'Electric_Furnace.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Macerator',
    'icon'=>'Macerator.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Extractor',
    'icon'=>'Extractor.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Compressor',
    'icon'=>'Compressor.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Canning Machine',
    'icon'=>'Canning_Machine.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Miner',
    'icon'=>'Miner.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Pump',
    'icon'=>'Pump.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Magnetizer',
    'icon'=>'Magnetizer.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Electrolyzer',
    'icon'=>'Electrolyzer.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Recycler',
    'icon'=>'Recycler.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Advanced Machine Block',
    'icon'=>'Advanced_Machine_Block.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Induction Furnace',
    'icon'=>'Induction_Furnace.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Mass Fabricator',
    'icon'=>'Mass_Fabricator.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Terraformer',
    'icon'=>'Terraformer.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Machine_Block.png',
    'pack'=>$pack),
);

unset($Items);
?>