<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// industrial craft 2 - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'ic2';

$Items[218]=array(
  'name'=>'Crops',
  'icon'=>'Crops.png',
  'pack'=>$pack);
$Items[219]=array(
  'name'=>'Luminator',
  'icon'=>'Luminator.png',
  'pack'=>$pack);
$Items[220]=array(
  'name'=>'Scaffold',
  'icon'=>'Scaffold.png',
  'pack'=>$pack);
$Items[221]=array(
  'name'=>'Construction Foam Wall',
  'icon'=>'Construction_Foam_Wall.png',
  'pack'=>$pack);
$Items[222]=array(
  'name'=>'Construction Foam',
  'icon'=>'Construction_Foam.png',
  'pack'=>$pack);
$Items[223]=array(
  0 =>array(
    'name'=>'Teleporter',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Tesla Coil',
    'icon'=>'Tesla_Coil.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Teleporter.png',
    'pack'=>$pack),
);
$Items[224]=array(
  0 =>array(
    'name'=>'Copper Block',
    'icon'=>'Copper_Block.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Tin Block',
    'icon'=>'Tin_Block.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Bronze Block',
    'icon'=>'Bronze_Block.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Uranium Block',
    'icon'=>'Uranium_Block.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Copper_Block.png',
    'pack'=>$pack),
);
$Items[225]=array(
  0 =>array(
    'name'=>'Personal Safe',
    'icon'=>'Personal_Safe.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Trade-O-Mat',
    'icon'=>'Trade-O-Mat.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Personal_Safe.png',
    'pack'=>$pack),
);
$Items[226]=array(
  'name'=>'Luminator',
  'icon'=>'Luminator.png',
  'pack'=>$pack);
$Items[227]=array(
  0 =>array(
    'name'=>'BatBox',
    'icon'=>'BatBox.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'MFE',
    'icon'=>'MFE_Unit.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'MFSU',
    'icon'=>'MFS_Unit.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'LV-Transformer',
    'icon'=>'Transformer_LV.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'MV-Transformer',
    'icon'=>'Transformer_MV.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'HV-Transformer',
    'icon'=>'Transformer_HV.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'BatBox.png',
    'pack'=>$pack),
);
$Items[230]=array(
  'name'=>'Reinforced Glass',
  'icon'=>'Reinforced_Glass.png',
  'pack'=>$pack);
$Items[231]=array(
  'name'=>'Reinforced Stone',
  'icon'=>'Reinforced_Stone.png',
  'pack'=>$pack);
$Items[232]=array(
  'name'=>'Iron Fence',
  'icon'=>'Iron_Fence.png',
  'pack'=>$pack);
$Items[233]=array(
  'name'=>'Reactor Chamber',
  'icon'=>'Reactor_Chamber.png',
  'pack'=>$pack);
$Items[234]=array(
  'name'=>'Rubber Trampoline',
  'icon'=>'Rubber_Trampoline.png',
  'pack'=>$pack);
$Items[237]=array(
  'name'=>'Nuke',
  'icon'=>'Nuke.png',
  'pack'=>$pack);
$Items[239]=array(
  'name'=>'Industrial TNT',
  'icon'=>'Industrial_TNT.png',
  'pack'=>$pack);
$Items[241]=array(
  'name'=>'Rubber Tree Sapling',
  'icon'=>'Rubber_Sapling.png',
  'pack'=>$pack);
$Items[242]=array(
  'name'=>'Rubber Tree Leaves',
  'icon'=>'Rubber_Leaves.png',
  'pack'=>$pack);
$Items[243]=array(
  'name'=>'Rubber Wood',
  'icon'=>'Rubber_Wood.png',
  'pack'=>$pack);
$Items[244]=array(
  'name'=>'Mining Pipe',
  'icon'=>'Mining_Pipe_2.png',
  'pack'=>$pack);
$Items[245]=array(
  'name'=>'Mining Pipe',
  'icon'=>'Mining_Pipe.png',
  'pack'=>$pack);
$Items[246]=array(
  0 =>array(
    'name'=>'Generator',
    'icon'=>'Generator.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Geothermal Generator',
    'icon'=>'Generator_Geothermal.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Water Mill',
    'icon'=>'Water_Mill.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Solar Panel',
    'icon'=>'Solar_Panel.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Wind Mill',
    'icon'=>'Wind_Mill.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Nuclear Reactor',
    'icon'=>'Nuclear_Reactor.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Generator.png',
    'pack'=>$pack),
);
$Items[247]=array(
  'name'=>'Uranium Ore',
  'icon'=>'Uranium_Ore_Block.png',
  'pack'=>$pack);
$Items[248]=array(
  'name'=>'Tin Ore',
  'icon'=>'Tin_Ore.png',
  'pack'=>$pack);
$Items[249]=array(
  'name'=>'Copper Ore',
  'icon'=>'Copper_Ore.png',
  'pack'=>$pack);
$Items[250]=array(
  0 =>array(
    'name'=>'Machine Block',
    'icon'=>'Machine_Block.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Iron Furnace',
    'icon'=>'Iron_Furnace.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Electric Furnace',
    'icon'=>'Electric_Furnace.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Macerator',
    'icon'=>'Macerator.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Extractor',
    'icon'=>'Extractor.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Compressor',
    'icon'=>'Compressor.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Canning Machine',
    'icon'=>'Canning_Machine.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'Miner',
    'icon'=>'Miner.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'Pump',
    'icon'=>'Pump.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Magnetizer',
    'icon'=>'Magnetizer.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Electrolyzer',
    'icon'=>'Electrolyzer.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'Recycler',
    'icon'=>'Recycler.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'Advanced Machine Block',
    'icon'=>'Advanced_Machine_Block.png',
    'pack'=>$pack),
  13=>array(
    'name'=>'Induction Furnace',
    'icon'=>'Induction_Furnace.png',
    'pack'=>$pack),
  14=>array(
    'name'=>'Mass Fabricator',
    'icon'=>'Mass_Fabricator.png',
    'pack'=>$pack),
  15=>array(
    'name'=>'Terraformer',
    'icon'=>'Terraformer.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Machine_Block.png',
    'pack'=>$pack),
);
$Items[30031]=array(
  'name'=>'Refined Iron Dust',
  'icon'=>'Refined_Iron_Dust.png',
  'pack'=>$pack);
$Items[30115]=array(
  'name'=>'Static Boots',
  'icon'=>'Static_Boots.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30116]=array(
  'name'=>'Solar Helmet',
  'icon'=>'Solar_Helmet.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30117]=array(
  0 =>array(
    'name'=>'Toolbox',
    'icon'=>'Toolbox.png',
    'stack'=>1,
    'pack'=>$pack),
  1 =>array(
    'name'=>'Toolbox',
    'icon'=>'Toolbox.png',
    'stack'=>1,
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Toolbox',
    'icon'=>'Toolbox.png',
    'stack'=>1,
    'pack'=>$pack),
);
$Items[30118]=array(
  'name'=>'TFBP - Mushroom',
  'icon'=>'TFBP_Mushroom.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30119]=array(
  'type' =>'tool',
  'name' =>'Electric Hoe',
  'title'=>'Electric Hoe %charged%',
  'icon' =>'Electric_Hoe.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30120]=array(
  'name' =>'Hydration Cell',
  'icon' =>'Cell_Hydration.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30121]=array(
  'name'=>'Fertilizer',
  'icon'=>'Fertilizer.png',
  'pack'=>$pack);
$Items[30122]=array(
  'name' =>'Cropnalyzer',
  'icon' =>'Cropnalyzer.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30124]=array(
  'type' =>'tool',
  'name' =>'Electric Treetap',
  'title'=>'Electric Treetap %charged%',
  'icon' =>'Electric_Treetap.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30125]=array(
  0 =>array(
    'name'=>'Overclocker Upgrade',
    'icon'=>'Overclocker_Upgrade.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Transformer Upgrade',
    'icon'=>'Transformer_Upgrade.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Energy Storage Upgrade',
    'icon'=>'Energy_Storage_Upgrade.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Upgrade',
    'icon'=>'Overclocker_Upgrade.png',
    'pack'=>$pack),
);
$Items[30126]=array(
  'name'=>'Seed Bag',
  'icon'=>'Seed_Bag.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30127]=array(
  'type' =>'tool',
  'name' =>'LapPack',
  'title'=>'LapPack %charged%',
  'icon' =>'LapPack.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30128]=array(
  'name'=>'Iridium Ore',
  'icon'=>'Iridium_Ore.png',
  'pack'=>$pack);
$Items[30129]=array(
  'type' =>'tool',
  'name' =>'CF Backpack',
  'title'=>'CF Backpack %damaged%',
  'icon' =>'CFPack.png',
  'damage'=>259,
  'stack'=>1,
  'pack'=>$pack);
$Items[30130]=array(
  'name'=>'Silver Dust',
  'icon'=>'Silver_Dust.png',
  'pack'=>$pack);
$Items[30131]=array(
  'type' =>'tool',
  'name' =>'CF Sprayer',
  'title'=>'CF Sprayer %damaged%',
  'icon' =>'CF_Sprayer.png',
  'damage'=>1600,
  'stack'=>1,
  'pack'=>$pack);
$Items[30132]=array(
  'name'=>'CF Pellet',
  'icon'=>'CF_Pellet.png',
  'pack'=>$pack);
$Items[30133]=array(
  'name'=>'Clay Dust',
  'icon'=>'Clay_Dust.png',
  'pack'=>$pack);
$Items[30134]=array(
  'name'=>'Frequency Transmitter',
  'icon'=>'FreqTrans.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30135]=array(
  'name'=>'Industrial Diamond',
  'icon'=>'Industrial_Diamond.png',
  'pack'=>$pack);
$Items[30136]=array(
  'name'=>'Coal Chunk',
  'icon'=>'Coal_Chunk.png',
  'pack'=>$pack);
$Items[30137]=array(
  'name'=>'Compressed Coal Ball',
  'icon'=>'Coal_Ball_Compressed.png',
  'pack'=>$pack);
$Items[30138]=array(
  'name'=>'Coal Ball',
  'icon'=>'Coal_Ball.png',
  'pack'=>$pack);
$Items[30139]=array(
  'name'=>'Scrap Box',
  'icon'=>'Scrap_Box.png',
  'pack'=>$pack);
$Items[30140]=array(
  'type' =>'tool',
  'name' =>'Electric Wrench',
  'title'=>'Electric Wrench %charged%',
  'icon' =>'Electric_Wrench.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30141]=array(
  'name'=>'TFBP - Flatification',
  'icon'=>'TFBP_Flatificator.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30142]=array(
  'name'=>'TFBP - Desertification',
  'icon'=>'TFBP_Desertification.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30143]=array(
  'name'=>'TFBP - Chilling',
  'icon'=>'TFBP_Chilling.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30144]=array(
  'name'=>'TFBP - Irrigation',
  'icon'=>'TFBP_Irrigation.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30145]=array(
  'name'=>'TFBP - Cultivation',
  'icon'=>'TFBP_Cultivation.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30146]=array(
  'name'=>'TFBP - Empty',
  'icon'=>'TFBP_Empty.png',
  'pack'=>$pack);
$Items[30147]=array(
  'name'=>'Iridium Plate',
  'icon'=>'Iridium_Plate.png',
  'pack'=>$pack);
$Items[30148]=array(
  'type' =>'tool',
  'name'=>'Nano Saber',
  'title'=>'Nano Saber %charged%',
  'icon'=>'Nano_Saber.png',
  'damage'=>25,
  'stack'=>1,
  'pack'=>$pack);
$Items[30149]=array(
  'type' =>'tool',
  'name'=>'Nano Saber',
  'title'=>'Nano Saber %charged%',
  'icon'=>'Nano_Saber.png',
  'damage'=>25,
  'stack'=>1,
  'pack'=>$pack);
$Items[30150]=array(
  'name'=>'Carbon Plate',
  'icon'=>'Carbon_Plate.png',
  'pack'=>$pack);
$Items[30151]=array(
  'name'=>'Raw Carbon Mesh',
  'icon'=>'Raw_Carbon_Mesh.png',
  'pack'=>$pack);
$Items[30152]=array(
  'name'=>'Raw Carbon Fiber',
  'icon'=>'Raw_Carbon_Fibers.png',
  'pack'=>$pack);
$Items[30153]=array(
  'type' =>'tool',
  'name' =>'Insulation Cutter',
  'title'=>'Insulation Cutter %damaged%',
  'icon' =>'Cutter.png',
  'damage'=>513,
  'stack'=>1,
  'pack'=>$pack);
$Items[30154]=array(
  'type' =>'tool',
  'name' =>'White Painter',
  'title'=>'White Painter %damaged%',
  'icon' =>'Painter_White.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30155]=array(
  'type' =>'tool',
  'name' =>'Orange Painter',
  'title'=>'Orange Painter %damaged%',
  'icon' =>'Painter_Orange.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30156]=array(
  'type' =>'tool',
  'name' =>'Pink Painter',
  'title'=>'Pink Painter %damaged%',
  'icon' =>'Painter_Pink.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30157]=array(
  'type' =>'tool',
  'name' =>'Light Blue Painter',
  'title'=>'Light Blue Painter %damaged%',
  'icon' =>'Painter_Light_Blue.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30158]=array(
  'type' =>'tool',
  'name' =>'Yellow Painter',
  'title'=>'Yellow Painter %damaged%',
  'icon' =>'Painter_Yellow.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30159]=array(
  'type' =>'tool',
  'name' =>'Lime Green Painter',
  'title'=>'Lime Green %damaged%',
  'icon' =>'Painter_Lime_Green.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30160]=array(
  'type' =>'tool',
  'name' =>'Light Pink Painter',
  'title'=>'Light Pink Painter %damaged%',
  'icon' =>'Painter_Light_Pink.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30161]=array(
  'type' =>'tool',
  'name' =>'Dark Grey Painter',
  'title'=>'Dark Grey Painter %damaged%',
  'icon' =>'Painter_Dark_Grey.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30162]=array(
  'type' =>'tool',
  'name' =>'Grey Painter',
  'title'=>'Grey Painter %damaged%',
  'icon' =>'Painter_Grey.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30163]=array(
  'type' =>'tool',
  'name' =>'Cyan Painter',
  'title'=>'Cyan Painter %damaged%',
  'icon' =>'Painter_Cyan.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30164]=array(
  'type' =>'tool',
  'name' =>'Purple Painter',
  'title'=>'Purple Painter %damaged%',
  'icon' =>'Painter_Purple.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30165]=array(
  'type' =>'tool',
  'name' =>'Blue Painter',
  'title'=>'Blue Painter %damaged%',
  'icon' =>'Painter_Blue.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30166]=array(
  'type' =>'tool',
  'name' =>'Brown Painter',
  'title'=>'Brown Painter %damaged%',
  'icon' =>'Painter_Brown.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30167]=array(
  'type' =>'tool',
  'name' =>'Green Painter',
  'title'=>'Green Painter %damaged%',
  'icon' =>'Painter_Green.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30168]=array(
  'type' =>'tool',
  'name' =>'Red Painter',
  'title'=>'Red Painter %damaged%',
  'icon' =>'Painter_Red.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30169]=array(
  'type' =>'tool',
  'name' =>'Black Painter',
  'title'=>'Black Painter %damaged%',
  'icon' =>'Painter_Black.png',
  'damage'=>31,
  'stack'=>1,
  'pack'=>$pack);
$Items[30170]=array(
  'name'=>'Used Painter',
  'icon'=>'Painter.png',
  'pack'=>$pack);
$Items[30171]=array(
  'type' =>'tool',
  'name' =>'QuantumSuit Boots',
  'title'=>'QuantumSuit %charged%',
  'icon' =>'QuantumSuit_Boots.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30172]=array(
  'type' =>'tool',
  'name' =>'QuantumSuit Leggings',
  'title'=>'QuantumSuit Leggings %charged%',
  'icon' =>'QuantumSuit_Leggings.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30173]=array(
  'type' =>'tool',
  'name' =>'QuantumSuit Bodyarmor',
  'title'=>'QuantumSuit Bodyarmor %charged%',
  'icon' =>'QuantumSuit_Bodyarmor.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30174]=array(
  'type' =>'tool',
  'name' =>'QuantumSuit Helmet',
  'title'=>'QuantumSuit Helmet %charged%',
  'icon' =>'QuantumSuit_Helmet.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30175]=array(
  'type' =>'tool',
  'name' =>'NanoSuit Boots',
  'title'=>'NanoSuit %charged%',
  'icon' =>'Nano_Boots.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30176]=array(
  'type' =>'tool',
  'name' =>'NanoSuit Leggings',
  'title'=>'NanoSuit Leggings %charged%',
  'icon' =>'Nano_Leggings.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30177]=array(
  'type' =>'tool',
  'name' =>'NanoSuit Bodyarmor',
  'title'=>'NanoSuit Bodyarmor %charged%',
  'icon' =>'Nano_Bodyarmor.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30178]=array(
  'type' =>'tool',
  'name' =>'NanoSuit Helmet',
  'title'=>'NanoSuit Helmet %charged%',
  'icon' =>'Nano_Helmet.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30179]=array(
  'type' =>'tool',
  'name' =>'Composite Armor Vest',
  'title'=>'Composite Armor Vest %damaged%',
  'icon' =>'Composite_Armor_Vest.png',
  'damage'=>800,
  'stack'=>1,
  'pack'=>$pack);
$Items[30180]=array(
  'type' =>'tool',
  'name' =>'BatPack',
  'title'=>'BatPack %charged%',
  'icon' =>'BatPack.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30181]=array(
  'name'=>'Electrolyzed Water Cell',
  'icon'=>'Cell_Electrolyzed_Water.png',
  'pack'=>$pack);
$Items[30182]=array(
  'name'=>'EU-Reader (EC-Meter)',
  'icon'=>'EU-Reader.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30183]=array(
  'type' =>'tool',
  'name' =>'Wrench',
  'title'=>'Wrench %damaged%',
  'icon' =>'Wrench.png',
  'damage'=>160,
  'stack'=>1,
  'pack'=>$pack);
$Items[30184]=array(
  0 =>array(
    'name'=>'Insulated Copper Cable',
    'icon'=>'Cable_Copper_Insulated.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Uninsulated Copper Cable',
    'icon'=>'Cable_Copper_Uninsulated.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Uninsulated Gold Cable',
    'icon'=>'Cable_Gold_Uninsulated.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Insulated Gold Cable',
    'icon'=>'Cable_Gold_Insulated.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'2x Insulated Gold Cable',
    'icon'=>'Cable_Gold_2x_Insulated.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Uninsulated HV Cable',
    'icon'=>'Cable_HV_Uninsulated.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Insulated HV Cable',
    'icon'=>'Cable_HV_Insulated.png',
    'pack'=>$pack),
  7 =>array(
    'name'=>'2x Insulated HV Cable',
    'icon'=>'Cable_HV_2x_Insulated.png',
    'pack'=>$pack),
  8 =>array(
    'name'=>'3x Insulated HV Cable',
    'icon'=>'Cable_HV_3x_Insulated.png',
    'pack'=>$pack),
  9 =>array(
    'name'=>'Glass Fibre Cable',
    'icon'=>'Cable_Glass_Fibre.png',
    'pack'=>$pack),
  10=>array(
    'name'=>'Ultra-Low-Current Cable',
    'icon'=>'Cable_Tin.png',
    'pack'=>$pack),
  11=>array(
    'name'=>'EU-Detector Cable',
    'icon'=>'Cable_Detector.png',
    'pack'=>$pack),
  12=>array(
    'name'=>'EU-Splitter Cable',
    'icon'=>'Cable_Splitter.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Cable',
    'icon'=>'Cable_Copper_Insulated.png',
    'pack'=>$pack),
);
$Items[30185]=array(
  'name'=>'Reinforced Door',
  'icon'=>'Reinforced_Door.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30186]=array(
  'name'=>'Industrial Credit',
  'icon'=>'Industrial_Credit.png',
  'pack'=>$pack);
$Items[30187]=array(
  'name'=>'Advanced Alloy',
  'icon'=>'Advanced_Alloy.png',
  'pack'=>$pack);
$Items[30188]=array(
  'name'=>'UU-Matter',
  'icon'=>'UU-Matter.png',
  'pack'=>$pack);
$Items[30189]=array(
  'name'=>'Scrap',
  'icon'=>'Scrap.png',
  'pack'=>$pack);
$Items[30190]=array(
  'name'=>'Advanced Circuit',
  'icon'=>'Advanced_Circuit.png',
  'pack'=>$pack);
$Items[30191]=array(
  'name'=>'Electronic Circuit',
  'icon'=>'Electronic_Circuit.png',
  'pack'=>$pack);
$Items[30192]=array(
  'type' =>'tool',
  'name' =>'Bronze Boots',
  'title'=>'Bronze Boots %damaged%',
  'icon' =>'Bronze_Boots.png',
  'damage'=>195,
  'stack'=>1,
  'pack'=>$pack);
$Items[30193]=array(
  'type' =>'tool',
  'name' =>'Bronze Leggings',
  'title'=>'Bronze Leggings %damaged%',
  'icon' =>'Bronze_Leggings.png',
  'damage'=>225,
  'stack'=>1,
  'pack'=>$pack);
$Items[30194]=array(
  'type' =>'tool',
  'name' =>'Bronze Chestplate',
  'title'=>'Bronze Chestplate %damaged%',
  'icon' =>'Bronze_Chestplate.png',
  'damage'=>240,
  'stack'=>1,
  'pack'=>$pack);
$Items[30195]=array(
  'type' =>'tool',
  'name' =>'Bronze Helmet',
  'title'=>'Bronze Helmet %damaged%',
  'icon' =>'Bronze_Helmet.png',
  'damage'=>165,
  'stack'=>1,
  'pack'=>$pack);
$Items[30196]=array(
  'type' =>'tool',
  'name' =>'Bronze Hoe',
  'title'=>'Bronze Hoe %damaged%',
  'icon' =>'Bronze_Hoe.png',
  'damage'=>350,
  'stack'=>1,
  'pack'=>$pack);
$Items[30197]=array(
  'type' =>'tool',
  'name' =>'Bronze Shovel',
  'title'=>'Bronze Shovel %damaged%',
  'icon' =>'Bronze_Shovel.png',
  'damage'=>350,
  'stack'=>1,
  'pack'=>$pack);
$Items[30198]=array(
  'type' =>'tool',
  'name' =>'Bronze Sword',
  'title'=>'Bronze Sword %damaged%',
  'icon' =>'Bronze_Sword.png',
  'damage'=>350,
  'stack'=>1,
  'pack'=>$pack);
$Items[30199]=array(
  'type' =>'tool',
  'name' =>'Bronze Axe',
  'title'=>'Bronze Axe %damaged%',
  'icon' =>'Bronze_Axe.png',
  'damage'=>350,
  'stack'=>1,
  'pack'=>$pack);
$Items[30200]=array(
  'type' =>'tool',
  'name' =>'Bronze Pickaxe',
  'title'=>'Bronze Pickaxe %damaged%',
  'icon' =>'Bronze_Pickaxe.png',
  'damage'=>350,
  'stack'=>1,
  'pack'=>$pack);
$Items[30201]=array(
  'name'=>'Near-depleted Uranium Cell',
  'icon'=>'Cell_Uranium_Near-Depleted.png',
  'pack'=>$pack);
$Items[30202]=array(
  'name'=>'Re-Enriched Uranium Cell',
  'icon'=>'Cell_Uranium_Re-Enriched.png',
  'pack'=>$pack);
$Items[30203]=array(
  'name'=>'Depleted Isotope Cell',
  'icon'=>'Cell_Depleted_Isotope.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30204]=array(
  'name'=>'Integrated Heat Disperser',
  'icon'=>'Integrated_Heat_Disperser.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30205]=array(
  'name'=>'Integrated Reactor Plating',
  'icon'=>'Integrated_Reactor_Plating.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30206]=array(
  'name'=>'Coolant Cell',
  'icon'=>'Cell_Cooling.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30207]=array(
  'name'=>'Uranium Cell',
  'icon'=>'Cell_Uranium.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30208]=array(
  'type' =>'tool',
  'name' =>'Mining Laser',
  'title'=>'Mining Laser %charged%',
  'icon' =>'Mining_Laser.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30209]=array(
  'type' =>'tool',
  'name' =>'Jetpack',
  'title'=>'Electric Jetpack %charged%',
  'icon' =>'Jetpack_Electric.png',
  'damage'=>18003,
  'stack'=>1,
  'pack'=>$pack);
$Items[30210]=array(
  'type' =>'tool',
  'name' =>'Jetpack',
  'title'=>'Jetpack %charged%',
  'icon' =>'Jetpack.png',
  'damage'=>18003,
  'stack'=>1,
  'pack'=>$pack);
$Items[30211]=array(
  'type' =>'tool',
  'name' =>'Rubber Boots',
  'title'=>'Rubber Boots %damaged%',
  'icon' =>'Rubber_Boots.png',
  'damage'=>65,
  'stack'=>1,
  'pack'=>$pack);
$Items[30212]=array(
  'type' =>'tool',
  'name' =>'Treetap',
  'title'=>'Treetap %damaged%',
  'icon' =>'Treetap.png',
  'damage'=>16,
  'stack'=>1,
  'pack'=>$pack);
$Items[30213]=array(
  'name'=>'Dynamite-O-Mote',
  'icon'=>'Dynamite-O-Mote.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30214]=array(
  'name'=>'Sticky Dynamite',
  'icon'=>'Dynamite_Sticky.png',
  'stack'=>16,
  'pack'=>$pack);
$Items[30215]=array(
  'name'=>'Dynamite',
  'icon'=>'Dynamite.png',
  'stack'=>16,
  'pack'=>$pack);
$Items[30216]=array(
  'name'=>'Rubber',
  'icon'=>'Rubber.png',
  'pack'=>$pack);
$Items[30217]=array(
  'name'=>'Sticky Resin',
  'icon'=>'Resin.png',
  'pack'=>$pack);
$Items[30218]=array(
  'name'=>'Water Cell',
  'icon'=>'Cell_Water.png',
  'pack'=>$pack);
$Items[30219]=array(
  'type' =>'tool',
  'name' =>'OV Scanner',
  'title'=>'OV Scanner %damaged%',
  'icon' =>'OV_Scanner.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30220]=array(
  'type' =>'tool',
  'name' =>'OD Scanner',
  'title'=>'OD Scanner %damaged%',
  'icon' =>'OD_Scanner.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30221]=array(
  'name'=>'Filled Tin Can',
  'icon'=>'Tin_Can_Filled.png',
  'pack'=>$pack);
$Items[30222]=array(
  'name'=>'Tin Can',
  'icon'=>'Tin_Can.png',
  'pack'=>$pack);
$Items[30223]=array(
  'name'=>'Compressed Plants',
  'icon'=>'Compressed_Plants.png',
  'pack'=>$pack);
$Items[30224]=array(
  'name'=>'Plantball',
  'icon'=>'Plantball.png',
  'pack'=>$pack);
$Items[30225]=array(
  'name'=>'H. Coal',
  'icon'=>'H_Coal.png',
  'pack'=>$pack);
$Items[30226]=array(
  'name'=>'Hydrated Coal Dust',
  'icon'=>'Coal_Dust_Hydrated.png',
  'pack'=>$pack);
$Items[30227]=array(
  'name'=>'Biofuel Cell',
  'icon'=>'Cell_Biofuel.png',
  'pack'=>$pack);
$Items[30228]=array(
  'name'=>'Coalfuel Cell',
  'icon'=>'Cell_Coalfuel.png',
  'pack'=>$pack);
$Items[30229]=array(
  'name'=>'Bio Cell',
  'icon'=>'Cell_Bio.png',
  'pack'=>$pack);
$Items[30230]=array(
  'name'=>'H. Coal Cell',
  'icon'=>'Cell_H_Coal.png',
  'pack'=>$pack);
$Items[30231]=array(
  'name'=>'Empty Fuel Can',
  'icon'=>'Fuel_Can_Empty.png',
  'pack'=>$pack);
$Items[30232]=array(
  'name'=>'Filled Fuel Can',
  'icon'=>'Fuel_Can_Filled.png',
  'stack'=>1,
  'pack'=>$pack);
$Items[30233]=array(
  'type' =>'tool',
  'name' =>'Chainsaw',
  'title'=>'Chainsaw %charged%',
  'icon' =>'Chainsaw.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30234]=array(
  'type' =>'tool',
  'name' =>'Diamond Drill',
  'title'=>'Diamond Drill %charged%',
  'icon' =>'Diamond_Drill.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30235]=array(
  'type' =>'tool',
  'name' =>'Mining Drill',
  'title'=>'Mining Drill %charged%',
  'icon' =>'Mining_Drill.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30236]=array(
  'name'=>'Lava Cell',
  'icon'=>'Cell_Lava.png',
  'pack'=>$pack);
$Items[30237]=array(
  'name'=>'Empty Cell',
  'icon'=>'Cell_Empty.png',
  'pack'=>$pack);
$Items[30238]=array(
  'name'=>'Single-Use Battery',
  'icon'=>'Single_Use_Battery.png',
  'pack'=>$pack);
$Items[30239]=array(
  'name'=>'RE-Battery',
  'icon'=>'RE_Battery.png',
  'pack'=>$pack);
$Items[30240]=array(
  'type' =>'tool',
  'name' =>'Lapotron Crystal',
  'title'=>'Lapotron Crystal %charged%',
  'icon' =>'Lapotron_Crystal.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30241]=array(
  'type' =>'tool',
  'name' =>'Energy Crystal',
  'title'=>'Energy Crystal %damaged%',
  'icon' =>'Energy_Crystal.png',
  'damage'=>27,
  'stack'=>1,
  'pack'=>$pack);
$Items[30242]=array(
  'type' =>'tool',
  'name' =>'RE-Battery',
  'title'=>'RE-Battery %charged%',
  'icon' =>'RE_Battery.png',
  'damage'=>27,
  'stack'=>16,
  'pack'=>$pack);
$Items[30243]=array(
  'name'=>'Uranium Ore',
  'icon'=>'Uranium_Ore_Dust.png',
  'pack'=>$pack);
$Items[30244]=array(
  'name'=>'Refined Uranium',
  'icon'=>'Uranium_Refined.png',
  'pack'=>$pack);
$Items[30245]=array(
  'name'=>'Mixed Metal Ingot',
  'icon'=>'Mixed_Metal_Ingot.png',
  'pack'=>$pack);
$Items[30246]=array(
  'name'=>'Bronze Ingot',
  'icon'=>'Bronze_Ingot.png',
  'pack'=>$pack);
$Items[30247]=array(
  'name'=>'Tin Ingot',
  'icon'=>'Tin_Ingot.png',
  'pack'=>$pack);
$Items[30248]=array(
  'name'=>'Copper Ingot',
  'icon'=>'Copper_Ingot.png',
  'pack'=>$pack);
$Items[30249]=array(
  'name'=>'Refined Iron',
  'icon'=>'Refined_Iron.png',
  'pack'=>$pack);
$Items[30250]=array(
  'name'=>'Small Pile of Iron Dust',
  'icon'=>'Iron_Dust_Heap.png',
  'pack'=>$pack);
$Items[30251]=array(
  'name'=>'Bronze Dust',
  'icon'=>'Bronze_Dust.png',
  'pack'=>$pack);
$Items[30252]=array(
  'name'=>'Tin Dust',
  'icon'=>'Tin_Dust.png',
  'pack'=>$pack);
$Items[30253]=array(
  'name'=>'Copper Dust',
  'icon'=>'Copper_Dust.png',
  'pack'=>$pack);
$Items[30254]=array(
  'name'=>'Gold Dust',
  'icon'=>'Gold_Dust.png',
  'pack'=>$pack);
$Items[30255]=array(
  'name'=>'Iron Dust',
  'icon'=>'Iron_Dust.png',
  'pack'=>$pack);
$Items[30256]=array(
  'name'=>'Coal Dust',
  'icon'=>'Coal_Dust.png',
  'pack'=>$pack);

unset($Items);
?>