<?php if(!defined('DEFINE_INDEX_FILE')){if(headers_sent()){echo '<header><meta http-equiv="refresh" content="0;url=../"></header>';}else{header('HTTP/1.0 301 Moved Permanently'); header('Location: ../');} die("<font size=+2>Access Denied!!</font>");}
// Computer Craft Sensors - item definitions
$Items = &ItemFuncs::$Items;
$pack  = 'ComputerCraftSensors';

$Items[215]=array(
  0 =>array(
    'name'=>'Sensor',
    'icon'=>'Sensor.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Sensor Controller',
    'icon'=>'Sensor_Controller.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Item',
    'icon'=>'Sensor.png',
    'pack'=>$pack),
);
$Items[1492]=array(
  0 =>array(
    'name'=>'Blank Sensor Card',
    'icon'=>'Sensor_Card_Blank.png',
    'pack'=>$pack,
    'sensor'=>16),
  1 =>array(
    'name'=>'World SensorModule',
    'icon'=>'SensorModule_World.png',
    'pack'=>$pack,
    'sensor'=>16),
  2 =>array(
    'name'=>'Inventory SensorModule',
    'icon'=>'SensorModule_Inventory.png',
    'pack'=>$pack,
    'sensor'=>16),
  3 =>array(
    'name'=>'BuildCraft SensorModule',
    'icon'=>'SensorModule_BuildCraft.png',
    'pack'=>$pack,
    'sensor'=>16),
  4 =>array(
    'name'=>'IndustrialCraft2 SensorModule',
    'icon'=>'SensorModule_IndustrialCraft2.png',
    'pack'=>$pack,
    'sensor'=>16),
  5 =>array(
    'name'=>'Forestry SensorModule',
    'icon'=>'SensorModule_Forestry.png',
    'pack'=>$pack,
    'sensor'=>16),
  6 =>array(
    'name'=>'RedPower2 SensorModule',
    'icon'=>'SensorModule_RedPower2.png',
    'pack'=>$pack,
    'sensor'=>16),
  7 =>array(
    'name'=>'EquivalentExchange SensorModule',
    'icon'=>'SensorModule_EquivalentExchange.png',
    'pack'=>$pack,
    'sensor'=>16),
  8 =>array(
    'name'=>'Advanced Power Systems SensorModule',
    'icon'=>'SensorModule_Advanced_Power_Systems.png',
    'pack'=>$pack,
    'sensor'=>16),
  9 =>array(
    'name'=>'Thaumcraft2 SensorModule',
    'icon'=>'SensorModule_Thaumcraft2.png',
    'pack'=>$pack,
    'sensor'=>16),
  10=>array(
    'name'=>'Proximity SensorModule',
    'icon'=>'SensorModule_Proximity.png',
    'pack'=>$pack,
    'sensor'=>16),
  -1=>array(
    'name'=>'Unknown SensorModule',
    'icon'=>'Sensor_Card_Blank.png',
    'pack'=>$pack,
    'sensor'=>16),
);
$Items[1493]=array(
  0 =>array(
    'name'=>'Blank Transmitter Card',
    'icon'=>'Transmitter_Card_Blank.png',
    'pack'=>$pack,
    'stack'=>32),
  1 =>array(
    'name'=>'Transmitter Card (Red)',
    'icon'=>'Transmitter_Card_Red.png',
    'pack'=>$pack,
    'stack'=>32),
  2 =>array(
    'name'=>'Transmitter Card (Purple)',
    'icon'=>'Transmitter_Card_Purple.png',
    'pack'=>$pack,
    'stack'=>32),
  3 =>array(
    'name'=>'Transmitter Card (Blue)',
    'icon'=>'Transmitter_Card_Blue.png',
    'pack'=>$pack,
    'stack'=>32),
  4 =>array(
    'name'=>'Transmitter Card (Cyan)',
    'icon'=>'Transmitter_Card_Cyan.png',
    'pack'=>$pack,
    'stack'=>32),
  5 =>array(
    'name'=>'Transmitter Card (Green)',
    'icon'=>'Transmitter_Card_Green.png',
    'pack'=>$pack,
    'stack'=>32),
  6 =>array(
    'name'=>'Transmitter Card (Yellow)',
    'icon'=>'',
    'pack'=>$pack,
    'stack'=>32),
  7 =>array(
    'name'=>'Transmitter Card (White)',
    'icon'=>'Transmitter_Card_White.png',
    'pack'=>$pack,
    'stack'=>32),
  8 =>array(
    'name'=>'Transmitter Card (Orange)',
    'icon'=>'Transmitter_Card_Orange.png',
    'pack'=>$pack,
    'stack'=>32),
  9 =>array(
    'name'=>'Transmitter Card (Black)',
    'icon'=>'Transmitter_Card_Black.png',
    'pack'=>$pack,
    'stack'=>32),
  10=>array(
    'name'=>'Transmitter Card (Pink)',
    'icon'=>'Transmitter_Card_Pink.png',
    'pack'=>$pack,
    'stack'=>32),
  -1=>array(
    'name'=>'Unknown Transmitter Card',
    'icon'=>'Transmitter_Card_Blank.png',
    'pack'=>$pack,
    'stack'=>32),
);
$Items[1494]=array(
  0 =>array(
    'name'=>'Computer Chip (Redstone)',
    'icon'=>'Computer_Chip_Redstone.png',
    'pack'=>$pack),
  1 =>array(
    'name'=>'Computer Chip (Iron)',
    'icon'=>'Computer_Chip_Iron.png',
    'pack'=>$pack),
  2 =>array(
    'name'=>'Computer Chip (Gold)',
    'icon'=>'Computer_Chip_Gold.png',
    'pack'=>$pack),
  3 =>array(
    'name'=>'Computer Chip (Diamond)',
    'icon'=>'Computer_Chip_Diamond.png',
    'pack'=>$pack),
  4 =>array(
    'name'=>'Computer Chip (Glass)',
    'icon'=>'Computer_Chip_Glass.png',
    'pack'=>$pack),
  5 =>array(
    'name'=>'Computer Chip (Stone)',
    'icon'=>'Computer_Chip_Stone.png',
    'pack'=>$pack),
  6 =>array(
    'name'=>'Computer Chip (Obsidian)',
    'icon'=>'Computer_Chip_Obsidian.png',
    'pack'=>$pack),
  -1=>array(
    'name'=>'Unknown Computer Chip',
    'icon'=>'Computer_Chip_Redstone.png',
    'pack'=>$pack),
);

unset($Items);
?>